// src/components/AdminSidebar.tsx
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
import {
  LayoutDashboard,
  Users,
  MapPin,
  FileText,
  Shield,
  BarChart3,
  ChevronLeft,
  ChevronRight,
  LogOut,
} from 'lucide-react';
import { cn } from '@/lib/utils';

const menuItems = [
  { path: '/admin/dashboard', label: '数据概览', icon: LayoutDashboard },
  { path: '/admin/workers', label: '阿姨审核', icon: Users },
  { path: '/admin/dispatch', label: '调度中心', icon: MapPin },
  { path: '/admin/sop', label: 'SOP文档库', icon: FileText },
  { path: '/admin/insurance', label: '保险配置', icon: Shield },
  { path: '/admin/qa', label: '质检分析', icon: BarChart3 },
];

export default function AdminSidebar() {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <aside
      className={cn(
        'h-screen bg-secondary-800 text-white flex flex-col transition-all duration-300 sticky top-0',
        collapsed ? 'w-20' : 'w-64'
      )}
    >
      <div className="h-16 flex items-center justify-between px-4 border-b border-secondary-700">
        {!collapsed && (
          <div className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-secondary-400 to-secondary-600 flex items-center justify-center">
              <span className="font-bold">暖</span>
            </div>
            <div>
              <h2 className="text-sm font-bold leading-tight">管理后台</h2>
              <p className="text-xs text-secondary-300">暖心到家</p>
            </div>
          </div>
        )}
        {collapsed && (
          <div className="w-9 h-9 mx-auto rounded-xl bg-gradient-to-br from-secondary-400 to-secondary-600 flex items-center justify-center">
            <span className="font-bold">暖</span>
          </div>
        )}
      </div>

      <nav className="flex-1 py-4 px-2 space-y-1 overflow-y-auto scrollbar-hide">
        {menuItems.map((item) => {
          const Icon = item.icon;
          return (
            <NavLink
              key={item.path}
              to={item.path}
              className={({ isActive }) =>
                cn(
                  'flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all duration-200',
                  'hover:bg-secondary-700/60',
                  isActive
                    ? 'bg-secondary-600 text-white shadow-lg shadow-secondary-900/30'
                    : 'text-secondary-200',
                  collapsed && 'justify-center px-2'
                )
              }
              title={collapsed ? item.label : undefined}
            >
              <Icon className="w-5 h-5 flex-shrink-0" />
              {!collapsed && <span className="text-sm font-medium">{item.label}</span>}
            </NavLink>
          );
        })}
      </nav>

      <div className="p-2 border-t border-secondary-700 space-y-1">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-secondary-200 hover:bg-secondary-700/60 transition-colors"
        >
          {collapsed ? (
            <ChevronRight className="w-5 h-5 mx-auto" />
          ) : (
            <>
              <ChevronLeft className="w-5 h-5" />
              <span className="text-sm font-medium">收起菜单</span>
            </>
          )}
        </button>
        <button
          className={cn(
            'w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-secondary-200 hover:bg-red-600/20 hover:text-red-300 transition-colors',
            collapsed && 'justify-center px-2'
          )}
          title={collapsed ? '退出登录' : undefined}
        >
          <LogOut className="w-5 h-5" />
          {!collapsed && <span className="text-sm font-medium">退出登录</span>}
        </button>
      </div>
    </aside>
  );
}

// src/layouts/components/AdminSidebar.vue
<template>
  <aside
    class="h-screen bg-neutral-900 border-r border-neutral-800 flex flex-col transition-all duration-300"
    :class="collapsed ? 'w-16' : 'w-64'"
  >
    <div class="h-16 flex items-center justify-between px-4 border-b border-neutral-800 shrink-0">
      <div v-if="!collapsed" class="flex items-center gap-2.5">
        <div class="w-8 h-8 bg-gov-gradient rounded-lg flex items-center justify-center">
          <Building2 class="w-4 h-4 text-white" />
        </div>
        <div class="flex flex-col">
          <span class="text-sm font-bold text-white leading-tight">抚州政务</span>
          <span class="text-xs text-neutral-500 leading-tight">管理后台</span>
        </div>
      </div>
      <div v-else class="w-full flex justify-center">
        <div class="w-8 h-8 bg-gov-gradient rounded-lg flex items-center justify-center">
          <Building2 class="w-4 h-4 text-white" />
        </div>
      </div>
    </div>

    <nav class="flex-1 py-4 overflow-y-auto scrollbar-thin">
      <el-menu
        :default-active="activeMenu"
        background-color="#1A1F29"
        text-color="#94A3B8"
        active-text-color="#60A5FA"
        :collapse="collapsed"
        :collapse-transition="false"
        router
        class="admin-menu !border-none"
      >
        <el-menu-item index="/admin">
          <template #icon>
            <LayoutDashboard class="w-5 h-5" />
          </template>
          <span>工作台</span>
        </el-menu-item>

        <el-sub-menu index="services-group">
          <template #title>
            <Briefcase class="w-5 h-5 mr-2" />
            <span>服务管理</span>
          </template>
          <el-menu-item index="/admin/services">服务列表</el-menu-item>
          <el-menu-item index="/admin/forms">表单管理</el-menu-item>
        </el-sub-menu>

        <el-menu-item index="/admin/monitor">
          <template #icon>
            <Activity class="w-5 h-5" />
          </template>
          <span>实时监控</span>
        </el-menu-item>

        <el-menu-item index="/admin/tickets">
          <template #icon>
            <Ticket class="w-5 h-5" />
          </template>
          <span>工单处理</span>
        </el-menu-item>

        <el-menu-item index="/admin/evaluations">
          <template #icon>
            <Star class="w-5 h-5" />
          </template>
          <span>评价管理</span>
        </el-menu-item>

        <el-menu-item index="/admin/reports">
          <template #icon>
            <BarChart3 class="w-5 h-5" />
          </template>
          <span>数据报表</span>
        </el-menu-item>

        <el-menu-item index="/admin/users">
          <template #icon>
            <Users class="w-5 h-5" />
          </template>
          <span>用户管理</span>
        </el-menu-item>
      </el-menu>
    </nav>

    <div class="p-3 border-t border-neutral-800 shrink-0">
      <button
        class="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-neutral-400 hover:text-white hover:bg-neutral-800 transition-all duration-200"
        @click="$emit('toggle-collapse')"
      >
        <ChevronLeft v-if="!collapsed" class="w-4 h-4" />
        <ChevronRight v-else class="w-4 h-4" />
        <span v-if="!collapsed" class="text-sm">收起菜单</span>
      </button>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import {
  Building2,
  LayoutDashboard,
  Briefcase,
  Activity,
  Ticket,
  Star,
  BarChart3,
  Users,
  ChevronLeft,
  ChevronRight,
} from 'lucide-vue-next'

defineProps<{
  collapsed: boolean
}>()

defineEmits<{
  (e: 'toggle-collapse'): void
}>()

const route = useRoute()
const activeMenu = computed(() => route.path)
</script>

<style>
.admin-menu .el-menu-item,
.admin-menu .el-sub-menu__title {
  height: 44px !important;
  line-height: 44px !important;
  margin: 2px 8px !important;
  border-radius: 8px !important;
}

.admin-menu .el-menu-item:hover,
.admin-menu .el-sub-menu__title:hover {
  background-color: rgba(96, 165, 250, 0.1) !important;
}

.admin-menu .el-menu-item.is-active {
  background-color: rgba(96, 165, 250, 0.15) !important;
  color: #60A5FA !important;
}

.admin-menu .el-sub-menu .el-menu-item {
  padding-left: 48px !important;
}

.admin-menu:not(.el-menu--collapse) .el-sub-menu .el-menu-item {
  min-width: calc(100% - 16px) !important;
}
</style>
