// apps/frontend/src/pages/Login.tsx
import React, { useState } from 'react';
import { Form, Input, Button, Card, Tabs, App, Typography } from 'antd';
import { UserOutlined, LockOutlined, MailOutlined, PhoneOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { authAPI } from '../services/api';
import { useAuthStore } from '../store';

const { Title, Text } = Typography;

const LoginPage: React.FC = () => {
  const navigate = useNavigate();
  const { message } = App.useApp();
  const setAuth = useAuthStore((s) => s.setAuth);
  const [loading, setLoading] = useState(false);
  const [mode, setMode] = useState<'login' | 'register'>('login');

  const handleLogin = async (values: any) => {
    setLoading(true);
    try {
      const result: any = await authAPI.login(values);
      setAuth(result);
      message.success('登录成功');
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  };

  const handleRegister = async (values: any) => {
    setLoading(true);
    try {
      const result: any = await authAPI.register(values);
      setAuth(result);
      message.success('注册成功');
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      padding: 24,
    }}>
      <Card style={{ width: 420, boxShadow: '0 10px 40px rgba(0,0,0,0.15)' }}>
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <div style={{ fontSize: 48, color: '#1677ff', marginBottom: 12 }}>⚡</div>
          <Title level={3} style={{ margin: 0 }}>IoT 统一管控平台</Title>
          <Text type="secondary">跨品牌智能设备统一管理</Text>
        </div>

        <Tabs
          activeKey={mode}
          onChange={(k) => setMode(k as any)}
          centered
          items={[
            {
              key: 'login',
              label: '登录',
              children: (
                <Form
                  layout="vertical"
                  onFinish={handleLogin}
                  initialValues={{ username: '', password: '' }}
                  size="large"
                >
                  <Form.Item
                    name="username"
                    label="用户名 / 邮箱 / 手机号"
                    rules={[{ required: true, message: '请输入登录信息' }]}
                  >
                    <Input prefix={<UserOutlined />} placeholder="请输入用户名" />
                  </Form.Item>
                  <Form.Item
                    name="password"
                    label="密码"
                    rules={[{ required: true, message: '请输入密码' }]}
                  >
                    <Input.Password prefix={<LockOutlined />} placeholder="请输入密码" />
                  </Form.Item>
                  <Form.Item>
                    <Button type="primary" htmlType="submit" loading={loading} block>
                      登录
                    </Button>
                  </Form.Item>
                  <div style={{ textAlign: 'center', color: '#999', fontSize: 12 }}>
                    测试账户: demo / demo1234
                  </div>
                </Form>
              ),
            },
            {
              key: 'register',
              label: '注册',
              children: (
                <Form
                  layout="vertical"
                  onFinish={handleRegister}
                  size="large"
                >
                  <Form.Item
                    name="username"
                    label="用户名"
                    rules={[{ required: true, min: 3, message: '用户名至少3位' }]}
                  >
                    <Input prefix={<UserOutlined />} placeholder="请设置用户名" />
                  </Form.Item>
                  <Form.Item name="email" label="邮箱 (可选)">
                    <Input prefix={<MailOutlined />} placeholder="请输入邮箱" />
                  </Form.Item>
                  <Form.Item name="phone" label="手机号 (可选)">
                    <Input prefix={<PhoneOutlined />} placeholder="请输入手机号" />
                  </Form.Item>
                  <Form.Item
                    name="password"
                    label="密码"
                    rules={[{ required: true, min: 8, message: '密码至少8位' }]}
                  >
                    <Input.Password prefix={<LockOutlined />} placeholder="请设置密码" />
                  </Form.Item>
                  <Form.Item>
                    <Button type="primary" htmlType="submit" loading={loading} block>
                      注册
                    </Button>
                  </Form.Item>
                </Form>
              ),
            },
          ]}
        />
      </Card>
    </div>
  );
};

export default LoginPage;

// frontend/src/views/login/index.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <div class="login-header">
        <h2>物流信息交互平台</h2>
        <p>企业协作 · 高效物流</p>
      </div>
      <el-form
        ref="loginFormRef"
        :model="loginForm"
        :rules="loginRules"
        class="login-form"
      >
        <el-form-item prop="username">
          <el-input
            v-model="loginForm.username"
            placeholder="请输入用户名"
            prefix-icon="User"
            size="large"
          />
        </el-form-item>
        <el-form-item prop="password">
          <el-input
            v-model="loginForm.password"
            type="password"
            placeholder="请输入密码"
            prefix-icon="Lock"
            size="large"
            show-password
            @keyup.enter="handleLogin"
          />
        </el-form-item>
        <el-form-item>
          <el-button
            type="primary"
            size="large"
            :loading="loading"
            class="login-btn"
            @click="handleLogin"
          >
            登录
          </el-button>
        </el-form-item>
      </el-form>
      <div class="login-footer">
        <span>还没有账号？</span>
        <el-link type="primary" @click="goRegister">立即注册</el-link>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, type FormInstance, type FormRules } from 'element-plus';
import { useUserStore } from '@/stores/user';

const router = useRouter();
const userStore = useUserStore();

const loginFormRef = ref<FormInstance>();
const loading = ref(false);

const loginForm = reactive({
  username: '',
  password: '',
});

const loginRules: FormRules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
};

const handleLogin = async () => {
  if (!loginFormRef.value) return;

  await loginFormRef.value.validate(async (valid) => {
    if (valid) {
      loading.value = true;
      try {
        const result = await userStore.login(loginForm);
        if (result.success) {
          ElMessage.success('登录成功');
          if (userStore.isAdmin) {
            router.push('/admin/dashboard');
          } else {
            router.push('/enterprise/dashboard');
          }
        }
      } catch (error: any) {
        console.error('Login error:', error);
      } finally {
        loading.value = false;
      }
    }
  });
};

const goRegister = () => {
  router.push('/register');
};
</script>

<style scoped>
.login-container {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-box {
  width: 420px;
  padding: 40px;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}

.login-header {
  text-align: center;
  margin-bottom: 30px;
}

.login-header h2 {
  margin: 0 0 10px 0;
  color: #303133;
  font-size: 24px;
}

.login-header p {
  margin: 0;
  color: #909399;
  font-size: 14px;
}

.login-form {
  margin-top: 20px;
}

.login-btn {
  width: 100%;
}

.login-footer {
  text-align: center;
  margin-top: 20px;
  color: #909399;
  font-size: 14px;
}
</style>
