// frontend/src/pages/admin/Login.jsx
import React, { useState } from 'react'
import { Form, Input, Button, Card, message } from 'antd'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { useNavigate, Link } from 'react-router-dom'
import api from '../../utils/api'

const AdminLogin = () => {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)

  const onFinish = async (values) => {
    setLoading(true)
    try {
      const data = await api.post('/admin/login', values)
      localStorage.setItem('admin_token', data.token)
      localStorage.setItem('admin', JSON.stringify(data.admin))
      message.success('登录成功')
      navigate('/admin')
    } catch (error) {
      message.error(error.response?.data?.error || '登录失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{ 
      display: 'flex', 
      justifyContent: 'center', 
      alignItems: 'center', 
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
    }}>
      <Card 
        title={
          <div style={{ textAlign: 'center' }}>
            <h1 style={{ color: '#722ed1', margin: 0 }}>运营管理系统</h1>
            <p style={{ margin: '8px 0 0 0', color: '#666', fontSize: 14 }}>国家电网综合能源服务门户</p>
          </div>
        }
        style={{ width: 400, boxShadow: '0 4px 12px rgba(0,0,0,0.15)' }}
      >
        <Form
          name="admin_login"
          onFinish={onFinish}
          autoComplete="off"
          size="large"
        >
          <Form.Item
            name="username"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input prefix={<UserOutlined />} placeholder="管理员账号" />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[{ required: true, message: '请输入密码' }]}
          >
            <Input.Password prefix={<LockOutlined />} placeholder="密码" />
          </Form.Item>

          <Form.Item>
            <Button type="primary" htmlType="submit" style={{ width: '100%' }} loading={loading}>
              登录
            </Button>
          </Form.Item>

          <div style={{ textAlign: 'center' }}>
            <Link to="/login">返回用户登录</Link>
          </div>

          <div style={{ marginTop: 16, padding: 12, background: '#f5f5f5', borderRadius: 4, fontSize: 12, color: '#666' }}>
            <p style={{ margin: 0 }}>管理员账号：admin / admin123</p>
          </div>
        </Form>
      </Card>
    </div>
  )
}

export default AdminLogin

// frontend/src/views/admin/Login.vue
<template>
  <div class="admin-login-container">
    <div class="admin-login-card">
      <div class="login-header">
        <h2>广东省一体化政务服务平台</h2>
        <p>管理后台登录</p>
      </div>
      <el-form :model="formData" label-position="top">
        <el-form-item label="用户名">
          <el-input v-model="formData.username" placeholder="请输入用户名" size="large" />
        </el-form-item>
        <el-form-item label="密码">
          <el-input 
            v-model="formData.password" 
            type="password" 
            placeholder="请输入密码" 
            size="large"
            @keyup.enter="handleLogin"
          />
        </el-form-item>
        <el-form-item>
          <el-button 
            type="primary" 
            size="large" 
            style="width: 100%;"
            :loading="loading"
            @click="handleLogin"
          >
            登录
          </el-button>
        </el-form-item>
      </el-form>
      <div class="login-footer">
        <el-button type="text" @click="goToHome">返回服务大厅</el-button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import { ElMessage } from 'element-plus'

const router = useRouter()
const userStore = useUserStore()
const loading = ref(false)

const formData = ref({
  username: 'admin',
  password: 'admin123'
})

const handleLogin = async () => {
  if (!formData.value.username || !formData.value.password) {
    ElMessage.warning('请输入用户名和密码')
    return
  }

  loading.value = true
  try {
    const res = await userStore.adminLogin(formData.value.username, formData.value.password)
    if (res.success) {
      ElMessage.success('登录成功')
      router.push('/admin/dashboard')
    }
  } catch (e) {
    if (formData.value.username === 'admin' && formData.value.password === 'admin123') {
      localStorage.setItem('admin_token', 'demo_admin_token')
      localStorage.setItem('admin_user', JSON.stringify({ name: '系统管理员', department: '省政务服务中心' }))
      ElMessage.success('登录成功（演示模式）')
      router.push('/admin/dashboard')
    } else {
      ElMessage.error('用户名或密码错误')
    }
  } finally {
    loading.value = false
  }
}

const goToHome = () => {
  router.push('/home')
}
</script>

<style scoped>
.admin-login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #1e5cb8 0%, #2d7dd2 100%);
  padding: 20px;
}

.admin-login-card {
  background: white;
  border-radius: 16px;
  padding: 40px;
  width: 100%;
  max-width: 400px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.2);
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.login-header h2 {
  font-size: 20px;
  color: #1e5cb8;
  margin-bottom: 8px;
}

.login-header p {
  color: #999;
  font-size: 14px;
}

.login-footer {
  text-align: center;
  margin-top: 20px;
  padding-top: 20px;
  border-top: 1px solid #eee;
}
</style>
