// frontend/src/views/Address.vue
<template>
  <div class="min-h-screen bg-pdd-bg">
    <div class="sticky top-0 bg-white z-30 px-3 py-2 border-b flex items-center">
      <button @click="$router.back()" class="text-xl">←</button>
      <h1 class="flex-1 text-center font-medium">收货地址</h1>
      <button @click="showAddModal = true" class="text-pdd-red text-sm">+ 新增</button>
    </div>

    <div v-if="loading" class="py-10">
      <Loading />
    </div>

    <div v-else-if="addresses.length === 0" class="py-20">
      <Empty icon="📍" text="暂无收货地址" />
      <div class="text-center mt-4">
        <button @click="showAddModal = true" class="px-6 py-2 bg-pdd-red text-white rounded-full text-sm">
          添加地址
        </button>
      </div>
    </div>

    <div v-else class="p-3 space-y-2">
      <div
        v-for="addr in addresses"
        :key="addr.id"
        class="bg-white rounded-lg p-3"
      >
        <div class="flex items-center gap-2">
          <span class="font-medium">{{ addr.name }}</span>
          <span class="text-gray-500 text-sm">{{ addr.phone }}</span>
          <span v-if="addr.is_default" class="px-2 py-0.5 bg-pdd-red/10 text-pdd-red text-xs rounded">默认</span>
        </div>
        <p class="text-sm text-gray-600 mt-1">{{ addr.province }}{{ addr.city }}{{ addr.district }}{{ addr.detail }}</p>
        <div class="flex items-center gap-4 mt-2 text-sm text-gray-500">
          <button @click="setDefault(addr)" class="flex items-center gap-1">
            <span>{{ addr.is_default ? '☑️' : '⬜' }}</span>
            <span>设为默认</span>
          </button>
          <button @click="editAddress(addr)" class="flex items-center gap-1">
            <span>✏️</span>
            <span>编辑</span>
          </button>
          <button @click="deleteAddress(addr.id)" class="flex items-center gap-1">
            <span>🗑️</span>
            <span>删除</span>
          </button>
        </div>
      </div>
    </div>

    <div v-if="showAddModal" class="fixed inset-0 bg-black/50 z-50 flex items-end">
      <div class="w-full bg-white rounded-t-xl p-4">
        <div class="flex items-center justify-between mb-4">
          <h3 class="font-medium">{{ editingId ? '编辑地址' : '新增地址' }}</h3>
          <button @click="closeModal" class="text-xl">✕</button>
        </div>
        <div class="space-y-3">
          <input
            v-model="form.name"
            type="text"
            placeholder="收货人姓名"
            class="w-full px-3 py-2 border border-gray-200 rounded text-sm"
          />
          <input
            v-model="form.phone"
            type="tel"
            placeholder="手机号码"
            class="w-full px-3 py-2 border border-gray-200 rounded text-sm"
          />
          <div class="flex gap-2">
            <input
              v-model="form.province"
              type="text"
              placeholder="省份"
              class="flex-1 px-3 py-2 border border-gray-200 rounded text-sm"
            />
            <input
              v-model="form.city"
              type="text"
              placeholder="城市"
              class="flex-1 px-3 py-2 border border-gray-200 rounded text-sm"
            />
          </div>
          <input
            v-model="form.district"
            type="text"
            placeholder="区县"
            class="w-full px-3 py-2 border border-gray-200 rounded text-sm"
          />
          <textarea
            v-model="form.detail"
            placeholder="详细地址"
            rows="2"
            class="w-full px-3 py-2 border border-gray-200 rounded text-sm resize-none"
          ></textarea>
          <label class="flex items-center gap-2 text-sm">
            <input type="checkbox" v-model="form.is_default" />
            <span>设为默认地址</span>
          </label>
        </div>
        <div class="mt-4">
          <button
            @click="saveAddress"
            :disabled="submitting"
            class="w-full py-2 bg-pdd-red text-white rounded-full text-sm disabled:bg-gray-300"
          >
            {{ submitting ? '保存中...' : '保存' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, reactive } from 'vue'
import { useToast } from '../stores/toast'
import { addressApi } from '../api'
import Loading from '../components/Loading.vue'
import Empty from '../components/Empty.vue'

const toast = useToast()

const loading = ref(true)
const addresses = ref([])
const showAddModal = ref(false)
const editingId = ref(null)
const submitting = ref(false)

const form = reactive({
  name: '',
  phone: '',
  province: '',
  city: '',
  district: '',
  detail: '',
  is_default: false
})

async function loadAddresses() {
  loading.value = true
  try {
    const res = await addressApi.getList()
    if (res.success) {
      addresses.value = res.data || []
    }
  } catch (e) {
    console.error('加载地址列表失败:', e)
  } finally {
    loading.value = false
  }
}

function resetForm() {
  form.name = ''
  form.phone = ''
  form.province = ''
  form.city = ''
  form.district = ''
  form.detail = ''
  form.is_default = false
  editingId.value = null
}

function editAddress(addr) {
  editingId.value = addr.id
  form.name = addr.name
  form.phone = addr.phone
  form.province = addr.province
  form.city = addr.city
  form.district = addr.district
  form.detail = addr.detail
  form.is_default = addr.is_default
  showAddModal.value = true
}

function closeModal() {
  showAddModal.value = false
  resetForm()
}

async function saveAddress() {
  if (!form.name || !form.phone || !form.detail) {
    toast.warning('请填写完整信息')
    return
  }

  submitting.value = true
  try {
    let res
    if (editingId.value) {
      res = await addressApi.update(editingId.value, form)
    } else {
      res = await addressApi.create(form)
    }
    
    if (res.success) {
      toast.success('保存成功')
      closeModal()
      loadAddresses()
    }
  } catch (e) {
    console.error('保存地址失败:', e)
  } finally {
    submitting.value = false
  }
}

async function setDefault(addr) {
  try {
    const res = await addressApi.setDefault(addr.id)
    if (res.success) {
      toast.success('设置成功')
      loadAddresses()
    }
  } catch (e) {
    console.error('设置默认地址失败:', e)
  }
}

async function deleteAddress(id) {
  try {
    const res = await addressApi.delete(id)
    if (res.success) {
      toast.success('删除成功')
      loadAddresses()
    }
  } catch (e) {
    console.error('删除地址失败:', e)
  }
}

onMounted(() => {
  loadAddresses()
})
</script>

// frontend/src/pages/user/Address.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Plus, MapPin, Home, Building2, Edit3, Trash2, Star, CheckCircle2 } from 'lucide-react';
import Card from '../../components/ui/Card';

interface AddressItem {
  id: string; name: string; phone: string; address: string; tag: 'home' | 'company' | 'school' | 'other'; isDefault: boolean;
}

const tagConfig = {
  home: { label: '家', icon: Home, color: 'bg-blue-50 text-blue-600' },
  company: { label: '公司', icon: Building2, color: 'bg-purple-50 text-purple-600' },
  school: { label: '学校', icon: Building2, color: 'bg-green-50 text-green-600' },
  other: { label: '其他', icon: MapPin, color: 'bg-gray-50 text-gray-600' },
};

const mockAddresses: AddressItem[] = [
  { id: '1', name: '张三', phone: '138****8888', address: '北京市朝阳区望京SOHO T1 1201室', tag: 'home', isDefault: true },
  { id: '2', name: '张三', phone: '138****8888', address: '北京市海淀区中关村软件园二期8号楼3层', tag: 'company', isDefault: false },
  { id: '3', name: '李女士', phone: '139****6666', address: '北京市东城区国瑞城A座2205', tag: 'other', isDefault: false },
];

export default function AddressPage() {
  const navigate = useNavigate();
  const [addresses, setAddresses] = useState(mockAddresses);
  const [showAddModal, setShowAddModal] = useState(false);

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="sticky top-0 z-40 bg-white border-b border-gray-100">
        <div className="flex items-center justify-between h-14 px-4">
          <button onClick={() => navigate(-1)} className="p-2 -ml-2 rounded-full hover:bg-gray-100"><ArrowLeft className="w-5 h-5 text-gray-700" /></button>
          <h1 className="text-base font-semibold text-gray-900">地址管理</h1>
          <button onClick={() => setShowAddModal(true)} className="p-2 -mr-2 rounded-full hover:bg-gray-100"><Plus className="w-5 h-5 text-brand-500" /></button>
        </div>
      </div>

      <div className="px-4 py-3 space-y-3">
        {addresses.map((addr) => {
          const tag = tagConfig[addr.tag];
          const TagIcon = tag.icon;
          return (
            <Card key={addr.id} hover>
              <div className="flex items-start gap-3">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 ${tag.color}`}><TagIcon className="w-5 h-5" /></div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-medium text-gray-800">{addr.name}</span>
                    <span className="text-sm text-gray-500">{addr.phone}</span>
                    {addr.isDefault && <span className="flex items-center gap-0.5 px-1.5 py-0.5 bg-brand-50 text-brand-600 rounded text-xs font-medium"><Star className="w-3 h-3" />默认</span>}
                    <span className={`px-1.5 py-0.5 rounded text-xs font-medium ${tag.color}`}>{tag.label}</span>
                  </div>
                  <p className="text-sm text-gray-600 line-clamp-2">{addr.address}</p>
                </div>
              </div>
              <div className="flex items-center justify-end gap-4 mt-3 pt-3 border-t border-gray-50">
                {!addr.isDefault && <button onClick={() => setAddresses(addresses.map((a) => ({ ...a, isDefault: a.id === addr.id })))} className="text-xs text-brand-600 hover:text-brand-700 font-medium">设为默认</button>}
                <button className="text-xs text-gray-500 hover:text-gray-700 flex items-center gap-1"><Edit3 className="w-3 h-3" />编辑</button>
                <button onClick={() => setAddresses(addresses.filter((a) => a.id !== addr.id))} className="text-xs text-red-500 hover:text-red-600 flex items-center gap-1"><Trash2 className="w-3 h-3" />删除</button>
              </div>
            </Card>
          );
        })}
        <button onClick={() => setShowAddModal(true)} className="w-full py-4 border-2 border-dashed border-gray-300 rounded-2xl flex items-center justify-center gap-2 text-gray-500 hover:border-brand-400 hover:text-brand-500">
          <Plus className="w-5 h-5" /><span className="font-medium">添加新地址</span>
        </button>
      </div>

      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40" onClick={() => setShowAddModal(false)}>
          <div className="w-full max-w-[480px] bg-white rounded-t-3xl p-6" onClick={(e) => e.stopPropagation()}>
            <h3 className="text-lg font-bold text-gray-900 mb-4">添加地址</h3>
            <div className="space-y-3">
              <div className="flex gap-3">
                <input placeholder="姓名" className="flex-1 px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-brand-500" />
                <input placeholder="手机号" className="flex-1 px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-brand-500" />
              </div>
              <div className="flex gap-2">
                {Object.entries(tagConfig).map(([key, cfg]) => (
                  <button key={key} className="flex-1 py-2.5 rounded-xl border border-gray-200 text-sm font-medium text-gray-600 hover:border-brand-400 hover:text-brand-600">{cfg.label}</button>
                ))}
              </div>
              <textarea placeholder="详细地址：街道、门牌号、楼层等" rows={3} className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none" />
            </div>
            <button onClick={() => setShowAddModal(false)} className="w-full mt-4 py-3 bg-gradient-to-r from-brand-500 to-brand-600 text-white rounded-xl font-medium">保存地址</button>
          </div>
        </div>
      )}
    </div>
  );
}
