// frontend/src/components/BottomNav.vue
<template>
  <div class="bottom-nav">
    <div 
      v-for="item in navItems" 
      :key="item.path"
      class="nav-item"
      :class="{ active: currentPath === item.path }"
      @click="navigate(item.path)"
    >
      <component :is="item.icon" class="nav-icon" />
      <span class="nav-text">{{ item.text }}</span>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { Home, Grid, Edit, ShoppingCart, User } from 'lucide-vue-next'

const router = useRouter()
const currentPath = computed(() => router.currentRoute.value.path)

const navItems = [
  { path: '/', text: '首页', icon: Home },
  { path: '/category', text: '分类', icon: Grid },
  { path: '/publish', text: '发布', icon: Edit },
  { path: '/cart', text: '购物车', icon: ShoppingCart },
  { path: '/profile', text: '我的', icon: User }
]

function navigate(path) {
  router.push(path)
}
</script>

<style scoped>
.bottom-nav {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 60px;
  background: white;
  display: flex;
  align-items: center;
  justify-content: space-around;
  box-shadow: 0 -2px 10px rgba(0, 0, 0, 0.05);
  z-index: 100;
  padding-bottom: env(safe-area-inset-bottom);
}

.nav-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  flex: 1;
  height: 100%;
  transition: all 0.3s;
}

.nav-icon {
  width: 24px;
  height: 24px;
  color: #999;
  transition: color 0.3s;
}

.nav-text {
  font-size: 11px;
  color: #999;
  margin-top: 4px;
  transition: color 0.3s;
}

.nav-item.active .nav-icon,
.nav-item.active .nav-text {
  color: #2563eb;
}
</style>

// frontend/src/components/BottomNav.jsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Home, Video, PlusSquare, MessageCircle, User } from 'lucide-react';

function BottomNav() {
  const location = useLocation();
  const currentPath = location.pathname;

  const navItems = [
    { path: '/', icon: Home, label: '首页' },
    { path: '/moments', icon: Video, label: '动态' },
    { path: '/create-live', icon: PlusSquare, label: '开播', special: true },
    { path: '/messages', icon: MessageCircle, label: '消息' },
    { path: '/profile', icon: User, label: '我的' }
  ];

  const isHidden = currentPath.startsWith('/live-room/') || 
                   currentPath === '/login' || 
                   currentPath === '/register';

  if (isHidden) {
    return null;
  }

  return (
    <div style={{
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      background: 'white',
      borderTop: '1px solid #eee',
      display: 'flex',
      justifyContent: 'space-around',
      alignItems: 'center',
      padding: '8px 0',
      paddingBottom: 'calc(8px + env(safe-area-inset-bottom))',
      zIndex: 100
    }}>
      {navItems.map((item) => (
        <Link
          key={item.path}
          to={item.path}
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textDecoration: 'none',
            color: currentPath === item.path ? '#ff4757' : '#999',
            fontSize: '11px',
            position: 'relative',
            flex: 1
          }}
        >
          {item.special ? (
            <div style={{
              width: '48px',
              height: '32px',
              borderRadius: '16px',
              background: 'linear-gradient(135deg, #ff4757, #ff6b81)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              marginBottom: '4px'
            }}>
              <item.icon size={20} color="white" />
            </div>
          ) : (
            <>
              <item.icon size={22} style={{ marginBottom: '4px' }} />
              <span>{item.label}</span>
            </>
          )}
        </Link>
      ))}
    </div>
  );
}

export default BottomNav;
