// src/components/ProductCard.tsx
import { useNavigate } from 'react-router-dom';
import { ShoppingCart, Star, Package, Pill } from 'lucide-react';
import type { Product } from '@shared/types';
import { cn } from '@/lib/utils';

interface ProductCardProps {
  product: Product;
}

export default function ProductCard({ product }: ProductCardProps) {
  const navigate = useNavigate();

  return (
    <div
      onClick={() => navigate(`/shop/${product.id}`)}
      className="card cursor-pointer group overflow-hidden p-0"
    >
      <div className="aspect-square bg-gradient-to-br from-cream-50 to-cream-100 flex items-center justify-center relative">
        {product.images?.[0] ? (
          <img
            src={product.images[0]}
            alt={product.name}
            className="w-full h-full object-cover"
          />
        ) : (
          <Package className="w-16 h-16 text-forest-300" />
        )}
        {product.isPrescription && (
          <div className="absolute top-3 left-3 flex items-center gap-1 px-2 py-1 rounded-full bg-warm-100 text-warm-500 text-xs font-medium">
            <Pill className="w-3 h-3" />
            处方药
          </div>
        )}
        {product.stock < 10 && product.stock > 0 && (
          <div className="absolute top-3 right-3 px-2 py-1 rounded-full bg-red-100 text-red-500 text-xs font-medium">
            仅剩{product.stock}件
          </div>
        )}
      </div>

      <div className="p-4">
        <h3 className="font-medium text-gray-900 line-clamp-2 mb-2 group-hover:text-forest-600 transition-colors">
          {product.name}
        </h3>

        <div className="flex items-center gap-1 mb-3">
          <div className="flex items-center gap-0.5">
            {[1, 2, 3, 4, 5].map((i) => (
              <Star
                key={i}
                className={cn(
                  'w-3 h-3',
                  i <= 4 ? 'text-warm-400 fill-warm-400' : 'text-gray-200'
                )}
              />
            ))}
          </div>
          <span className="text-xs text-gray-400">({Math.floor(Math.random() * 500 + 50)})</span>
        </div>

        <div className="flex items-end justify-between">
          <div>
            <span className="text-xs text-gray-400">¥</span>
            <span className="text-xl font-bold text-warm-500">{product.price.toFixed(2)}</span>
          </div>
          <button
            onClick={(e) => {
              e.stopPropagation();
            }}
            className="p-2.5 rounded-xl bg-forest-500 text-white hover:bg-forest-600 transition-colors shadow-soft"
          >
            <ShoppingCart className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/ProductCard.vue
<template>
  <div
    class="bg-white rounded-lg overflow-hidden shadow-sm"
    @click="$router.push(`/product/${product?.id}`)"
  >
    <div class="relative">
      <img
        :src="product?.image"
        :alt="product?.name"
        class="w-full aspect-square object-cover"
        loading="lazy"
      />
      <div
        v-if="product?.is_buy === 1"
        class="absolute top-2 left-2 bg-pdd-red text-white text-xs px-2 py-0.5 rounded"
      >
        百亿补贴
      </div>
    </div>
    <div class="p-2">
      <h3 class="text-sm text-gray-800 line-clamp-2 min-h-[36px]">{{ product?.name }}</h3>
      <div class="flex items-end gap-1 mt-1">
        <span class="text-pdd-red text-lg font-bold">¥{{ product?.price?.toFixed?.(2) || product?.price }}</span>
        <span v-if="product?.original_price" class="text-gray-400 text-xs line-through mb-0.5">¥{{ product?.original_price?.toFixed?.(2) || product?.original_price }}</span>
      </div>
      <div class="flex items-center justify-between mt-1">
        <span class="text-gray-400 text-xs">已拼{{ formatSales(product?.sales) }}件</span>
        <button
          @click.stop="toggleFavorite"
          class="text-xl"
          :class="product?.is_favorite ? 'text-pdd-red' : 'text-gray-300'"
        >
          {{ product?.is_favorite ? '❤️' : '🤍' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useRouter } from 'vue-router'
import { useUserStore } from '../stores/user'
import { useToast } from '../stores/toast'
import { productApi } from '../api'

const props = defineProps({
  product: {
    type: Object,
    default: () => ({})
  }
})

const emit = defineEmits(['update:favorite'])

const router = useRouter()
const userStore = useUserStore()
const toast = useToast()

function formatSales(sales) {
  if (!sales) return '0'
  if (sales >= 10000) {
    return (sales / 10000).toFixed(1) + '万'
  }
  return sales.toString()
}

async function toggleFavorite() {
  if (!userStore.isLoggedIn) {
    router.push({ name: 'Login', query: { redirect: router.currentRoute.value.fullPath } })
    return
  }
  
  try {
    const res = await productApi.toggleFavorite(props.product.id)
    if (res.success) {
      emit('update:favorite', {
        productId: props.product.id,
        isFavorite: res.data.is_favorite
      })
      toast.success(res.data.is_favorite ? '已收藏' : '已取消收藏')
    }
  } catch (e) {
    console.error('收藏失败:', e)
  }
}
</script>
