// frontend/src/components/Toast.vue
<template>
  <transition-group name="toast" tag="div" class="fixed top-20 left-1/2 -translate-x-1/2 z-50 flex flex-col gap-2">
    <div
      v-for="msg in toastStore.messages"
      :key="msg.id"
      class="px-4 py-2 rounded-lg text-white text-sm shadow-lg min-w-[120px] text-center"
      :class="{
        'bg-green-500': msg.type === 'success',
        'bg-red-500': msg.type === 'error',
        'bg-yellow-500': msg.type === 'warning',
        'bg-gray-700': msg.type === 'info'
      }"
    >
      {{ msg.message }}
    </div>
  </transition-group>
</template>

<script setup>
import { useToast } from '../stores/toast'

const toastStore = useToast()
</script>

<style scoped>
.toast-enter-active,
.toast-leave-active {
  transition: all 0.3s ease;
}

.toast-enter-from,
.toast-leave-to {
  opacity: 0;
  transform: translate(-50%, -20px);
}
</style>

// frontend/src/components/Toast.tsx
import React, { useEffect, useState } from 'react';

interface ToastProps {
  message: string;
  type?: 'success' | 'error' | 'info';
  duration?: number;
  onClose: () => void;
}

const Toast: React.FC<ToastProps> = ({ message, type = 'info', duration = 2000, onClose }) => {
  useEffect(() => {
    const timer = setTimeout(onClose, duration);
    return () => clearTimeout(timer);
  }, [duration, onClose]);

  const bgColor = type === 'success' ? 'bg-green-500' : type === 'error' ? 'bg-red-500' : 'bg-blue-500';

  return (
    <div className={`fixed top-20 left-1/2 transform -translate-x-1/2 z-50 ${bgColor} text-white px-6 py-3 rounded-lg shadow-lg`}>
      {message}
    </div>
  );
};

let globalShowToast: (message: string, type?: 'success' | 'error' | 'info') => void;

export const ToastContainer: React.FC = () => {
  const [toasts, setToasts] = useState<{ id: number; message: string; type: 'success' | 'error' | 'info' }[]>([]);

  globalShowToast = (message, type = 'info') => {
    const id = Date.now();
    setToasts((prev) => [...prev, { id, message, type }]);
  };

  const removeToast = (id: number) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  };

  return (
    <>
      {toasts.map((toast) => (
        <Toast key={toast.id} message={toast.message} type={toast.type} onClose={() => removeToast(toast.id)} />
      ))}
    </>
  );
};

export const showToast = (message: string, type: 'success' | 'error' | 'info' = 'info') => {
  if (globalShowToast) {
    globalShowToast(message, type);
  }
};
