// frontend/src/components/Toast.vue
<template>
  <transition-group name="toast" tag="div" class="fixed top-20 left-1/2 -translate-x-1/2 z-50 flex flex-col gap-2">
    <div
      v-for="msg in toastStore.messages"
      :key="msg.id"
      class="px-4 py-2 rounded-lg text-white text-sm shadow-lg min-w-[120px] text-center"
      :class="{
        'bg-green-500': msg.type === 'success',
        'bg-red-500': msg.type === 'error',
        'bg-yellow-500': msg.type === 'warning',
        'bg-gray-700': msg.type === 'info'
      }"
    >
      {{ msg.message }}
    </div>
  </transition-group>
</template>

<script setup>
import { useToast } from '../stores/toast'

const toastStore = useToast()
</script>

<style scoped>
.toast-enter-active,
.toast-leave-active {
  transition: all 0.3s ease;
}

.toast-enter-from,
.toast-leave-to {
  opacity: 0;
  transform: translate(-50%, -20px);
}
</style>

// frontend/src/components/Toast.jsx
import { useToastStore } from '@/store';
import { X, CheckCircle, AlertCircle, Info } from 'lucide-react';
import { cn } from '@/utils';

const iconMap = {
  success: CheckCircle,
  error: AlertCircle,
  info: Info,
  warning: AlertCircle,
};

export default function Toast() {
  const { toasts, removeToast } = useToastStore();

  return (
    <div className="fixed top-4 right-4 z-50 flex flex-col gap-2">
      {toasts.map((toast) => {
        const Icon = iconMap[toast.type] || Info;
        return (
          <div
            key={toast.id}
            className={cn(
              'flex items-center gap-3 px-4 py-3 rounded-lg shadow-lg text-white min-w-[280px]',
              toast.type === 'error' ? 'bg-red-500' :
              toast.type === 'success' ? 'bg-green-500' :
              'bg-blue-500'
            )}
          >
            <Icon size={20} />
            <span className="flex-1 text-sm">{toast.message}</span>
            <button
              onClick={() => removeToast(toast.id)}
              className="hover:opacity-80 transition-opacity"
            >
              <X size={18} />
            </button>
          </div>
        );
      })}
    </div>
  );
}
