// apps/web/src/views/login/index.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <div class="login-header">
        <el-icon :size="40" color="#409EFF"><Coffee /></el-icon>
        <h1>食品生产管理系统</h1>
        <p>原料入库 - 领料生产 - 批次质检 - 成品入库 - 发货追溯</p>
      </div>
      <el-form ref="formRef" :model="loginForm" :rules="rules" class="login-form">
        <el-form-item prop="username">
          <el-input
            v-model="loginForm.username"
            placeholder="请输入用户名"
            prefix-icon="User"
            size="large"
          />
        </el-form-item>
        <el-form-item prop="password">
          <el-input
            v-model="loginForm.password"
            type="password"
            placeholder="请输入密码"
            prefix-icon="Lock"
            size="large"
            show-password
            @keyup.enter="handleLogin"
          />
        </el-form-item>
        <el-form-item>
          <el-button
            type="primary"
            size="large"
            :loading="loading"
            @click="handleLogin"
            style="width: 100%"
          >
            登录
          </el-button>
        </el-form-item>
      </el-form>
      <div class="login-footer">
        <p>系统角色说明：</p>
        <div class="role-list">
          <el-tag type="primary" size="small">采购人员</el-tag>
          <el-tag type="success" size="small">仓库管理</el-tag>
          <el-tag type="warning" size="small">生产班组</el-tag>
          <el-tag type="danger" size="small">质检人员</el-tag>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import type { FormInstance, FormRules } from 'element-plus'
import { ElMessage } from 'element-plus'

const router = useRouter()
const userStore = useUserStore()

const formRef = ref<FormInstance>()
const loading = ref(false)

const loginForm = reactive({
  username: 'admin',
  password: '123456',
})

const rules: FormRules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
}

const handleLogin = async () => {
  if (!formRef.value) return

  await formRef.value.validate(async (valid) => {
    if (!valid) return

    loading.value = true
    try {
      userStore.setToken('mock-token-' + Date.now())
      userStore.setUserInfo({
        id: '1',
        username: loginForm.username,
        name: '管理员',
        role: 'ADMIN',
      })
      ElMessage.success('登录成功')
      router.push('/dashboard')
    } catch (error) {
      ElMessage.error('登录失败')
    } finally {
      loading.value = false
    }
  })
}
</script>

<style lang="scss" scoped>
.login-container {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-box {
  width: 420px;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
  padding: 40px;

  .login-header {
    text-align: center;
    margin-bottom: 40px;

    h1 {
      margin: 16px 0 8px;
      font-size: 24px;
      color: #333;
    }

    p {
      font-size: 14px;
      color: #999;
    }
  }

  .login-form {
    .el-form-item {
      margin-bottom: 24px;
    }
  }

  .login-footer {
    margin-top: 32px;
    padding-top: 24px;
    border-top: 1px solid #eee;

    p {
      font-size: 12px;
      color: #999;
      margin-bottom: 12px;
    }

    .role-list {
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
    }
  }
}
</style>

// frontend/src/pages/Login/Login.tsx
import React, { useState } from 'react';
import { Form, Input, Button, Card, Typography, message } from 'antd';
import { UserOutlined, LockOutlined, LoginOutlined } from '@ant-design/icons';
import { useAuth } from '@/hooks/useAuth';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuthStore } from '@/store/auth';

const { Title } = Typography;

interface LoginFormValues {
  username: string;
  password: string;
}

export const Login: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [form] = Form.useForm();
  const { login, getDashboardPath } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const { isAuthenticated, user } = useAuthStore();

  React.useEffect(() => {
    if (isAuthenticated && user) {
      const from = (location.state as any)?.from?.pathname || getDashboardPath(user.role);
      navigate(from, { replace: true });
    }
  }, [isAuthenticated, user, navigate, location.state, getDashboardPath]);

  const onFinish = async (values: LoginFormValues) => {
    setLoading(true);
    try {
      const success = await login(values);
      if (!success) {
        message.error('用户名或密码错误');
      }
    } catch (error) {
      message.error('登录失败，请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  const quickLogin = async (username: string, password: string) => {
    form.setFieldsValue({ username, password });
    setLoading(true);
    try {
      await login({ username, password });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      }}
    >
      <Card
        style={{
          width: 400,
          boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
        }}
      >
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <Title level={3} style={{ marginBottom: 8 }}>
            医院预约挂号系统
          </Title>
          <Typography.Text type="secondary">请登录以继续使用</Typography.Text>
        </div>

        <Form
          form={form}
          name="login"
          onFinish={onFinish}
          autoComplete="off"
          size="large"
        >
          <Form.Item
            name="username"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input
              prefix={<UserOutlined style={{ color: 'rgba(0,0,0,.25)' }} />}
              placeholder="用户名"
            />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[{ required: true, message: '请输入密码' }]}
          >
            <Input.Password
              prefix={<LockOutlined style={{ color: 'rgba(0,0,0,.25)' }} />}
              placeholder="密码"
            />
          </Form.Item>

          <Form.Item>
            <Button
              type="primary"
              htmlType="submit"
              loading={loading}
              icon={<LoginOutlined />}
              block
              size="large"
            >
              登录
            </Button>
          </Form.Item>
        </Form>

        <div style={{ marginTop: 24, paddingTop: 24, borderTop: '1px solid #f0f0f0' }}>
          <Typography.Text type="secondary" style={{ display: 'block', marginBottom: 16 }}>
            快速登录测试账号：
          </Typography.Text>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
            <Button size="small" onClick={() => quickLogin('admin', 'admin123')}>
              管理员
            </Button>
            <Button size="small" onClick={() => quickLogin('doctor1', 'doctor123')}>
              医生
            </Button>
            <Button size="small" onClick={() => quickLogin('nurse1', 'nurse123')}>
              护士
            </Button>
            <Button size="small" onClick={() => quickLogin('registrar1', 'registrar123')}>
              挂号员
            </Button>
            <Button size="small" onClick={() => quickLogin('patient1', 'patient123')}>
              患者
            </Button>
          </div>
        </div>
      </Card>
    </div>
  );
};

export default Login;
