// src/pages/admin/AdminLayout.tsx
import { NavLink, Outlet } from 'react-router-dom';
import {
  LayoutDashboard,
  Building2,
  FileWarning,
  Shield,
  Bell,
  User,
  Menu,
  X,
} from 'lucide-react';
import { useState } from 'react';
import { cn } from '@/lib/utils';

const menuItems = [
  { path: '/admin/dashboard', label: '数据总览', icon: LayoutDashboard },
  { path: '/admin/schools', label: '院校监控', icon: Building2 },
  { path: '/admin/complaints', label: '投诉处理', icon: FileWarning },
];

export default function AdminLayout() {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <div className="min-h-screen bg-slate-900 flex">
      <aside
        className={cn(
          'fixed inset-y-0 left-0 z-50 w-64 bg-slate-800 border-r border-slate-700 transform transition-transform duration-300 ease-in-out lg:relative lg:translate-x-0',
          sidebarOpen ? 'translate-x-0' : '-translate-x-full'
        )}
      >
        <div className="h-16 px-6 border-b border-slate-700 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center shadow-lg shadow-primary-500/30">
              <Shield className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-base font-bold text-white">教育局监管</h1>
              <p className="text-xs text-slate-400">Admin Dashboard</p>
            </div>
          </div>
          <button
            onClick={() => setSidebarOpen(false)}
            className="lg:hidden p-2 hover:bg-slate-700 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-slate-400" />
          </button>
        </div>

        <nav className="p-4 space-y-1">
          {menuItems.map((item) => (
            <NavLink
              key={item.path}
              to={item.path}
              onClick={() => setSidebarOpen(false)}
              className={({ isActive }) =>
                cn(
                  'flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium transition-all duration-200',
                  isActive
                    ? 'bg-primary-600 text-white shadow-lg shadow-primary-600/30'
                    : 'text-slate-300 hover:bg-slate-700/50 hover:text-white'
                )
              }
            >
              <item.icon className="w-5 h-5" />
              {item.label}
            </NavLink>
          ))}
        </nav>

        <div className="absolute bottom-0 left-0 right-0 p-4 border-t border-slate-700">
          <div className="flex items-center gap-3 p-3 rounded-xl hover:bg-slate-700/50 cursor-pointer transition-colors">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center">
              <User className="w-5 h-5 text-white" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-white truncate">管理员</p>
              <p className="text-xs text-slate-400 truncate">admin@edu.gov.cn</p>
            </div>
          </div>
        </div>
      </aside>

      {sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      <div className="flex-1 flex flex-col min-w-0">
        <header className="h-16 bg-slate-800/80 backdrop-blur-sm border-b border-slate-700 px-4 lg:px-6 flex items-center justify-between sticky top-0 z-30">
          <div className="flex items-center gap-4">
            <button
              onClick={() => setSidebarOpen(true)}
              className="lg:hidden p-2 hover:bg-slate-700 rounded-lg transition-colors"
            >
              <Menu className="w-5 h-5 text-slate-300" />
            </button>
            <h2 className="text-lg font-bold text-white hidden sm:block">
              实习监管平台
            </h2>
          </div>

          <div className="flex items-center gap-3">
            <button className="relative p-2.5 hover:bg-slate-700 rounded-xl transition-colors">
              <Bell className="w-5 h-5 text-slate-300" />
              <span className="absolute top-2 right-2 w-2 h-2 bg-red-500 rounded-full" />
            </button>
            <div className="h-8 w-px bg-slate-700 hidden sm:block" />
            <div className="hidden sm:flex items-center gap-2">
              <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center">
                <User className="w-4 h-4 text-white" />
              </div>
              <span className="text-sm text-slate-300 font-medium">管理员</span>
            </div>
          </div>
        </header>

        <main className="flex-1 p-4 lg:p-6 overflow-auto">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

// src/components/layout/AdminLayout.vue
<template>
  <div class="min-h-screen flex bg-gray-50">
    <aside class="w-64 bg-white border-r border-gray-100 flex flex-col">
      <div class="h-16 flex items-center gap-3 px-5 border-b border-gray-100">
        <div class="w-9 h-9 rounded-lg bg-brand-500 flex items-center justify-center">
          <span class="text-white font-bold">德</span>
        </div>
        <div>
          <div class="text-sm font-bold text-gray-900">大件运营平台</div>
          <div class="text-xs text-gray-500">Deppon Admin</div>
        </div>
      </div>

      <nav class="flex-1 py-4 px-3 space-y-1">
        <router-link
          v-for="item in menuItems"
          :key="item.path"
          :to="item.path"
          class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all duration-200"
          :class="isActive(item.path) ? 'bg-brand-50 text-brand-600' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'"
        >
          <component :is="item.icon" class="w-5 h-5" />
          <span>{{ item.label }}</span>
          <span v-if="item.badge" class="ml-auto px-2 py-0.5 rounded-full text-xs bg-alert-500 text-white">
            {{ item.badge }}
          </span>
        </router-link>
      </nav>

      <div class="p-4 border-t border-gray-100">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-full bg-brand-100 flex items-center justify-center text-brand-600 font-semibold">
            管
          </div>
          <div class="flex-1 min-w-0">
            <div class="text-sm font-medium text-gray-900 truncate">管理员</div>
            <div class="text-xs text-gray-500">运营调度组</div>
          </div>
          <router-link to="/" class="text-gray-400 hover:text-gray-600">
            <component :is="icons.LogOut" class="w-4 h-4" />
          </router-link>
        </div>
      </div>
    </aside>

    <div class="flex-1 flex flex-col min-w-0">
      <header class="h-16 bg-white border-b border-gray-100 flex items-center justify-between px-6">
        <div>
          <h1 class="text-lg font-semibold text-gray-900">{{ pageTitle }}</h1>
          <p class="text-xs text-gray-500">{{ pageSubtitle }}</p>
        </div>
        <div class="flex items-center gap-3">
          <button class="relative p-2 rounded-lg hover:bg-gray-100 text-gray-600">
            <component :is="icons.Bell" class="w-5 h-5" />
            <span class="absolute top-1 right-1 w-2 h-2 rounded-full bg-alert-500"></span>
          </button>
          <button class="p-2 rounded-lg hover:bg-gray-100 text-gray-600">
            <component :is="icons.Settings" class="w-5 h-5" />
          </button>
        </div>
      </header>

      <main class="flex-1 p-6 overflow-auto animate-fade-in">
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import {
  LayoutDashboard, Route, Video, FileText, Truck, Bell, Settings, LogOut
} from 'lucide-vue-next'

const icons = { Bell, Settings, LogOut }
const route = useRoute()

const menuItems = [
  { path: '/admin/dashboard', label: '数据概览', icon: LayoutDashboard },
  { path: '/admin/routing', label: '路由规划引擎', icon: Route },
  { path: '/admin/video-review', label: '装卸视频审核', icon: Video, badge: '3' },
  { path: '/admin/claims', label: '理赔中心', icon: FileText, badge: '1' },
  { path: '/admin/vehicles', label: '车辆监控对接', icon: Truck }
]

const titleMap: Record<string, { title: string; subtitle: string }> = {
  '/admin/dashboard': { title: '数据概览', subtitle: '大件物流运营核心指标实时监控' },
  '/admin/routing': { title: '大件路由规划引擎', subtitle: '智能规避限高限重路段，多方案对比选优' },
  '/admin/video-review': { title: '装卸作业视频审核', subtitle: 'AI智能抽检 + 人工复核' },
  '/admin/claims': { title: '理赔中心', subtitle: 'OCR智能识别 · 结构化录入 · 快速理算' },
  '/admin/vehicles': { title: '车辆监控对接', subtitle: '交通运输部货运车辆动态监控平台' }
}

const pageInfo = computed(() => titleMap[route.path] || { title: '', subtitle: '' })
const pageTitle = computed(() => pageInfo.value.title)
const pageSubtitle = computed(() => pageInfo.value.subtitle)

function isActive(path: string) {
  return route.path === path
}
</script>
