// frontend/src/components/AdminLayout.tsx
import { Outlet, Link, useLocation } from 'react-router-dom'
import { LayoutDashboard, FileText, CheckSquare, Hash, Flame, ShieldAlert, BarChart3, Users } from 'lucide-react'

const menuItems = [
  { path: '/admin', label: '仪表盘', icon: LayoutDashboard, exact: true },
  { path: '/admin/contents', label: '内容管理', icon: FileText },
  { path: '/admin/review', label: '审核管理', icon: CheckSquare },
  { path: '/admin/topics', label: '话题管理', icon: Hash },
  { path: '/admin/hotlist', label: '热门管理', icon: Flame },
  { path: '/admin/sensitive', label: '敏感词管理', icon: ShieldAlert },
  { path: '/admin/analytics', label: '数据分析', icon: BarChart3 },
  { path: '/admin/users', label: '用户管理', icon: Users },
]

export default function AdminLayout() {
  const location = useLocation()

  const isActive = (path: string, exact?: boolean) => {
    if (exact) return location.pathname === path
    return location.pathname.startsWith(path)
  }

  return (
    <div className="min-h-screen flex bg-gray-100">
      <aside className="w-56 bg-white border-r border-gray-200 shrink-0">
        <div className="p-4 border-b border-gray-200">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-primary-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-sm">城</span>
            </div>
            <span className="text-lg font-bold text-gray-900">城事志</span>
          </Link>
          <p className="text-xs text-gray-400 mt-1">管理后台</p>
        </div>
        <nav className="p-3 space-y-1">
          {menuItems.map((item) => {
            const Icon = item.icon
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
                  isActive(item.path, item.exact)
                    ? 'bg-primary-50 text-primary-600'
                    : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                }`}
              >
                <Icon className="w-4 h-4" />
                {item.label}
              </Link>
            )
          })}
        </nav>
      </aside>
      <main className="flex-1 overflow-auto">
        <div className="p-6">
          <Outlet />
        </div>
      </main>
    </div>
  )
}

// src/components/layout/AdminLayout.vue
<template>
  <div class="min-h-screen flex bg-gray-50">
    <aside class="w-64 bg-white border-r border-gray-100 flex flex-col">
      <div class="h-16 flex items-center gap-3 px-5 border-b border-gray-100">
        <div class="w-9 h-9 rounded-lg bg-brand-500 flex items-center justify-center">
          <span class="text-white font-bold">德</span>
        </div>
        <div>
          <div class="text-sm font-bold text-gray-900">大件运营平台</div>
          <div class="text-xs text-gray-500">Deppon Admin</div>
        </div>
      </div>

      <nav class="flex-1 py-4 px-3 space-y-1">
        <router-link
          v-for="item in menuItems"
          :key="item.path"
          :to="item.path"
          class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all duration-200"
          :class="isActive(item.path) ? 'bg-brand-50 text-brand-600' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'"
        >
          <component :is="item.icon" class="w-5 h-5" />
          <span>{{ item.label }}</span>
          <span v-if="item.badge" class="ml-auto px-2 py-0.5 rounded-full text-xs bg-alert-500 text-white">
            {{ item.badge }}
          </span>
        </router-link>
      </nav>

      <div class="p-4 border-t border-gray-100">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-full bg-brand-100 flex items-center justify-center text-brand-600 font-semibold">
            管
          </div>
          <div class="flex-1 min-w-0">
            <div class="text-sm font-medium text-gray-900 truncate">管理员</div>
            <div class="text-xs text-gray-500">运营调度组</div>
          </div>
          <router-link to="/" class="text-gray-400 hover:text-gray-600">
            <component :is="icons.LogOut" class="w-4 h-4" />
          </router-link>
        </div>
      </div>
    </aside>

    <div class="flex-1 flex flex-col min-w-0">
      <header class="h-16 bg-white border-b border-gray-100 flex items-center justify-between px-6">
        <div>
          <h1 class="text-lg font-semibold text-gray-900">{{ pageTitle }}</h1>
          <p class="text-xs text-gray-500">{{ pageSubtitle }}</p>
        </div>
        <div class="flex items-center gap-3">
          <button class="relative p-2 rounded-lg hover:bg-gray-100 text-gray-600">
            <component :is="icons.Bell" class="w-5 h-5" />
            <span class="absolute top-1 right-1 w-2 h-2 rounded-full bg-alert-500"></span>
          </button>
          <button class="p-2 rounded-lg hover:bg-gray-100 text-gray-600">
            <component :is="icons.Settings" class="w-5 h-5" />
          </button>
        </div>
      </header>

      <main class="flex-1 p-6 overflow-auto animate-fade-in">
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import {
  LayoutDashboard, Route, Video, FileText, Truck, Bell, Settings, LogOut
} from 'lucide-vue-next'

const icons = { Bell, Settings, LogOut }
const route = useRoute()

const menuItems = [
  { path: '/admin/dashboard', label: '数据概览', icon: LayoutDashboard },
  { path: '/admin/routing', label: '路由规划引擎', icon: Route },
  { path: '/admin/video-review', label: '装卸视频审核', icon: Video, badge: '3' },
  { path: '/admin/claims', label: '理赔中心', icon: FileText, badge: '1' },
  { path: '/admin/vehicles', label: '车辆监控对接', icon: Truck }
]

const titleMap: Record<string, { title: string; subtitle: string }> = {
  '/admin/dashboard': { title: '数据概览', subtitle: '大件物流运营核心指标实时监控' },
  '/admin/routing': { title: '大件路由规划引擎', subtitle: '智能规避限高限重路段，多方案对比选优' },
  '/admin/video-review': { title: '装卸作业视频审核', subtitle: 'AI智能抽检 + 人工复核' },
  '/admin/claims': { title: '理赔中心', subtitle: 'OCR智能识别 · 结构化录入 · 快速理算' },
  '/admin/vehicles': { title: '车辆监控对接', subtitle: '交通运输部货运车辆动态监控平台' }
}

const pageInfo = computed(() => titleMap[route.path] || { title: '', subtitle: '' })
const pageTitle = computed(() => pageInfo.value.title)
const pageSubtitle = computed(() => pageInfo.value.subtitle)

function isActive(path: string) {
  return route.path === path
}
</script>
