// frontend/src/pages/ProductDetail.jsx
import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { ArrowLeft, ShoppingCart, MessageCircle, Share2, ChevronUp, Star, Heart, Home } from 'lucide-react'
import useStore from '../store/useStore'
import api from '../utils/api'
import { showToast } from '../utils/toast'

function ProductDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [product, setProduct] = useState(null)
  const [reviews, setReviews] = useState([])
  const [relatedProducts, setRelatedProducts] = useState([])
  const [activeTab, setActiveTab] = useState('product')
  const [showScrollTop, setShowScrollTop] = useState(false)
  const [showSpecModal, setShowSpecModal] = useState(false)
  const [quantity, setQuantity] = useState(1)
  const [actionType, setActionType] = useState(null)
  const [liked, setLiked] = useState(false)
  const reviewsRef = useRef(null)
  const detailRef = useRef(null)
  const pageRef = useRef(null)
  
  const addToCart = useStore((state) => state.addToCart)
  const cartCount = useStore((state) => state.cartCount)
  
  useEffect(() => {
    fetchProduct()
    handleScroll()
  }, [id])
  
  const fetchProduct = async () => {
    try {
      const response = await api.get(`/product/${id}`)
      setProduct(response.product)
      setReviews(response.reviews || [])
      setRelatedProducts(response.relatedProducts || [])
    } catch (error) {
      console.error('Failed to fetch product:', error)
    }
  }
  
  const handleScroll = () => {
    const handleScrollEvent = () => {
      const scrollTop = pageRef.current?.scrollTop || window.scrollY
      setShowScrollTop(scrollTop > 300)
    }
    
    window.addEventListener('scroll', handleScrollEvent)
    return () => window.removeEventListener('scroll', handleScrollEvent)
  }
  
  const scrollToReviews = () => {
    setActiveTab('reviews')
    reviewsRef.current?.scrollIntoView({ behavior: 'smooth' })
  }
  
  const scrollToDetail = () => {
    setActiveTab('detail')
    detailRef.current?.scrollIntoView({ behavior: 'smooth' })
  }
  
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }
  
  const handleAction = (type) => {
    setActionType(type)
    setShowSpecModal(true)
  }
  
  const confirmAction = async () => {
    if (!product) return
    
    if (actionType === 'cart') {
      try {
        await addToCart(product.id, null, quantity)
        showToast('已加入购物车')
        setShowSpecModal(false)
      } catch (error) {
        showToast('加入购物车失败')
      }
    } else if (actionType === 'buy') {
      localStorage.setItem('checkoutData', JSON.stringify({
        items: [{
          product_id: product.id,
          product,
          quantity,
          price: product.price
        }]
      }))
      navigate('/checkout')
    }
  }
  
  const buyNow = async () => {
    if (!product) return
    
    try {
      const response = await api.post('/order/create', {
        product_id: product.id,
        quantity: 1,
        address: { name: '测试用户', phone: '13800000000', address: '测试地址' }
      })
      
      if (response.order?.id) {
        await api.post(`/order/${response.order.id}/pay`)
        showToast('下单成功')
        navigate(`/order/${response.order.id}`)
      }
    } catch (error) {
      showToast(error.response?.data?.error || '下单失败')
    }
  }
  
  if (!product) {
    return <div className="loading">加载中...</div>
  }
  
  return (
    <div ref={pageRef} className="product-detail-page">
      <div className="header">
        <div className="back-btn" onClick={() => navigate(-1)}>
          <ArrowLeft size={22} />
        </div>
        <div className="header-title">商品详情</div>
        <div className="back-btn" onClick={() => navigate('/')}>
          <Home size={22} />
        </div>
      </div>
      
      <div className="detail-images">
        <img
          src={product.images?.[0] || 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=product%20placeholder&image_size=square_hd'}
          alt={product.name}
        />
      </div>
      
      <div className="detail-info">
        <div className="detail-price">
          <span className="price-current">¥{product.price?.toFixed(2)}</span>
          {product.original_price && (
            <span className="price-original">¥{product.original_price?.toFixed(2)}</span>
          )}
        </div>
        <div className="detail-name">{product.name}</div>
        <div className="detail-desc">{product.description}</div>
        <div className="detail-stats">
          <span>销量 {product.sales}</span>
          <span>库存 {product.stock}</span>
          <span onClick={scrollToReviews} style={{ cursor: 'pointer' }}>评价 {reviews.length}</span>
        </div>
      </div>
      
      <div className="detail-tabs">
        <div
          className={`detail-tab ${activeTab === 'product' ? 'active' : ''}`}
          onClick={() => setActiveTab('product')}
        >
          商品
        </div>
        <div
          className={`detail-tab ${activeTab === 'reviews' ? 'active' : ''}`}
          onClick={scrollToReviews}
        >
          评价({reviews.length})
        </div>
        <div
          className={`detail-tab ${activeTab === 'detail' ? 'active' : ''}`}
          onClick={scrollToDetail}
        >
          详情
        </div>
      </div>
      
      <div ref={reviewsRef} className="review-section">
        <h4 style={{ fontSize: 15, fontWeight: 600, marginBottom: 12 }}>用户评价</h4>
        {reviews.length === 0 ? (
          <p style={{ color: '#999', textAlign: 'center', padding: 20 }}>暂无评价</p>
        ) : (
          reviews.map((review) => (
            <div key={review.id} className="review-item">
              <div className="review-user">
                <img
                  src={review.avatar || 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=avatar&image_size=square'}
                  alt={review.nickname}
                />
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span>{review.nickname}</span>
                    <div className="review-stars">
                      {Array(review.rating).fill('★').join('')}
                    </div>
                  </div>
                </div>
              </div>
              <div className="review-content">{review.content}</div>
            </div>
          ))
        )}
      </div>
      
      {relatedProducts.length > 0 && (
        <div style={{ backgroundColor: '#fff', marginBottom: 8 }}>
          <div className="section-title">
            <h3>相关推荐</h3>
          </div>
          <div className="product-grid" style={{ padding: '0 8px 16px' }}>
            {relatedProducts.map((product) => (
              <div
                key={product.id}
                className="product-card"
                onClick={() => {
                  setProduct(null)
                  navigate(`/product/${product.id}`, { replace: true })
                }}
              >
                <img
                  src={product.images?.[0] || 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=product%20placeholder&image_size=square_hd'}
                  alt={product.name}
                />
                <div className="product-info">
                  <div className="product-name">{product.name}</div>
                  <div className="product-price">
                    <span className="price-current">¥{product.price?.toFixed(2)}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
      
      <div ref={detailRef} style={{ backgroundColor: '#fff', padding: 16 }}>
        <h4 style={{ fontSize: 15, fontWeight: 600, marginBottom: 12 }}>图文详情</h4>
        {product.detail_images?.map((img, idx) => (
          <img
            key={idx}
            src={img}
            alt={`detail-${idx}`}
            style={{ width: '100%', marginBottom: 8 }}
          />
        ))}
      </div>
      
      <div className="detail-bottom">
        <div className="detail-action-icons">
          <div className="action-icon" onClick={() => navigate('/')}>
            <Home size={22} color="#666" />
            <span>首页</span>
          </div>
          <div className="action-icon" onClick={() => setLiked(!liked)}>
            <Heart size={22} color={liked ? '#ff4d4f' : '#666'} fill={liked ? '#ff4d4f' : 'none'} />
            <span>收藏</span>
          </div>
          <div className="action-icon" onClick={() => navigate('/cart')}>
            <div style={{ position: 'relative' }}>
              <ShoppingCart size={22} color="#666" />
              {cartCount > 0 && (
                <span className="nav-badge" style={{ top: -8, right: -8 }}>
                  {cartCount > 99 ? '99+' : cartCount}
                </span>
              )}
            </div>
            <span>购物车</span>
          </div>
          <div className="action-icon">
            <MessageCircle size={22} color="#666" />
            <span>客服</span>
          </div>
        </div>
        <div className="detail-action-btns">
          <button className="btn-cart" onClick={() => handleAction('cart')}>加入购物车</button>
          <button className="btn-buy" onClick={buyNow}>立即购买</button>
        </div>
      </div>
      
      {showScrollTop && (
        <div className="scroll-top-btn visible" onClick={scrollToTop}>
          <ChevronUp size={24} color="#999" />
        </div>
      )}
      
      {showSpecModal && (
        <div className="modal-overlay" onClick={() => setShowSpecModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>确认</h3>
              <button onClick={() => setShowSpecModal(false)}>✕</button>
            </div>
            <div className="modal-body">
              <div style={{ display: 'flex', gap: 12, marginBottom: 20 }}>
                <img
                  src={product.images?.[0]}
                  alt={product.name}
                  style={{ width: 80, height: 80, borderRadius: 8 }}
                />
                <div>
                  <p style={{ fontWeight: 600 }}>{product.name}</p>
                  <p style={{ color: '#ff4d4f', fontSize: 18, fontWeight: 700, marginTop: 8 }}>
                    ¥{product.price?.toFixed(2)}
                  </p>
                </div>
              </div>
              
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span>数量</span>
                <div className="quantity-control">
                  <button
                    className="quantity-btn"
                    onClick={() => setQuantity(Math.max(1, quantity - 1))}
                  >
                    -
                  </button>
                  <span className="quantity-input">{quantity}</span>
                  <button
                    className="quantity-btn"
                    onClick={() => setQuantity(Math.min(product.stock || 99, quantity + 1))}
                  >
                    +
                  </button>
                </div>
              </div>
            </div>
            <div style={{ padding: 16, borderTop: '1px solid #f0f0f0' }}>
              <button
                className="btn-primary"
                style={{ width: '100%', height: 44, borderRadius: 22, fontSize: 15 }}
                onClick={confirmAction}
              >
                {actionType === 'cart' ? '加入购物车' : '立即购买'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default ProductDetail

// client/src/views/ProductDetail.vue
<template>
  <div class="product-detail" v-if="product">
    <div class="back-header">
      <span class="back-btn" @click="goBack">←</span>
      <span class="title">商品详情</span>
      <span class="share-btn">分享</span>
    </div>

    <div class="scroll-content">
      <div class="product-gallery">
        <img :src="product.cover_image" :alt="product.title" />
      </div>

      <div class="product-info card">
        <div class="price-row">
          <span class="price">¥{{ product.price }}</span>
          <span v-if="product.original_price" class="price-old">¥{{ product.original_price }}</span>
        </div>
        <h1 class="product-title">{{ product.title }}</h1>
        <div class="product-meta">
          <span>销量 {{ product.sales }}</span>
          <span>库存 {{ product.stock }}</span>
        </div>
      </div>

      <div class="shop-info card">
        <div class="shop-header">
          <div class="shop-avatar">🏪</div>
          <div class="shop-detail">
            <div class="shop-name">{{ product.shop_name }}</div>
            <div class="shop-desc">官方认证 · 品质保障</div>
          </div>
          <button class="btn btn-outline" @click="goChat">联系客服</button>
        </div>
      </div>

      <div class="tab-nav">
        <div 
          class="tab-item" 
          :class="{ active: activeTab === 'detail' }"
          @click="activeTab = 'detail'"
        >商品</div>
        <div 
          class="tab-item" 
          :class="{ active: activeTab === 'comments' }"
          @click="activeTab = 'comments'"
        >评价 ({{ comments.length }})</div>
        <div 
          class="tab-item" 
          :class="{ active: activeTab === 'recommend' }"
          @click="activeTab = 'recommend'"
        >推荐</div>
      </div>

      <div v-if="activeTab === 'detail'" class="tab-content">
        <div class="detail-desc card">
          <h3>商品详情</h3>
          <p>{{ product.description }}</p>
          <div v-if="product.images" class="detail-images">
            <img v-for="(img, idx) in productImages" :key="idx" :src="img" />
          </div>
        </div>
      </div>

      <div v-if="activeTab === 'comments'" class="tab-content">
        <div v-if="comments.length > 0" class="comments-list">
          <div v-for="comment in comments" :key="comment.id" class="comment-item card">
            <div class="comment-header">
              <img :src="comment.avatar" class="avatar" />
              <div class="user-info">
                <div class="nickname">{{ comment.nickname }}</div>
                <div class="rating">
                  <span v-for="i in 5" :key="i">⭐</span>
                </div>
              </div>
            </div>
            <div class="comment-content">{{ comment.content }}</div>
            <div class="comment-time">{{ formatTime(comment.created_at) }}</div>
          </div>
        </div>
        <div v-else class="empty-state">
          <div class="icon">💬</div>
          <div>暂无评价</div>
        </div>
      </div>

      <div v-if="activeTab === 'recommend'" class="tab-content">
        <div class="product-grid">
          <ProductCard 
            v-for="item in relatedProducts" 
            :key="item.id" 
            :product="item"
            @click="goDetail(item.id)"
          />
        </div>
      </div>
    </div>

    <div class="bottom-bar safe-area-bottom">
      <div class="action-left">
        <div class="action-item" @click="goHome">
          <span>🏠</span>
          <span>首页</span>
        </div>
        <div class="action-item" @click="toggleFavorite">
          <span>{{ product.isFavorite ? '❤️' : '🤍' }}</span>
          <span>收藏</span>
        </div>
        <div class="action-item" @click="goCart">
          <span>🛒</span>
          <span>购物车</span>
        </div>
      </div>
      <div class="action-right">
        <button class="btn-cart" @click="addToCart">加入购物车</button>
        <button class="btn-buy" @click="buyNow">立即购买</button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, inject } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { productApi, orderApi } from '../api';
import { useUserStore } from '../stores/user';
import ProductCard from '../components/ProductCard.vue';

const route = useRoute();
const router = useRouter();
const userStore = useUserStore();
const showToast = inject('showToast');

const product = ref(null);
const comments = ref([]);
const relatedProducts = ref([]);
const activeTab = ref('detail');

const productImages = computed(() => {
  if (!product.value?.images) return [];
  return product.value.images.split(',').map(s => s.trim()).filter(Boolean);
});

const fetchProductDetail = async () => {
  try {
    const res = await productApi.getDetail(route.params.id);
    if (res.code === 200) {
      product.value = res.data;
      comments.value = res.data.comments || [];
      relatedProducts.value = res.data.relatedProducts || [];
    }
  } catch (e) {
    console.error(e);
  }
};

const goBack = () => {
  router.back();
};

const goHome = () => {
  router.push('/');
};

const goCart = () => {
  router.push('/cart');
};

const goChat = () => {
  if (!userStore.isLoggedIn) {
    router.push('/login?redirect=' + encodeURIComponent(route.fullPath));
    return;
  }
  router.push(`/chat/${product.value?.shop_id || 1}`);
};

const goDetail = (id) => {
  if (id === parseInt(route.params.id)) return;
  router.push(`/product/${id}`);
  product.value = null;
  fetchProductDetail();
};

const toggleFavorite = async () => {
  if (!userStore.isLoggedIn) {
    router.push('/login?redirect=' + encodeURIComponent(route.fullPath));
    return;
  }
  
  try {
    const res = await productApi.toggleFavorite(route.params.id);
    if (res.code === 200) {
      product.value.isFavorite = res.data.isFavorite;
      showToast(res.data.isFavorite ? '收藏成功' : '已取消收藏');
    }
  } catch (e) {
    console.error(e);
  }
};

const addToCart = async () => {
  if (!userStore.isLoggedIn) {
    router.push('/login?redirect=' + encodeURIComponent(route.fullPath));
    return;
  }
  
  try {
    const res = await orderApi.addToCart({
      productId: product.value.id,
      quantity: 1
    });
    if (res.code === 200) {
      showToast('已加入购物车');
    }
  } catch (e) {
    console.error(e);
    showToast(e.response?.data?.message || '添加失败');
  }
};

const buyNow = async () => {
  if (!userStore.isLoggedIn) {
    router.push('/login?redirect=' + encodeURIComponent(route.fullPath));
    return;
  }
  
  try {
    const res = await orderApi.createOrder({
      items: [{ productId: product.value.id, quantity: 1 }],
      address: '北京市朝阳区xxx路xxx号',
      phone: '13800138000',
      receiver: '收货人'
    });
    if (res.code === 200) {
      showToast('下单成功');
      router.push(`/order/${res.data.orderId}`);
    }
  } catch (e) {
    console.error(e);
    showToast(e.response?.data?.message || '下单失败');
  }
};

const formatTime = (time) => {
  if (!time) return '';
  const date = new Date(time);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
};

onMounted(() => {
  fetchProductDetail();
});
</script>

<style scoped>
.product-detail {
  min-height: 100vh;
  background: #f5f5f5;
  padding-bottom: 60px;
}

.back-header {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: 44px;
  background: rgba(255, 255, 255, 0.95);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 16px;
  z-index: 100;
  border-bottom: 1px solid #eee;
}

.back-btn {
  font-size: 20px;
  color: #333;
}

.title {
  font-size: 16px;
  font-weight: bold;
}

.share-btn {
  font-size: 14px;
  color: #666;
}

.scroll-content {
  padding-top: 44px;
}

.product-gallery {
  width: 100%;
  background: #fff;
}

.product-gallery img {
  width: 100%;
  aspect-ratio: 1;
  object-fit: cover;
}

.product-info {
  padding: 16px;
  margin-bottom: 12px;
}

.price-row {
  display: flex;
  align-items: baseline;
  gap: 10px;
  margin-bottom: 10px;
}

.price {
  font-size: 24px;
  color: #ff4d4f;
  font-weight: bold;
}

.price-old {
  font-size: 14px;
  color: #999;
  text-decoration: line-through;
}

.product-title {
  font-size: 16px;
  font-weight: 500;
  color: #333;
  line-height: 1.5;
  margin-bottom: 10px;
}

.product-meta {
  display: flex;
  gap: 20px;
  font-size: 12px;
  color: #999;
}

.shop-info {
  padding: 16px;
  margin-bottom: 12px;
}

.shop-header {
  display: flex;
  align-items: center;
  gap: 12px;
}

.shop-avatar {
  width: 48px;
  height: 48px;
  background: #f5f5f5;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24px;
}

.shop-detail {
  flex: 1;
}

.shop-name {
  font-size: 14px;
  font-weight: 500;
  color: #333;
}

.shop-desc {
  font-size: 12px;
  color: #999;
  margin-top: 4px;
}

.tab-nav {
  display: flex;
  background: #fff;
  border-bottom: 1px solid #eee;
  position: sticky;
  top: 44px;
  z-index: 99;
}

.tab-item {
  flex: 1;
  text-align: center;
  padding: 12px 0;
  font-size: 14px;
  color: #666;
  position: relative;
}

.tab-item.active {
  color: #ff5000;
  font-weight: 500;
}

.tab-item.active::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  width: 40px;
  height: 2px;
  background: #ff5000;
}

.tab-content {
  padding: 12px;
}

.detail-desc {
  padding: 16px;
}

.detail-desc h3 {
  font-size: 14px;
  font-weight: 500;
  margin-bottom: 12px;
  color: #333;
}

.detail-desc p {
  font-size: 14px;
  color: #666;
  line-height: 1.8;
}

.detail-images {
  margin-top: 16px;
}

.detail-images img {
  width: 100%;
  margin-bottom: 12px;
  border-radius: 8px;
}

.comments-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.comment-item {
  padding: 16px;
}

.comment-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 12px;
}

.avatar {
  width: 36px;
  height: 36px;
  border-radius: 50%;
}

.user-info {
  flex: 1;
}

.nickname {
  font-size: 14px;
  color: #333;
}

.rating {
  font-size: 12px;
  margin-top: 2px;
}

.comment-content {
  font-size: 14px;
  color: #333;
  line-height: 1.6;
}

.comment-time {
  font-size: 12px;
  color: #999;
  margin-top: 8px;
}

.product-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 12px;
}

.empty-state {
  text-align: center;
  padding: 60px 20px;
  color: #999;
}

.empty-state .icon {
  font-size: 48px;
  margin-bottom: 12px;
}

.bottom-bar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #fff;
  display: flex;
  align-items: center;
  padding: 8px 12px;
  border-top: 1px solid #eee;
  z-index: 100;
}

.action-left {
  display: flex;
  gap: 20px;
  margin-right: 16px;
}

.action-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  font-size: 10px;
  color: #666;
}

.action-item span:first-child {
  font-size: 20px;
  margin-bottom: 2px;
}

.action-right {
  flex: 1;
  display: flex;
  gap: 10px;
}

.btn-cart, .btn-buy {
  flex: 1;
  height: 40px;
  border: none;
  border-radius: 20px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
}

.btn-cart {
  background: #ffe8d9;
  color: #ff5000;
}

.btn-buy {
  background: linear-gradient(to right, #ff5000, #ff6b00);
  color: #fff;
}
</style>
