// client/src/views/Register.vue
<template>
  <div class="container" style="max-width: 400px; padding-top: 60px;">
    <div class="card" style="padding: 32px;">
      <h2 style="text-align: center; margin-bottom: 32px; font-size: 24px; font-weight: 700;">注册</h2>
      <form @submit.prevent="handleRegister">
        <div class="form-group">
          <label class="form-label">用户名</label>
          <input
            v-model="form.username"
            type="text"
            class="form-input"
            placeholder="请输入用户名（3-20个字符）"
            required
          />
        </div>
        <div class="form-group">
          <label class="form-label">昵称</label>
          <input
            v-model="form.nickname"
            type="text"
            class="form-input"
            placeholder="请输入昵称（可选）"
          />
        </div>
        <div class="form-group">
          <label class="form-label">密码</label>
          <input
            v-model="form.password"
            type="password"
            class="form-input"
            placeholder="请输入密码（6-32个字符）"
            required
          />
        </div>
        <div class="form-group">
          <label class="form-label">确认密码</label>
          <input
            v-model="form.confirmPassword"
            type="password"
            class="form-input"
            placeholder="请再次输入密码"
            required
          />
        </div>
        <div style="margin-bottom: 16px; text-align: center; color: #999; font-size: 14px;">
          已有账号？
          <router-link to="/login" style="color: #667eea; text-decoration: none;">立即登录</router-link>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 100%;" :disabled="loading">
          {{ loading ? '注册中...' : '注册' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useUserStore } from '@/stores/user';

const router = useRouter();
const userStore = useUserStore();

const form = ref({
  username: '',
  nickname: '',
  password: '',
  confirmPassword: '',
});
const loading = ref(false);

const handleRegister = async () => {
  if (!form.value.username || !form.value.password) {
    alert('请填写用户名和密码');
    return;
  }

  if (form.value.password !== form.value.confirmPassword) {
    alert('两次密码输入不一致');
    return;
  }

  if (form.value.username.length < 3 || form.value.username.length > 20) {
    alert('用户名长度应为3-20个字符');
    return;
  }

  if (form.value.password.length < 6 || form.value.password.length > 32) {
    alert('密码长度应为6-32个字符');
    return;
  }

  loading.value = true;
  try {
    await userStore.register(
      form.value.username,
      form.value.password,
      form.value.nickname || undefined
    );
    alert('注册成功，请登录');
    router.push('/login');
  } catch (error: any) {
    alert(error.response?.data?.message || '注册失败');
  } finally {
    loading.value = false;
  }
};
</script>

// src/pages/Register.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Tv } from 'lucide-react'
import { useAuthStore } from '@/store/auth'

export default function Register() {
  const navigate = useNavigate()
  const { register } = useAuthStore()
  const [username, setUsername] = useState('')
  const [phone, setPhone] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')

    if (username.length < 3) {
      setError('用户名至少3个字符')
      return
    }
    if (password.length < 6) {
      setError('密码至少6个字符')
      return
    }
    if (password !== confirmPassword) {
      setError('两次密码不一致')
      return
    }

    setLoading(true)
    try {
      await register(username, password, phone || undefined)
      navigate('/login', { state: { registered: true } })
    } catch (err: any) {
      setError(err.message || '注册失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center px-4">
      <div className="bg-white rounded-lg shadow-md w-full max-w-md p-8">
        <div className="flex flex-col items-center mb-8">
          <Tv className="w-12 h-12 text-red-600 mb-2" />
          <h1 className="text-2xl font-bold text-gray-800">注册账号</h1>
        </div>

        {error && (
          <div className="bg-red-50 text-red-600 px-4 py-2 rounded mb-4 text-sm">{error}</div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              minLength={3}
              className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-red-500"
              placeholder="请输入用户名（至少3个字符）"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">手机号（选填）</label>
            <input
              type="tel"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-red-500"
              placeholder="请输入手机号"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              minLength={6}
              className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-red-500"
              placeholder="请输入密码（至少6个字符）"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">确认密码</label>
            <input
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              required
              className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-red-500"
              placeholder="请再次输入密码"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-red-600 hover:bg-red-700 text-white font-medium py-2 rounded-md transition-colors disabled:opacity-50"
          >
            {loading ? '注册中...' : '注册'}
          </button>
        </form>

        <p className="mt-4 text-center text-sm text-gray-500">
          已有账号？
          <Link to="/login" className="text-red-600 hover:text-red-700 ml-1">去登录</Link>
        </p>
      </div>
    </div>
  )
}
