// frontend/src/pages/ApplicationDetail.jsx
import React, { useState, useEffect } from 'react';
import { apiService } from '../api.js';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Plus } from 'lucide-react';

function ApplicationDetail() {
  const { id } = useParams();
  const [app, setApp] = useState(null);
  const [users, setUsers] = useState([]);
  const [activeTab, setActiveTab] = useState('basic');
  const [envModal, setEnvModal] = useState(false);
  const [verModal, setVerModal] = useState(false);
  const [secModal, setSecModal] = useState(false);
  const [envForm, setEnvForm] = useState({ env_name: '', env_type: 'dev', server_address: '' });
  const [verForm, setVerForm] = useState({ version_number: '', release_notes: '', env_id: '' });
  const [secForm, setSecForm] = useState({ secret_name: '', secret_type: 'password', secret_value: '', valid_from: '', valid_until: '' });

  useEffect(() => {
    loadData();
  }, [id]);

  const loadData = async () => {
    try {
      const [appRes, usersRes] = await Promise.all([
        apiService.getApplication(id),
        apiService.getUsers()
      ]);
      setApp(appRes.data);
      setUsers(usersRes.data);
    } catch (err) {
      console.error('Failed to load:', err);
    }
  };

  const handleEnvSubmit = async (e) => {
    e.preventDefault();
    try {
      await apiService.createEnvironment({ ...envForm, app_id: id });
      setEnvModal(false);
      setEnvForm({ env_name: '', env_type: 'dev', server_address: '' });
      loadData();
    } catch (err) {
      alert('创建失败');
    }
  };

  const handleVerSubmit = async (e) => {
    e.preventDefault();
    try {
      await apiService.createVersion({ ...verForm, app_id: id });
      setVerModal(false);
      setVerForm({ version_number: '', release_notes: '', env_id: '' });
      loadData();
    } catch (err) {
      alert('创建失败');
    }
  };

  const handleSecSubmit = async (e) => {
    e.preventDefault();
    try {
      await apiService.createSecret({ ...secForm, app_id: id });
      setSecModal(false);
      setSecForm({ secret_name: '', secret_type: 'password', secret_value: '', valid_from: '', valid_until: '' });
      loadData();
    } catch (err) {
      alert('创建失败');
    }
  };

  if (!app) return <div>加载中...</div>;

  return (
    <div>
      <div className="page-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <Link to="/applications" className="link-text">
            <ArrowLeft size={20} />
          </Link>
          <h1 className="page-title">{app.app_name} <code>({app.app_code})</code></h1>
        </div>
      </div>

      <div className="tabs">
        <button className={`tab ${activeTab === 'basic' ? 'active' : ''}`} onClick={() => setActiveTab('basic')}>基本信息</button>
        <button className={`tab ${activeTab === 'envs' ? 'active' : ''}`} onClick={() => setActiveTab('envs')}>环境配置</button>
        <button className={`tab ${activeTab === 'versions' ? 'active' : ''}`} onClick={() => setActiveTab('versions')}>版本管理</button>
        <button className={`tab ${activeTab === 'secrets' ? 'active' : ''}`} onClick={() => setActiveTab('secrets')}>密钥管理</button>
      </div>

      {activeTab === 'basic' && (
        <div className="card">
          <div className="detail-grid">
            <div className="detail-item">
              <span className="label">应用编码</span>
              <span className="value">{app.app_code}</span>
            </div>
            <div className="detail-item">
              <span className="label">应用名称</span>
              <span className="value">{app.app_name}</span>
            </div>
            <div className="detail-item">
              <span className="label">分类</span>
              <span className="value">{app.category}</span>
            </div>
            <div className="detail-item">
              <span className="label">负责人</span>
              <span className="value">{app.owner_name || '-'}</span>
            </div>
            <div className="detail-item">
              <span className="label">技术栈</span>
              <span className="value">{app.tech_stack || '-'}</span>
            </div>
            <div className="detail-item">
              <span className="label">状态</span>
              <span className="value">
                <span className={`badge badge-${app.status === 'active' ? 'active' : 'inactive'}`}>
                  {app.status === 'active' ? '启用' : '停用'}
                </span>
              </span>
            </div>
            <div className="detail-item" style={{ gridColumn: '1 / -1' }}>
              <span className="label">描述</span>
              <span className="value">{app.description || '-'}</span>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'envs' && (
        <div className="card">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '16px' }}>
            <h3>环境列表</h3>
            <button className="btn btn-primary btn-sm" onClick={() => setEnvModal(true)}>
              <Plus size={14} /> 添加环境
            </button>
          </div>
          <div className="table-container">
            <table>
              <thead>
                <tr>
                  <th>环境名称</th>
                  <th>环境类型</th>
                  <th>服务器地址</th>
                  <th>状态</th>
                  <th>创建时间</th>
                </tr>
              </thead>
              <tbody>
                {app.environments?.map(env => (
                  <tr key={env.id}>
                    <td>{env.env_name}</td>
                    <td>{env.env_type}</td>
                    <td>{env.server_address || '-'}</td>
                    <td><span className={`badge badge-${env.status === 'active' ? 'active' : 'inactive'}`}>{env.status === 'active' ? '启用' : '停用'}</span></td>
                    <td>{new Date(env.created_at).toLocaleString()}</td>
                  </tr>
                ))}
                {(!app.environments || app.environments.length === 0) && (
                  <tr><td colSpan="5" className="empty-state">暂无环境配置</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {activeTab === 'versions' && (
        <div className="card">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '16px' }}>
            <h3>版本列表</h3>
            <button className="btn btn-primary btn-sm" onClick={() => setVerModal(true)}>
              <Plus size={14} /> 添加版本
            </button>
          </div>
          <div className="table-container">
            <table>
              <thead>
                <tr>
                  <th>版本号</th>
                  <th>发布说明</th>
                  <th>状态</th>
                  <th>创建时间</th>
                </tr>
              </thead>
              <tbody>
                {app.versions?.map(v => (
                  <tr key={v.id}>
                    <td><code>{v.version_number}</code></td>
                    <td>{v.release_notes || '-'}</td>
                    <td><span className="badge badge-draft">{v.status}</span></td>
                    <td>{new Date(v.created_at).toLocaleString()}</td>
                  </tr>
                ))}
                {(!app.versions || app.versions.length === 0) && (
                  <tr><td colSpan="4" className="empty-state">暂无版本记录</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {activeTab === 'secrets' && (
        <div className="card">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '16px' }}>
            <h3>密钥列表</h3>
            <button className="btn btn-primary btn-sm" onClick={() => setSecModal(true)}>
              <Plus size={14} /> 添加密钥
            </button>
          </div>
          <div className="table-container">
            <table>
              <thead>
                <tr>
                  <th>密钥名称</th>
                  <th>类型</th>
                  <th>有效期</th>
                  <th>状态</th>
                  <th>创建时间</th>
                </tr>
              </thead>
              <tbody>
                {app.secrets?.map(s => (
                  <tr key={s.id}>
                    <td>{s.secret_name}</td>
                    <td>{s.secret_type}</td>
                    <td>{s.valid_from || '-'} ~ {s.valid_until || '-'}</td>
                    <td><span className={`badge badge-${s.status === 'active' ? 'active' : 'inactive'}`}>{s.status === 'active' ? '有效' : '失效'}</span></td>
                    <td>{new Date(s.created_at).toLocaleString()}</td>
                  </tr>
                ))}
                {(!app.secrets || app.secrets.length === 0) && (
                  <tr><td colSpan="5" className="empty-state">暂无密钥配置</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {envModal && (
        <div className="modal-overlay" onClick={() => setEnvModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2>添加环境</h2>
              <button className="modal-close" onClick={() => setEnvModal(false)}>&times;</button>
            </div>
            <form onSubmit={handleEnvSubmit}>
              <div className="modal-body">
                <div className="form-group">
                  <label>环境名称 *</label>
                  <input required value={envForm.env_name} onChange={e => setEnvForm({...envForm, env_name: e.target.value})} placeholder="如：生产环境" />
                </div>
                <div className="form-row">
                  <div className="form-group">
                    <label>环境类型</label>
                    <select value={envForm.env_type} onChange={e => setEnvForm({...envForm, env_type: e.target.value})}>
                      <option value="dev">开发</option>
                      <option value="test">测试</option>
                      <option value="staging">预发布</option>
                      <option value="prod">生产</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label>服务器地址</label>
                    <input value={envForm.server_address} onChange={e => setEnvForm({...envForm, server_address: e.target.value})} />
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setEnvModal(false)}>取消</button>
                <button type="submit" className="btn btn-primary">创建</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {verModal && (
        <div className="modal-overlay" onClick={() => setVerModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2>添加版本</h2>
              <button className="modal-close" onClick={() => setVerModal(false)}>&times;</button>
            </div>
            <form onSubmit={handleVerSubmit}>
              <div className="modal-body">
                <div className="form-group">
                  <label>版本号 *</label>
                  <input required value={verForm.version_number} onChange={e => setVerForm({...verForm, version_number: e.target.value})} placeholder="如：v1.0.0" />
                </div>
                <div className="form-group">
                  <label>发布说明</label>
                  <textarea rows="3" value={verForm.release_notes} onChange={e => setVerForm({...verForm, release_notes: e.target.value})} />
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setVerModal(false)}>取消</button>
                <button type="submit" className="btn btn-primary">创建</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {secModal && (
        <div className="modal-overlay" onClick={() => setSecModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2>添加密钥</h2>
              <button className="modal-close" onClick={() => setSecModal(false)}>&times;</button>
            </div>
            <form onSubmit={handleSecSubmit}>
              <div className="modal-body">
                <div className="form-row">
                  <div className="form-group">
                    <label>密钥名称 *</label>
                    <input required value={secForm.secret_name} onChange={e => setSecForm({...secForm, secret_name: e.target.value})} />
                  </div>
                  <div className="form-group">
                    <label>密钥类型</label>
                    <select value={secForm.secret_type} onChange={e => setSecForm({...secForm, secret_type: e.target.value})}>
                      <option value="password">密码</option>
                      <option value="api_key">API Key</option>
                      <option value="token">Token</option>
                      <option value="certificate">证书</option>
                    </select>
                  </div>
                </div>
                <div className="form-group">
                  <label>密钥值 *</label>
                  <input type="password" required value={secForm.secret_value} onChange={e => setSecForm({...secForm, secret_value: e.target.value})} />
                </div>
                <div className="form-row">
                  <div className="form-group">
                    <label>生效时间</label>
                    <input type="datetime-local" value={secForm.valid_from} onChange={e => setSecForm({...secForm, valid_from: e.target.value})} />
                  </div>
                  <div className="form-group">
                    <label>失效时间</label>
                    <input type="datetime-local" value={secForm.valid_until} onChange={e => setSecForm({...secForm, valid_until: e.target.value})} />
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setSecModal(false)}>取消</button>
                <button type="submit" className="btn btn-primary">创建</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default ApplicationDetail;

// frontend/src/pages/ApplicationDetail.vue
<template>
  <div v-loading="loading">
    <el-page-header @back="$router.back()" :content="app?.name || '应用详情'" style="margin-bottom: 20px" />
    
    <el-card v-if="app">
      <template #header>
        <div style="display: flex; justify-content: space-between; align-items: center">
          <span style="font-weight: bold">基本信息</span>
          <el-button type="primary" size="small" @click="activeTab = 'env'; openEnvDialog()">
            <el-icon><Plus /></el-icon>添加环境
          </el-button>
        </div>
      </template>
      <el-descriptions :column="3" border>
        <el-descriptions-item label="应用ID">{{ app.app_id }}</el-descriptions-item>
        <el-descriptions-item label="应用名称">{{ app.name }}</el-descriptions-item>
        <el-descriptions-item label="应用类型">{{ getTypeText(app.type) }}</el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag :type="getStatusType(app.status)">{{ getStatusText(app.status) }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="负责人">{{ app.owner_name || '-' }}</el-descriptions-item>
        <el-descriptions-item label="创建人">{{ app.creator_name || '-' }}</el-descriptions-item>
        <el-descriptions-item label="描述" :span="3">{{ app.description || '-' }}</el-descriptions-item>
      </el-descriptions>
    </el-card>

    <el-card style="margin-top: 20px">
      <el-tabs v-model="activeTab">
        <el-tab-pane label="环境配置" name="env">
          <el-table :data="app?.environments || []" size="small">
            <el-table-column prop="name" label="环境名称" width="120" />
            <el-table-column prop="type" label="类型" width="100">
              <template #default="{ row }">
                <el-tag size="small">{{ row.type }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="base_url" label="基础地址" show-overflow-tooltip />
            <el-table-column prop="status" label="状态" width="80">
              <template #default="{ row }">
                <el-tag :type="row.status === 'active' ? 'success' : 'info'" size="small">{{ row.status === 'active' ? '启用' : '停用' }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="created_at" label="创建时间" width="180" />
            <el-table-column label="操作" width="200">
              <template #default="{ row }">
                <el-button type="primary" size="small" link @click="openSecretDialog(row)">添加密钥</el-button>
                <el-button type="success" size="small" link>编辑</el-button>
                <el-button type="danger" size="small" link>删除</el-button>
              </template>
            </el-table-column>
          </el-table>
          <el-empty v-if="!app?.environments?.length" description="暂无环境配置" />
        </el-tab-pane>

        <el-tab-pane label="密钥管理" name="secret">
          <el-table :data="app?.secrets || []" size="small">
            <el-table-column prop="env_name" label="环境" width="100" />
            <el-table-column prop="secret_type" label="类型" width="120" />
            <el-table-column prop="secret_key" label="密钥名称" width="150" />
            <el-table-column prop="secret_value" label="密钥值" />
            <el-table-column prop="status" label="状态" width="80">
              <template #default="{ row }">
                <el-tag :type="row.status === 'active' ? 'success' : 'info'" size="small">{{ row.status === 'active' ? '活跃' : '停用' }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="expires_at" label="过期时间" width="180" />
            <el-table-column label="操作" width="150">
              <template #default="{ row }">
                <el-button type="warning" size="small" link>轮换</el-button>
                <el-button type="danger" size="small" link>删除</el-button>
              </template>
            </el-table-column>
          </el-table>
          <el-empty v-if="!app?.secrets?.length" description="暂无密钥" />
        </el-tab-pane>

        <el-tab-pane label="版本历史" name="version">
          <el-empty description="暂无版本记录" />
        </el-tab-pane>

        <el-tab-pane label="操作时间线" name="timeline">
          <el-timeline>
            <el-timeline-item
              v-for="item in timeline"
              :key="item.id"
              :timestamp="item.time"
              placement="top"
            >
              <template #dot>
                <el-icon :size="15"><DocumentChecked /></el-icon>
              </template>
              <h4>{{ item.description }}</h4>
              <p style="color: #909399; font-size: 12px">操作人: {{ item.user }}</p>
            </el-timeline-item>
          </el-timeline>
          <el-empty v-if="timeline.length === 0" description="暂无操作记录" />
        </el-tab-pane>
      </el-tabs>
    </el-card>

    <el-dialog v-model="envDialogVisible" title="添加环境" width="500px">
      <el-form :model="envForm" label-width="100px">
        <el-form-item label="环境名称">
          <el-input v-model="envForm.name" placeholder="如: development, production" />
        </el-form-item>
        <el-form-item label="环境类型">
          <el-select v-model="envForm.type" style="width: 100%">
            <el-option label="开发环境" value="development" />
            <el-option label="测试环境" value="testing" />
            <el-option label="预发布环境" value="staging" />
            <el-option label="生产环境" value="production" />
          </el-select>
        </el-form-item>
        <el-form-item label="基础地址">
          <el-input v-model="envForm.base_url" placeholder="https://api.example.com" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="envDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="createEnv">确定</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="secretDialogVisible" title="添加密钥" width="500px">
      <el-form :model="secretForm" label-width="100px">
        <el-form-item label="环境">
          <el-select v-model="secretForm.env_id" style="width: 100%">
            <el-option v-for="env in app?.environments" :key="env.id" :label="env.name" :value="env.id" />
          </el-select>
        </el-form-item>
        <el-form-item label="密钥类型">
          <el-select v-model="secretForm.secret_type" style="width: 100%">
            <el-option label="客户端密钥" value="client_secret" />
            <el-option label="API密钥" value="api_key" />
            <el-option label="证书" value="certificate" />
            <el-option label="私钥" value="private_key" />
          </el-select>
        </el-form-item>
        <el-form-item label="密钥名称">
          <el-input v-model="secretForm.secret_key" placeholder="如: client_id, api_key" />
        </el-form-item>
        <el-form-item label="过期时间">
          <el-date-picker v-model="secretForm.expires_at" type="datetime" placeholder="选择过期时间" style="width: 100%" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="secretDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="createSecret">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { appApi, envApi, secretApi, auditApi } from '../api'

const route = useRoute()
const loading = ref(false)
const app = ref(null)
const activeTab = ref('env')
const timeline = ref([])
const envDialogVisible = ref(false)
const secretDialogVisible = ref(false)
const currentEnv = ref(null)

const envForm = reactive({
  name: '',
  type: 'development',
  base_url: ''
})

const secretForm = reactive({
  env_id: null,
  secret_type: 'client_secret',
  secret_key: '',
  expires_at: null
})

async function loadApp() {
  loading.value = true
  try {
    app.value = await appApi.get(route.params.id)
    loadTimeline()
  } catch (e) {
    ElMessage.error('加载失败')
  } finally {
    loading.value = false
  }
}

async function loadTimeline() {
  try {
    const res = await auditApi.timeline({ resource_type: 'application', resource_id: route.params.id })
    timeline.value = res.data
  } catch (e) {
    console.error(e)
  }
}

function openEnvDialog() {
  Object.assign(envForm, { name: '', type: 'development', base_url: '' })
  envDialogVisible.value = true
}

async function createEnv() {
  try {
    await envApi.create({ ...envForm, app_id: app.value.id })
    ElMessage.success('创建成功')
    envDialogVisible.value = false
    loadApp()
  } catch (e) {
    ElMessage.error('创建失败')
  }
}

function openSecretDialog(env) {
  currentEnv.value = env
  Object.assign(secretForm, {
    env_id: env.id,
    secret_type: 'client_secret',
    secret_key: '',
    expires_at: null
  })
  secretDialogVisible.value = true
}

async function createSecret() {
  try {
    await secretApi.create({ ...secretForm, app_id: app.value.id })
    ElMessage.success('创建成功')
    secretDialogVisible.value = false
    loadApp()
  } catch (e) {
    ElMessage.error('创建失败')
  }
}

function getTypeText(type) {
  const map = { web: 'Web应用', mobile: '移动应用', api: 'API服务', desktop: '桌面应用' }
  return map[type] || type
}

function getStatusType(status) {
  const map = { development: 'info', testing: 'warning', production: 'success', disabled: 'danger' }
  return map[status] || 'info'
}

function getStatusText(status) {
  const map = { development: '开发中', testing: '测试中', production: '生产中', disabled: '已停用' }
  return map[status] || status
}

onMounted(() => {
  loadApp()
})
</script>
