// frontend/src/views/Cart.vue
<template>
  <div class="min-h-screen bg-pdd-bg pb-24">
    <div class="sticky top-0 bg-white z-30 px-3 py-2 border-b">
      <h1 class="text-center font-medium text-lg">购物车</h1>
    </div>

    <div v-if="loading" class="py-10">
      <Loading />
    </div>

    <div v-else-if="carts.length === 0" class="py-20">
      <Empty icon="🛒" text="购物车是空的" />
      <div class="text-center mt-4">
        <button @click="$router.push('/')" class="px-6 py-2 bg-pdd-red text-white rounded-full text-sm">
          去逛逛
        </button>
      </div>
    </div>

    <div v-else>
      <div class="space-y-2 px-3 py-2">
        <div
          v-for="item in carts"
          :key="item.id"
          class="bg-white rounded-lg p-3 flex items-center gap-3"
        >
          <button @click="toggleSelect(item)" class="text-xl">
            {{ item.selected ? '✅' : '⬜' }}
          </button>
          <img :src="item.product_image" class="w-20 h-20 object-cover rounded" @click="$router.push(`/product/${item.product_id}`)" />
          <div class="flex-1 min-w-0">
            <h3 class="text-sm text-gray-800 line-clamp-2">{{ item.product_name }}</h3>
            <div class="flex items-center justify-between mt-2">
              <span class="text-pdd-red font-bold">¥{{ item.price?.toFixed?.(2) || item.price }}</span>
              <div class="flex items-center gap-2">
                <button
                  @click="updateQuantity(item, item.quantity - 1)"
                  :disabled="item.quantity <= 1"
                  class="w-6 h-6 flex items-center justify-center bg-gray-100 rounded text-gray-600 disabled:text-gray-300"
                >
                  -
                </button>
                <span class="w-6 text-center text-sm">{{ item.quantity }}</span>
                <button
                  @click="updateQuantity(item, item.quantity + 1)"
                  :disabled="item.quantity >= item.stock"
                  class="w-6 h-6 flex items-center justify-center bg-gray-100 rounded text-gray-600 disabled:text-gray-300"
                >
                  +
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="fixed bottom-0 left-0 right-0 bg-white border-t z-40 px-3 py-2 safe-bottom">
      <div class="flex items-center gap-3">
        <button @click="toggleSelectAll" class="text-xl">
          {{ isAllSelected ? '✅' : '⬜' }}
        </button>
        <span class="text-sm">全选</span>
        <div class="flex-1 text-right">
          <span class="text-sm text-gray-500">合计: </span>
          <span class="text-pdd-red text-xl font-bold">¥{{ totalPrice.toFixed(2) }}</span>
        </div>
        <button
          @click="goCheckout"
          :disabled="selectedCount === 0"
          class="px-6 py-2 bg-pdd-red text-white rounded-full text-sm font-medium disabled:bg-gray-300"
        >
          去结算({{ selectedCount }})
        </button>
      </div>
    </div>

    <TabBar />
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from '../stores/toast'
import { cartApi } from '../api'
import Loading from '../components/Loading.vue'
import Empty from '../components/Empty.vue'
import TabBar from '../components/TabBar.vue'

const router = useRouter()
const toast = useToast()

const loading = ref(true)
const carts = ref([])

const selectedCount = computed(() => carts.value.filter(c => c.selected).length)
const isAllSelected = computed(() => carts.value.length > 0 && carts.value.every(c => c.selected))
const totalPrice = computed(() => {
  return carts.value
    .filter(c => c.selected)
    .reduce((sum, item) => sum + (item.price || 0) * (item.quantity || 0), 0)
})

async function loadCarts() {
  loading.value = true
  try {
    const res = await cartApi.getList()
    if (res.success) {
      carts.value = res.data || []
    }
  } catch (e) {
    console.error('加载购物车失败:', e)
  } finally {
    loading.value = false
  }
}

async function toggleSelect(item) {
  try {
    await cartApi.updateCart(item.id, undefined, !item.selected)
    item.selected = !item.selected
  } catch (e) {
    console.error('更新购物车失败:', e)
  }
}

async function toggleSelectAll() {
  const newSelected = !isAllSelected.value
  try {
    for (const item of carts.value) {
      if (item.selected !== newSelected) {
        await cartApi.updateCart(item.id, undefined, newSelected)
        item.selected = newSelected
      }
    }
  } catch (e) {
    console.error('全选失败:', e)
  }
}

async function updateQuantity(item, quantity) {
  if (quantity < 1 || quantity > item.stock) return
  
  try {
    await cartApi.updateCart(item.id, quantity, undefined)
    item.quantity = quantity
  } catch (e) {
    console.error('更新数量失败:', e)
  }
}

function goCheckout() {
  const selected = carts.value.filter(c => c.selected)
  if (selected.length === 0) {
    toast.warning('请选择要结算的商品')
    return
  }
  
  router.push({ name: 'Checkout', query: { productId: selected[0].product_id, quantity: selected[0].quantity } })
}

onMounted(() => {
  loadCarts()
})
</script>

// frontend/src/pages/Cart.jsx
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, Trash2 } from 'lucide-react'
import { useCartStore } from '../store'

export default function Cart() {
  const navigate = useNavigate()
  const { items, removeItem, updateQuantity, getTotal, clearCart } = useCartStore()

  if (items.length === 0) {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="bg-white p-4 flex items-center sticky top-0 z-10">
          <button onClick={() => navigate(-1)} className="mr-4">
            <ArrowLeft className="w-6 h-6" />
          </button>
          <h1 className="font-medium">购物车</h1>
        </div>
        <div className="flex flex-col items-center justify-center py-20">
          <div className="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mb-4">
            <svg className="w-12 h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
          </div>
          <p className="text-gray-500">购物车是空的</p>
          <button
            onClick={() => navigate('/products')}
            className="mt-4 bg-red-500 text-white px-6 py-2 rounded-lg"
          >
            去逛逛
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      <div className="bg-white p-4 flex items-center sticky top-0 z-10">
        <button onClick={() => navigate(-1)} className="mr-4">
          <ArrowLeft className="w-6 h-6" />
        </button>
        <h1 className="font-medium">购物车({items.length})</h1>
      </div>

      <div className="p-4 space-y-3">
        {items.map((item) => (
          <div key={item.id} className="bg-white rounded-xl p-3 flex">
            <img
              src={item.images}
              alt={item.name}
              className="w-20 h-20 object-cover rounded-lg"
            />
            <div className="flex-1 ml-3">
              <h3 className="font-medium text-sm line-clamp-2">{item.name}</h3>
              <p className="text-red-500 font-bold mt-1">¥{item.price}</p>
              <div className="flex items-center justify-between mt-2">
                <div className="flex items-center border rounded-lg">
                  <button
                    onClick={() => {
                      if (item.quantity > 1) {
                        updateQuantity(item.id, item.quantity - 1)
                      } else {
                        removeItem(item.id)
                      }
                    }}
                    className="w-8 h-8 flex items-center justify-center"
                  >
                    -
                  </button>
                  <span className="w-8 text-center text-sm">{item.quantity}</span>
                  <button
                    onClick={() => updateQuantity(item.id, item.quantity + 1)}
                    className="w-8 h-8 flex items-center justify-center"
                  >
                    +
                  </button>
                </div>
                <button
                  onClick={() => removeItem(item.id)}
                  className="text-gray-400"
                >
                  <Trash2 className="w-5 h-5" />
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="fixed bottom-16 left-0 right-0 bg-white border-t p-4 max-w-md mx-auto">
        <div className="flex items-center justify-between">
          <div>
            <span className="text-sm text-gray-500">合计：</span>
            <span className="text-red-500 font-bold text-xl">¥{getTotal()}</span>
          </div>
          <button
            onClick={() => navigate('/confirm-order')}
            className="bg-red-500 text-white px-8 py-2.5 rounded-lg font-medium"
          >
            结算({items.length})
          </button>
        </div>
      </div>
    </div>
  )
}
