// frontend/src/pages/Cart.vue
<template>
  <div class="cart">
    <div class="header">
      <button class="back-btn" @click="$router.back()">←</button>
      <h2>购物车</h2>
    </div>
    
    <div class="content">
      <div v-if="cart.length === 0" class="empty">
        <div class="empty-icon">🛒</div>
        <p>购物车是空的</p>
        <button class="btn btn-primary" @click="$router.push('/menu')">去点餐</button>
      </div>
      
      <div v-else>
        <div v-for="item in cart" :key="item.id" class="cart-item card">
          <div class="item-info">
            <h4>{{ item.name }}</h4>
            <span v-if="item.is_set_meal" class="tag">套餐</span>
            <p class="price">¥{{ item.price.toFixed(2) }}</p>
          </div>
          <div class="item-actions">
            <button class="minus-btn" @click="updateQuantity(item, -1)">-</button>
            <span class="quantity">{{ item.quantity }}</span>
            <button class="add-btn" @click="updateQuantity(item, 1)">+</button>
          </div>
        </div>
        
        <div class="summary card">
          <div class="summary-row">
            <span>共{{ cartCount }}件</span>
            <span class="total">¥{{ totalPrice.toFixed(2) }}</span>
          </div>
          <button class="btn btn-primary btn-block" @click="submitOrder" :disabled="submitting">
            {{ submitting ? '提交中...' : '提交订单' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  name: 'Cart',
  data() {
    return {
      cart: [],
      submitting: false
    }
  },
  computed: {
    cartCount() {
      return this.cart.reduce((sum, item) => sum + item.quantity, 0)
    },
    totalPrice() {
      return this.cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
    }
  },
  mounted() {
    this.loadCart()
  },
  methods: {
    loadCart() {
      const saved = localStorage.getItem('cart')
      if (saved) {
        this.cart = JSON.parse(saved)
      }
    },
    saveCart() {
      localStorage.setItem('cart', JSON.stringify(this.cart))
    },
    updateQuantity(item, delta) {
      item.quantity += delta
      if (item.quantity <= 0) {
        this.cart = this.cart.filter(i => i.id !== item.id)
      }
      this.saveCart()
    },
    async submitOrder() {
      if (this.submitting) return
      this.submitting = true
      
      try {
        const restaurantId = localStorage.getItem('restaurantId') || 1
        const tableId = localStorage.getItem('tableId')
        const queueId = localStorage.getItem('queueId')
        
        const orderItems = this.cart.map(item => ({
          menu_item_id: item.menu_item_id,
          quantity: item.quantity,
          price: item.price
        }))
        
        const res = await axios.post('http://localhost:19881/api/orders', {
          restaurant_id: restaurantId,
          table_id: tableId ? parseInt(tableId) : null,
          queue_id: queueId ? parseInt(queueId) : null,
          items: orderItems
        })
        
        localStorage.removeItem('cart')
        localStorage.removeItem('tableId')
        localStorage.removeItem('queueId')
        this.$router.push(`/order/${res.data.id}`)
      } catch (e) {
        console.error(e)
        alert('提交失败，请重试')
      } finally {
        this.submitting = false
      }
    }
  }
}
</script>

<style scoped>
.cart {
  min-height: 100vh;
  background: #f5f5f5;
}
.header {
  background: white;
  padding: 16px 20px;
  display: flex;
  align-items: center;
  gap: 12px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
.back-btn {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  padding: 4px 8px;
}
.header h2 {
  font-size: 18px;
  color: #333;
}
.content {
  padding: 20px;
}
.empty {
  text-align: center;
  padding: 60px 20px;
}
.empty-icon {
  font-size: 80px;
  margin-bottom: 16px;
}
.empty p {
  color: #666;
  margin-bottom: 20px;
}
.cart-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.item-info {
  flex: 1;
}
.item-info h4 {
  font-size: 16px;
  color: #333;
  margin-bottom: 4px;
}
.tag {
  background: #ff6b6b;
  color: white;
  font-size: 10px;
  padding: 2px 6px;
  border-radius: 4px;
  margin-right: 8px;
}
.price {
  font-size: 18px;
  color: #ff6b6b;
  font-weight: bold;
  margin-top: 8px;
}
.item-actions {
  display: flex;
  align-items: center;
  gap: 12px;
}
.add-btn, .minus-btn {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  border: none;
  font-size: 20px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}
.add-btn {
  background: #ff6b6b;
  color: white;
}
.minus-btn {
  background: #eee;
  color: #333;
}
.quantity {
  font-size: 18px;
  min-width: 24px;
  text-align: center;
}
.summary {
  margin-top: 16px;
}
.summary-row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 16px;
}
.total {
  font-size: 24px;
  color: #ff6b6b;
  font-weight: bold;
}
</style>

// frontend/src/pages/Cart.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';
import axios from 'axios';

const Cart = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [items, setItems] = useState([]);

  useEffect(() => {
    if (!user) return;
    axios.get('/api/cart').then(res => setItems(res.data));
  }, [user]);

  if (!user) {
    return (
      <div style={{ 
        textAlign: 'center', 
        padding: '80px 20px',
        background: '#fff',
        minHeight: '80vh'
      }}>
        <div style={{ fontSize: '80px', marginBottom: '20px' }}>🔒</div>
        <h2 style={{ marginBottom: '10px', color: '#333' }}>请先登录</h2>
        <p style={{ color: '#999', marginBottom: '30px' }}>登录后可以使用购物车功能</p>
        <button 
          onClick={() => navigate('/login')}
          style={{
            padding: '12px 40px',
            background: '#ff4d4f',
            color: '#fff',
            border: 'none',
            borderRadius: '25px',
            fontSize: '16px',
            cursor: 'pointer'
          }}
        >
          立即登录
        </button>
      </div>
    );
  }

  const removeItem = async (id) => {
    await axios.delete(`/api/cart/${id}`);
    setItems(items.filter(i => i.id !== id));
  };

  const checkout = async () => {
    await axios.post('/api/orders');
    alert('下单成功');
    navigate('/orders');
  };

  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);

  const styles = {
    container: {
      padding: '15px'
    },
    empty: {
      textAlign: 'center',
      padding: '60px 20px'
    },
    item: {
      background: '#fff',
      borderRadius: '8px',
      padding: '15px',
      marginBottom: '10px',
      display: 'flex',
      gap: '10px'
    },
    img: {
      width: '80px',
      height: '80px',
      borderRadius: '8px',
      objectFit: 'cover',
      background: '#f0f0f0'
    },
    info: {
      flex: 1
    },
    title: {
      fontSize: '14px',
      marginBottom: '8px'
    },
    price: {
      color: '#ff4d4f',
      fontSize: '18px',
      fontWeight: 'bold',
      marginBottom: '10px'
    },
    actions: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center'
    },
    deleteBtn: {
      background: 'none',
      border: 'none',
      color: '#999',
      fontSize: '14px'
    },
    bottomBar: {
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      height: '60px',
      background: '#fff',
      display: 'flex',
      alignItems: 'center',
      padding: '0 15px',
      borderTop: '1px solid #eee',
      zIndex: 100
    },
    total: {
      flex: 1
    },
    totalLabel: {
      color: '#666',
      fontSize: '14px'
    },
    totalPrice: {
      color: '#ff4d4f',
      fontSize: '20px',
      fontWeight: 'bold'
    },
    checkoutBtn: {
      padding: '12px 30px',
      background: '#ff4d4f',
      color: '#fff',
      border: 'none',
      borderRadius: '20px',
      fontSize: '16px'
    }
  };

  if (!items.length) {
    return (
      <div style={styles.empty}>
        <div style={{ fontSize: '60px', marginBottom: '20px' }}>🛒</div>
        <p style={{ color: '#999' }}>购物车是空的</p>
      </div>
    );
  }

  return (
    <div style={{ ...styles.container, paddingBottom: '80px' }}>
      {items.map(item => (
        <div key={item.id} style={styles.item}>
          <img src={item.image} style={styles.img} alt={item.title} />
          <div style={styles.info}>
            <div style={styles.title}>{item.title}</div>
            <div style={styles.price}>¥{item.price}</div>
            <div style={styles.actions}>
              <span style={{ color: '#666' }}>x{item.quantity}</span>
              <button onClick={() => removeItem(item.id)} style={styles.deleteBtn}>删除</button>
            </div>
          </div>
        </div>
      ))}
      <div style={styles.bottomBar}>
        <div style={styles.total}>
          <span style={styles.totalLabel}>合计：</span>
          <span style={styles.totalPrice}>¥{total.toFixed(2)}</span>
        </div>
        <button onClick={checkout} style={styles.checkoutBtn}>结算</button>
      </div>
    </div>
  );
};

export default Cart;
