// client/src/views/Checkout.vue
<template>
  <div class="checkout page-container">
    <div class="header">
      <span class="back-btn" @click="goBack">←</span>
      <div class="header-title">确认订单</div>
    </div>

    <div class="address-card card">
      <div class="address-icon">📍</div>
      <div class="address-info">
        <div class="address-header">
          <span class="receiver">{{ address.receiver }}</span>
          <span class="phone">{{ address.phone }}</span>
        </div>
        <div class="address-detail">{{ address.address }}</div>
      </div>
      <div class="arrow">›</div>
    </div>

    <div class="product-card card">
      <div class="card-header">
        <span class="card-title">商品列表</span>
        <span class="count">共 {{ items.length }} 件</span>
      </div>
      <div v-for="item in items" :key="item.id" class="product-item">
        <img :src="item.cover_image" class="product-image" />
        <div class="product-info">
          <div class="product-title text-ellipsis-2">{{ item.title }}</div>
          <div class="product-bottom">
            <span class="price">¥{{ item.price }}</span>
            <span class="qty">x{{ item.quantity }}</span>
          </div>
        </div>
      </div>
    </div>

    <div class="summary-card card">
      <div class="summary-row">
        <span class="label">商品金额</span>
        <span class="value">¥{{ totalAmount.toFixed(2) }}</span>
      </div>
      <div class="summary-row">
        <span class="label">运费</span>
        <span class="value">¥{{ shipping.toFixed(2) }}</span>
      </div>
      <div class="summary-row">
        <span class="label">优惠</span>
        <span class="value discount">-¥{{ discount.toFixed(2) }}</span>
      </div>
      <div class="divider"></div>
      <div class="summary-row total">
        <span class="label">实付金额</span>
        <span class="value price">¥{{ payAmount.toFixed(2) }}</span>
      </div>
    </div>

    <div class="bottom-bar safe-area-bottom">
      <div class="total-section">
        <span class="label">实付：</span>
        <span class="price">¥{{ payAmount.toFixed(2) }}</span>
      </div>
      <button 
        class="btn btn-primary submit-btn"
        @click="submitOrder"
        :disabled="loading"
      >
        {{ loading ? '提交中...' : '提交订单' }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, inject } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { orderApi } from '../api';

const route = useRoute();
const router = useRouter();
const showToast = inject('showToast');

const items = ref([]);
const loading = ref(false);

const address = ref({
  receiver: '张三',
  phone: '138****8000',
  address: '北京市朝阳区xxx路xxx小区xxx号楼xxx单元xxx室'
});

const totalAmount = computed(() => {
  return items.value.reduce((sum, item) => sum + item.price * item.quantity, 0);
});

const shipping = computed(() => {
  return totalAmount.value >= 99 ? 0 : 10;
});

const discount = computed(() => {
  return 0;
});

const payAmount = computed(() => {
  return totalAmount.value + shipping.value - discount.value;
});

const goBack = () => {
  router.back();
};

const submitOrder = async () => {
  if (items.value.length === 0) {
    showToast('请选择商品');
    return;
  }
  
  loading.value = true;
  
  try {
    const orderItems = items.value.map(item => ({
      productId: item.product_id,
      skuId: item.sku_id,
      quantity: item.quantity,
      cartId: item.id
    }));
    
    const res = await orderApi.createOrder({
      items: orderItems,
      address: address.value.address,
      phone: '13800138000',
      receiver: address.value.receiver
    });
    
    if (res.code === 200) {
      showToast('下单成功');
      router.replace(`/order/${res.data.orderId}`);
    } else {
      showToast(res.message || '下单失败');
    }
  } catch (e) {
    console.error(e);
    showToast(e.response?.data?.message || '下单失败');
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  try {
    const itemsParam = route.query.items;
    if (itemsParam) {
      items.value = JSON.parse(decodeURIComponent(itemsParam));
    }
  } catch (e) {
    console.error(e);
  }
});
</script>

<style scoped>
.checkout {
  background: #f5f5f5;
  padding-bottom: 70px;
  min-height: 100vh;
}

.header {
  position: sticky;
  top: 0;
  background: #fff;
  padding: 12px 16px;
  display: flex;
  align-items: center;
  gap: 16px;
  border-bottom: 1px solid #eee;
  z-index: 100;
}

.back-btn {
  font-size: 20px;
  color: #333;
}

.header-title {
  font-size: 16px;
  font-weight: bold;
}

.address-card {
  display: flex;
  align-items: center;
  padding: 16px;
  margin: 12px;
  gap: 12px;
}

.address-icon {
  font-size: 24px;
}

.address-info {
  flex: 1;
}

.address-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 6px;
}

.receiver {
  font-size: 15px;
  font-weight: 500;
  color: #333;
}

.phone {
  font-size: 14px;
  color: #666;
}

.address-detail {
  font-size: 13px;
  color: #666;
  line-height: 1.5;
}

.arrow {
  font-size: 20px;
  color: #ccc;
}

.product-card {
  margin: 12px;
  overflow: hidden;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  border-bottom: 1px solid #f5f5f5;
}

.card-title {
  font-size: 14px;
  font-weight: bold;
  color: #333;
}

.count {
  font-size: 13px;
  color: #999;
}

.product-item {
  display: flex;
  padding: 12px 16px;
  gap: 12px;
  border-bottom: 1px solid #f5f5f5;
}

.product-item:last-child {
  border-bottom: none;
}

.product-image {
  width: 80px;
  height: 80px;
  object-fit: cover;
  border-radius: 6px;
  flex-shrink: 0;
}

.product-info {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}

.product-title {
  font-size: 14px;
  color: #333;
  line-height: 1.4;
}

.product-bottom {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.price {
  color: #ff4d4f;
  font-weight: bold;
}

.qty {
  font-size: 13px;
  color: #999;
}

.summary-card {
  margin: 12px;
  padding: 16px;
}

.summary-row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 12px;
  font-size: 14px;
}

.summary-row.total {
  margin-bottom: 0;
}

.label {
  color: #666;
}

.value {
  color: #333;
}

.value.discount {
  color: #52c41a;
}

.value.price {
  color: #ff4d4f;
  font-size: 18px;
  font-weight: bold;
}

.summary-row.total .label {
  font-weight: bold;
  color: #333;
}

.bottom-bar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #fff;
  display: flex;
  align-items: center;
  padding: 10px 16px;
  border-top: 1px solid #eee;
  z-index: 100;
}

.total-section {
  flex: 1;
}

.total-section .label {
  font-size: 14px;
}

.total-section .price {
  font-size: 20px;
  font-weight: bold;
  color: #ff4d4f;
}

.submit-btn {
  height: 44px;
  padding: 0 32px;
  font-size: 15px;
  font-weight: bold;
}

.submit-btn:disabled {
  opacity: 0.7;
}
</style>

// frontend/src/pages/Checkout.jsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, MapPin, ChevronRight } from 'lucide-react'
import useStore from '../store/useStore'
import api from '../utils/api'
import { showToast } from '../utils/toast'

function Checkout() {
  const navigate = useNavigate()
  const user = useStore((state) => state.user)
  const [checkoutData, setCheckoutData] = useState(null)
  const [loading, setLoading] = useState(false)
  const [isGroupBuy, setIsGroupBuy] = useState(false)
  const [groupBuyId, setGroupBuyId] = useState(null)
  
  useEffect(() => {
    const data = localStorage.getItem('checkoutData')
    if (data) {
      try {
        const parsed = JSON.parse(data)
        setCheckoutData(parsed)
      } catch (e) {
        navigate('/cart')
      }
    } else {
      navigate('/cart')
    }
    
    const gbId = localStorage.getItem('joinGroupBuyId')
    if (gbId) {
      setIsGroupBuy(true)
      setGroupBuyId(parseInt(gbId))
      localStorage.removeItem('joinGroupBuyId')
    }
  }, [])
  
  const getTotalAmount = () => {
    if (!checkoutData?.items) return 0
    return checkoutData.items.reduce((sum, item) => sum + item.price * item.quantity, 0)
  }
  
  const submitOrder = async () => {
    if (!checkoutData) return
    
    setLoading(true)
    
    try {
      const address = {
        name: user?.nickname || '用户',
        phone: user?.phone || '13800000000',
        address: '测试地址（实际项目中需要地址管理功能）'
      }
      
      const orderData = {
        address,
        is_group_buy: isGroupBuy,
        group_buy_id: groupBuyId
      }
      
      if (checkoutData.cart_ids) {
        orderData.cart_ids = checkoutData.cart_ids
      } else if (checkoutData.items?.length === 1) {
        const item = checkoutData.items[0]
        orderData.product_id = item.product_id
        orderData.sku_id = item.sku_id
        orderData.quantity = item.quantity
      }
      
      const response = await api.post('/order/create', orderData)
      
      if (response.order?.id) {
        await api.post(`/order/${response.order.id}/pay`)
        localStorage.removeItem('checkoutData')
        showToast('下单成功')
        navigate(`/order/${response.order.id}`, { replace: true })
      }
    } catch (error) {
      showToast(error.response?.data?.error || '下单失败')
    } finally {
      setLoading(false)
    }
  }
  
  if (!checkoutData) {
    return <div className="loading">加载中...</div>
  }
  
  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#f5f5f5', paddingBottom: 80 }}>
      <div className="header">
        <div className="back-btn" onClick={() => navigate(-1)}>
          <ArrowLeft size={22} />
        </div>
        <div className="header-title">确认订单</div>
      </div>
      
      <div className="checkout-address">
        <div className="checkout-address-row">
          <MapPin size={22} color="#ff4d4f" />
          <div style={{ flex: 1, marginLeft: 12 }}>
            <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
              <span style={{ fontWeight: 600 }}>{user?.nickname || '用户'}</span>
              <span style={{ color: '#666' }}>{user?.phone || '13800000000'}</span>
            </div>
            <p style={{ fontSize: 13, color: '#999', marginTop: 4 }}>
              测试地址（实际项目中需要地址管理功能）
            </p>
          </div>
          <ChevronRight size={20} color="#999" />
        </div>
      </div>
      
      <div className="checkout-items">
        {checkoutData.items?.map((item, idx) => (
          <div key={idx} className="checkout-item">
            <img
              src={item.images?.[0] || item.product?.images?.[0] || 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=product%20placeholder&image_size=square_hd'}
              alt={item.name || item.product?.name}
            />
            <div style={{ flex: 1, minWidth: 0 }}>
              <p style={{ fontSize: 14, lineHeight: 1.4, display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                {item.name || item.product?.name}
              </p>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8 }}>
                <span style={{ color: '#ff4d4f', fontWeight: 600 }}>
                  ¥{item.price?.toFixed(2)}
                </span>
                <span style={{ color: '#999' }}>x{item.quantity}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
      
      {isGroupBuy && (
        <div style={{ backgroundColor: '#fff', padding: 16, marginBottom: 12, borderRadius: 12 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ color: '#ff4d4f', fontWeight: 600 }}>🎁 拼团模式</span>
          </div>
        </div>
      )}
      
      <div className="checkout-summary">
        <div className="checkout-summary-row">
          <span>商品金额</span>
          <span>¥{getTotalAmount().toFixed(2)}</span>
        </div>
        <div className="checkout-summary-row">
          <span>运费</span>
          <span>¥0.00</span>
        </div>
        <div className="checkout-summary-row">
          <span>优惠</span>
          <span style={{ color: '#ff4d4f' }}>-¥0.00</span>
        </div>
        <div className="checkout-summary-row total">
          <span>实付款</span>
          <span style={{ color: '#ff4d4f' }}>¥{getTotalAmount().toFixed(2)}</span>
        </div>
      </div>
      
      <div className="checkout-bottom">
        <div>
          <span style={{ fontSize: 14, color: '#666' }}>实付: </span>
          <span style={{ fontSize: 20, fontWeight: 700, color: '#ff4d4f' }}>
            ¥{getTotalAmount().toFixed(2)}
          </span>
        </div>
        <button
          className="btn-submit-order"
          onClick={submitOrder}
          disabled={loading}
        >
          {loading ? '提交中...' : '提交订单'}
        </button>
      </div>
    </div>
  )
}

export default Checkout
