// src/pages/admin/DashboardPage.vue
<template>
  <div class="space-y-6">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
      <div class="stat-card">
        <div class="flex items-start justify-between">
          <div>
            <div class="stat-label">今日订单</div>
            <div class="stat-number mt-2">{{ stats.todayOrders }}</div>
          </div>
          <div class="w-12 h-12 rounded-xl bg-brand-50 flex items-center justify-center">
            <component :is="icons.Package" class="w-6 h-6 text-brand-500" />
          </div>
        </div>
        <div class="flex items-center gap-2 mt-3">
          <span class="flex items-center gap-1 text-green-600 text-sm font-medium">
            <component :is="icons.TrendingUp" class="w-4 h-4" />
            12.5%
          </span>
          <span class="text-gray-400 text-sm">较昨日</span>
        </div>
      </div>
      <div class="stat-card">
        <div class="flex items-start justify-between">
          <div>
            <div class="stat-label">今日营收</div>
            <div class="stat-number mt-2">¥{{ formatNumber(stats.todayRevenue) }}</div>
          </div>
          <div class="w-12 h-12 rounded-xl bg-green-50 flex items-center justify-center">
            <component :is="icons.Banknote" class="w-6 h-6 text-green-600" />
          </div>
        </div>
        <div class="flex items-center gap-2 mt-3">
          <span class="flex items-center gap-1 text-green-600 text-sm font-medium">
            <component :is="icons.TrendingUp" class="w-4 h-4" />
            8.3%
          </span>
          <span class="text-gray-400 text-sm">较昨日</span>
        </div>
      </div>
      <div class="stat-card">
        <div class="flex items-start justify-between">
          <div>
            <div class="stat-label">在途车辆</div>
            <div class="stat-number mt-2">{{ stats.activeVehicles }}</div>
          </div>
          <div class="w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center">
            <component :is="icons.Truck" class="w-6 h-6 text-blue-600" />
          </div>
        </div>
        <div class="flex items-center gap-2 mt-3">
          <span class="flex items-center gap-1 text-gray-500 text-sm font-medium">
            <component :is="icons.Minus" class="w-4 h-4" />
            持平
          </span>
          <span class="text-gray-400 text-sm">较昨日</span>
        </div>
      </div>
      <div class="stat-card">
        <div class="flex items-start justify-between">
          <div>
            <div class="stat-label">待处理告警</div>
            <div class="stat-number mt-2">{{ stats.pendingAlerts }}</div>
          </div>
          <div class="w-12 h-12 rounded-xl bg-alert-50 flex items-center justify-center">
            <component :is="icons.AlertTriangle" class="w-6 h-6 text-alert-500" />
          </div>
        </div>
        <div class="flex items-center gap-2 mt-3">
          <span class="flex items-center gap-1 text-red-600 text-sm font-medium">
            <component :is="icons.TrendingUp" class="w-4 h-4" />
            2条
          </span>
          <span class="text-gray-400 text-sm">较昨日新增</span>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-5">
      <div class="card-base p-5 lg:col-span-2">
        <div class="flex items-center justify-between mb-4">
          <div>
            <h3 class="text-base font-semibold text-gray-900">周订单趋势</h3>
            <p class="text-xs text-gray-500 mt-0.5">近7天订单数与营收对比</p>
          </div>
          <div class="flex items-center gap-4 text-xs">
            <span class="flex items-center gap-1.5">
              <span class="w-3 h-3 rounded bg-brand-500"></span>
              订单数
            </span>
            <span class="flex items-center gap-1.5">
              <span class="w-3 h-3 rounded bg-alert-500"></span>
              营收
            </span>
          </div>
        </div>
        <div ref="trendChartRef" class="h-72"></div>
      </div>
      <div class="card-base p-5">
        <div class="mb-4">
          <h3 class="text-base font-semibold text-gray-900">服务类型占比</h3>
          <p class="text-xs text-gray-500 mt-0.5">本月各服务类型订单分布</p>
        </div>
        <div ref="pieChartRef" class="h-72"></div>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-5">
      <div class="card-base p-5">
        <div class="mb-4">
          <h3 class="text-base font-semibold text-gray-900">告警类型分布</h3>
          <p class="text-xs text-gray-500 mt-0.5">近30天各类告警数量统计</p>
        </div>
        <div ref="alertChartRef" class="h-64"></div>
      </div>
      <div class="card-base p-5">
        <div class="flex items-center justify-between mb-4">
          <div>
            <h3 class="text-base font-semibold text-gray-900">实时在途车辆</h3>
            <p class="text-xs text-gray-500 mt-0.5">当前正在运输的车辆状态</p>
          </div>
          <router-link to="/admin/vehicles" class="text-xs text-brand-500 hover:text-brand-600 flex items-center gap-1">
            查看全部
            <component :is="icons.ChevronRight" class="w-3 h-3" />
          </router-link>
        </div>
        <div class="space-y-3 max-h-64 overflow-auto">
          <div
            v-for="vehicle in runningVehicles"
            :key="vehicle.plateNo"
            class="flex items-center justify-between p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-lg bg-brand-50 flex items-center justify-center">
                <component :is="icons.Truck" class="w-5 h-5 text-brand-500" />
              </div>
              <div>
                <div class="text-sm font-semibold text-gray-900">{{ vehicle.plateNo }}</div>
                <div class="text-xs text-gray-500">{{ vehicle.currentLocation }}</div>
              </div>
            </div>
            <div class="text-right">
              <div class="text-sm font-din font-bold text-gray-900">{{ vehicle.currentSpeed }} <span class="text-xs font-normal text-gray-500">km/h</span></div>
              <span class="badge badge-success">
                <span class="w-1.5 h-1.5 rounded-full bg-green-500 mr-1 animate-pulse"></span>
                运行中
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card-base p-5">
      <div class="flex items-center justify-between mb-4">
        <div>
          <h3 class="text-base font-semibold text-gray-900">最新告警</h3>
          <p class="text-xs text-gray-500 mt-0.5">需及时处理的运输异常事件</p>
        </div>
        <button class="text-xs text-brand-500 hover:text-brand-600 flex items-center gap-1">
          处理全部
          <component :is="icons.ChevronRight" class="w-3 h-3" />
        </button>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="border-b border-gray-100">
              <th class="text-left text-xs font-medium text-gray-500 py-3 px-2">级别</th>
              <th class="text-left text-xs font-medium text-gray-500 py-3 px-2">类型</th>
              <th class="text-left text-xs font-medium text-gray-500 py-3 px-2">运单号</th>
              <th class="text-left text-xs font-medium text-gray-500 py-3 px-2">位置</th>
              <th class="text-left text-xs font-medium text-gray-500 py-3 px-2">告警信息</th>
              <th class="text-left text-xs font-medium text-gray-500 py-3 px-2">时间</th>
              <th class="text-left text-xs font-medium text-gray-500 py-3 px-2">操作</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="alert in alerts"
              :key="alert.id"
              class="border-b border-gray-50 hover:bg-gray-50 transition-colors"
            >
              <td class="py-3 px-2">
                <span :class="alert.level === 'critical' ? 'badge badge-danger' : 'badge badge-warning'">
                  {{ alert.level === 'critical' ? '严重' : '预警' }}
                </span>
              </td>
              <td class="py-3 px-2 text-sm text-gray-700">{{ alertTypeMap[alert.type] }}</td>
              <td class="py-3 px-2 text-sm font-medium text-brand-600">{{ alert.waybillNo }}</td>
              <td class="py-3 px-2 text-sm text-gray-700">{{ alert.location }}</td>
              <td class="py-3 px-2 text-sm text-gray-600 max-w-xs truncate">{{ alert.message }}</td>
              <td class="py-3 px-2 text-sm text-gray-500">{{ alert.timestamp }}</td>
              <td class="py-3 px-2">
                <button v-if="!alert.acknowledged" class="text-xs text-brand-500 hover:text-brand-600">
                  确认处理
                </button>
                <span v-else class="text-xs text-gray-400">已处理</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import * as echarts from 'echarts'
import { Package, Banknote, Truck, AlertTriangle, TrendingUp, Minus, ChevronRight } from 'lucide-vue-next'
import { mockDashboardStats, mockAlerts, mockVehicles } from '@/mock'

const icons = { Package, Banknote, Truck, AlertTriangle, TrendingUp, Minus, ChevronRight }

const stats = mockDashboardStats
const alerts = mockAlerts
const runningVehicles = computed(() => mockVehicles.filter(v => v.status === 'running'))

const alertTypeMap: Record<string, string> = {
  temperature: '温度告警',
  humidity: '湿度告警',
  vibration: '震动告警',
  geo: '地理围栏'
}

const trendChartRef = ref<HTMLElement | null>(null)
const pieChartRef = ref<HTMLElement | null>(null)
const alertChartRef = ref<HTMLElement | null>(null)

function formatNumber(num: number): string {
  return num.toLocaleString('zh-CN')
}

onMounted(() => {
  if (trendChartRef.value) {
    const chart = echarts.init(trendChartRef.value)
    chart.setOption({
      tooltip: {
        trigger: 'axis',
        axisPointer: { type: 'cross' }
      },
      grid: { left: 40, right: 60, top: 20, bottom: 30 },
      xAxis: {
        type: 'category',
        data: stats.weeklyOrderTrend.map(d => d.date),
        axisLine: { lineStyle: { color: '#E5E7EB' } },
        axisLabel: { color: '#9CA3AF', fontSize: 12 }
      },
      yAxis: [
        {
          type: 'value',
          name: '订单数',
          nameTextStyle: { color: '#9CA3AF', fontSize: 11 },
          splitLine: { lineStyle: { color: '#F3F4F6' } },
          axisLabel: { color: '#9CA3AF', fontSize: 12 }
        },
        {
          type: 'value',
          name: '营收(万)',
          nameTextStyle: { color: '#9CA3AF', fontSize: 11 },
          splitLine: { show: false },
          axisLabel: { color: '#9CA3AF', fontSize: 12, formatter: (v: number) => (v / 10000).toFixed(0) }
        }
      ],
      series: [
        {
          name: '订单数',
          type: 'bar',
          data: stats.weeklyOrderTrend.map(d => d.count),
          itemStyle: { color: '#0052D9', borderRadius: [4, 4, 0, 0] },
          barWidth: 24
        },
        {
          name: '营收',
          type: 'line',
          yAxisIndex: 1,
          data: stats.weeklyOrderTrend.map(d => d.revenue),
          smooth: true,
          lineStyle: { color: '#FF6A00', width: 3 },
          itemStyle: { color: '#FF6A00' },
          areaStyle: {
            color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
              { offset: 0, color: 'rgba(255, 106, 0, 0.25)' },
              { offset: 1, color: 'rgba(255, 106, 0, 0)' }
            ])
          }
        }
      ]
    })
  }

  if (pieChartRef.value) {
    const chart = echarts.init(pieChartRef.value)
    chart.setOption({
      tooltip: { trigger: 'item', formatter: '{b}: {c} ({d}%)' },
      legend: { bottom: 0, icon: 'circle', itemWidth: 8, itemHeight: 8, textStyle: { color: '#6B7280', fontSize: 12 } },
      series: [{
        type: 'pie',
        radius: ['45%', '70%'],
        center: ['50%', '42%'],
        avoidLabelOverlap: false,
        label: { show: false },
        labelLine: { show: false },
        data: stats.serviceDistribution,
        color: ['#0052D9', '#4787F7', '#FF6A00', '#75A5F9']
      }]
    })
  }

  if (alertChartRef.value) {
    const chart = echarts.init(alertChartRef.value)
    chart.setOption({
      tooltip: { trigger: 'axis' },
      grid: { left: 40, right: 20, top: 20, bottom: 30 },
      xAxis: {
        type: 'category',
        data: stats.alertDistribution.map(d => d.type),
        axisLine: { lineStyle: { color: '#E5E7EB' } },
        axisLabel: { color: '#9CA3AF', fontSize: 12 }
      },
      yAxis: {
        type: 'value',
        splitLine: { lineStyle: { color: '#F3F4F6' } },
        axisLabel: { color: '#9CA3AF', fontSize: 12 }
      },
      series: [{
        type: 'bar',
        data: stats.alertDistribution.map(d => ({
          value: d.count,
          itemStyle: { color: d.level === 'critical' ? '#EF4444' : '#FF6A00', borderRadius: [4, 4, 0, 0] }
        })),
        barWidth: 32
      }]
    })
  }
})
</script>

// frontend/src/pages/DashboardPage.tsx
import { useState, useEffect } from 'react'
import { api } from '@/utils/api'
import { Package, Truck, Handshake, Navigation, Loader2, TrendingUp, TrendingDown } from 'lucide-react'
import ReactEChartsCore from 'echarts-for-react/lib/core'
import * as echarts from 'echarts/core'
import { BarChart, LineChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent, TitleComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'

echarts.use([BarChart, LineChart, GridComponent, TooltipComponent, LegendComponent, TitleComponent, CanvasRenderer])

interface CostItem {
  date: string
  index: number
  province: string
}

interface SupplyDemandItem {
  period: string
  province: string
  cargo_demand: number
  vehicle_supply: number
  avg_price: number
  avg_transit_days: number
}

export default function DashboardPage() {
  const [stats, setStats] = useState<any>(null)
  const [costData, setCostData] = useState<CostItem[]>([])
  const [sdData, setSdData] = useState<SupplyDemandItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true)
        setError('')
        const [statsRes, costRes, sdRes] = await Promise.all([
          api.get<any>('/api/dashboard/stats'),
          api.get<any>('/api/dashboard/cost-index'),
          api.get<any>('/api/dashboard/supply-demand'),
        ])
        const s = statsRes?.data ?? statsRes
        setStats(s)
        const c = costRes?.data ?? costRes
        setCostData(Array.isArray(c) ? c : [])
        const sd = sdRes?.data ?? sdRes
        setSdData(Array.isArray(sd) ? sd : [])
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : '获取数据失败'
        setError(msg)
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [])

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32 text-gray-400">
        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
        加载中...
      </div>
    )
  }

  if (error) {
    return (
      <div className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>
    )
  }

  const statCards = [
    { label: '总货源数', value: stats?.totals?.cargo ?? stats?.pending_cargo ?? 0, icon: Package, color: '#E8722A', bg: 'bg-orange-50' },
    { label: '总车源数', value: stats?.totals?.vehicles ?? stats?.idle_vehicle ?? 0, icon: Truck, color: '#1B2A4A', bg: 'bg-blue-50' },
    { label: '运输任务', value: stats?.totals?.tasks ?? stats?.active_tasks ?? 0, icon: Handshake, color: '#16A34A', bg: 'bg-green-50' },
    { label: '在途任务', value: stats?.active_tasks ?? 0, icon: Navigation, color: '#7C3AED', bg: 'bg-purple-50' },
  ]

  const provinces = [...new Set(costData.map((d) => d.province))]

  const latestCostByProvince = provinces.map((prov) => {
    const items = costData.filter((c) => c.province === prov)
    const latest = items[items.length - 1]
    return { province: prov, index: latest?.index ?? 0 }
  }).sort((a, b) => b.index - a.index)

  const barOption = {
    tooltip: { trigger: 'axis' as const },
    grid: { left: 60, right: 20, top: 40, bottom: 40 },
    xAxis: {
      type: 'category' as const,
      data: latestCostByProvince.map((d) => d.province),
      axisLabel: { fontSize: 11, color: '#6B7280' },
      axisLine: { lineStyle: { color: '#E5E7EB' } },
    },
    yAxis: {
      type: 'value' as const,
      axisLabel: { color: '#6B7280' },
      splitLine: { lineStyle: { color: '#F3F4F6' } },
    },
    series: [
      {
        type: 'bar' as const,
        data: latestCostByProvince.map((d) => d.index),
        itemStyle: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
            { offset: 0, color: '#E8722A' },
            { offset: 1, color: '#F5A66B' },
          ]),
          borderRadius: [4, 4, 0, 0],
        },
        barWidth: '50%',
      },
    ],
  }

  const sdProvinces = [...new Set(sdData.map((d) => d.province))].slice(0, 5)
  const sdDates = [...new Set(sdData.map((d) => d.period))].sort().slice(-8)

  const lineOption = {
    tooltip: { trigger: 'axis' as const },
    legend: { data: ['货运需求', '运力供给', '均价'], top: 0, textStyle: { fontSize: 11 } },
    grid: { left: 60, right: 60, top: 40, bottom: 40 },
    xAxis: {
      type: 'category' as const,
      data: sdDates.map((d) => d.substring(5)),
      axisLabel: { color: '#6B7280', fontSize: 11 },
      axisLine: { lineStyle: { color: '#E5E7EB' } },
      boundaryGap: false,
    },
    yAxis: [
      { type: 'value' as const, name: '数量', axisLabel: { color: '#6B7280' }, splitLine: { lineStyle: { color: '#F3F4F6' } } },
      { type: 'value' as const, name: '均价(元)', axisLabel: { color: '#6B7280' }, splitLine: { show: false } },
    ],
    series: [
      {
        name: '货运需求',
        type: 'line' as const,
        data: sdDates.map((d) => sdData.filter((s) => s.period === d).reduce((sum, s) => sum + s.cargo_demand, 0)),
        smooth: true, symbol: 'circle', symbolSize: 4,
        lineStyle: { color: '#E8722A', width: 2 },
        itemStyle: { color: '#E8722A' },
        areaStyle: { color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{ offset: 0, color: 'rgba(232,114,42,0.2)' }, { offset: 1, color: 'rgba(232,114,42,0.02)' }]) },
      },
      {
        name: '运力供给',
        type: 'line' as const,
        data: sdDates.map((d) => sdData.filter((s) => s.period === d).reduce((sum, s) => sum + s.vehicle_supply, 0)),
        smooth: true, symbol: 'circle', symbolSize: 4,
        lineStyle: { color: '#1B2A4A', width: 2 },
        itemStyle: { color: '#1B2A4A' },
        areaStyle: { color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{ offset: 0, color: 'rgba(27,42,74,0.15)' }, { offset: 1, color: 'rgba(27,42,74,0.02)' }]) },
      },
      {
        name: '均价',
        type: 'line' as const, yAxisIndex: 1,
        data: sdDates.map((d) => { const items = sdData.filter((s) => s.period === d); return items.length > 0 ? Math.round(items.reduce((sum, s) => sum + s.avg_price, 0) / items.length) : null }),
        smooth: true, symbol: 'diamond', symbolSize: 4,
        lineStyle: { color: '#7C3AED', width: 2 },
        itemStyle: { color: '#7C3AED' },
      },
    ],
  }

  const latestSdByProvince = [...new Set(sdData.map((d) => d.province))].map((prov) => {
    const items = sdData.filter((s) => s.province === prov)
    const latest = items[items.length - 1]
    return { province: prov, demand: latest?.cargo_demand ?? 0, supply: latest?.vehicle_supply ?? 0, price: latest?.avg_price ?? 0, days: latest?.avg_transit_days ?? 0 }
  }).sort((a, b) => b.demand - a.demand)

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-[#1B2A4A]">数据看板</h2>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {statCards.map((s) => (
          <div key={s.label} className="flex items-center gap-4 rounded-xl bg-white p-5 shadow-sm">
            <div className={`flex h-12 w-12 items-center justify-center rounded-xl ${s.bg}`}>
              <s.icon className="h-6 w-6" style={{ color: s.color }} />
            </div>
            <div>
              <p className="text-sm text-gray-500">{s.label}</p>
              <p className="text-2xl font-bold text-[#1B2A4A]">{s.value}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className="rounded-xl bg-white p-6 shadow-sm">
          <h3 className="mb-4 flex items-center gap-2 text-base font-semibold text-[#1B2A4A]">
            <TrendingUp className="h-4 w-4 text-[#E8722A]" />
            区域物流成本指数（最新月度）
          </h3>
          <ReactEChartsCore echarts={echarts} option={barOption} style={{ height: 320 }} />
        </div>
        <div className="rounded-xl bg-white p-6 shadow-sm">
          <h3 className="mb-4 flex items-center gap-2 text-base font-semibold text-[#1B2A4A]">
            <TrendingDown className="h-4 w-4 text-[#1B2A4A]" />
            运力供需趋势与均价
          </h3>
          <ReactEChartsCore echarts={echarts} option={lineOption} style={{ height: 320 }} />
        </div>
      </div>

      <div className="rounded-xl bg-white p-6 shadow-sm">
        <h3 className="mb-4 text-base font-semibold text-[#1B2A4A]">各省供需比与均价概览</h3>
        {latestSdByProvince.length === 0 ? (
          <div className="py-12 text-center text-gray-400">暂无数据</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-[#F5F6FA]">
                  <th className="px-4 py-3 text-left font-medium text-[#1B2A4A]">省份</th>
                  <th className="px-4 py-3 text-left font-medium text-[#1B2A4A]">货运需求</th>
                  <th className="px-4 py-3 text-left font-medium text-[#1B2A4A]">运力供给</th>
                  <th className="px-4 py-3 text-left font-medium text-[#1B2A4A]">供需比</th>
                  <th className="px-4 py-3 text-left font-medium text-[#1B2A4A]">均价(元)</th>
                  <th className="px-4 py-3 text-left font-medium text-[#1B2A4A]">平均时效(天)</th>
                </tr>
              </thead>
              <tbody>
                {latestSdByProvince.map((d, i) => {
                  const ratio = d.supply > 0 ? (d.demand / d.supply).toFixed(2) : '-'
                  const ratioNum = parseFloat(ratio as string)
                  return (
                    <tr key={i} className="border-b border-gray-50 hover:bg-gray-50/50">
                      <td className="px-4 py-3 text-gray-700 font-medium">{d.province}</td>
                      <td className="px-4 py-3 text-[#E8722A] font-medium">{d.demand.toLocaleString()}</td>
                      <td className="px-4 py-3 text-[#1B2A4A] font-medium">{d.supply.toLocaleString()}</td>
                      <td className="px-4 py-3">
                        <span className={`inline-block rounded-full px-2.5 py-0.5 text-xs font-medium ${isNaN(ratioNum) || ratioNum <= 1 ? 'bg-red-100 text-red-600' : ratioNum <= 1.5 ? 'bg-orange-100 text-[#E8722A]' : 'bg-green-100 text-green-600'}`}>
                          {ratio}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-gray-700">¥{d.price.toFixed(0)}</td>
                      <td className="px-4 py-3 text-gray-700">{d.days}天</td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
