// frontend/src/views/Exceptions.vue
<template>
  <div class="exceptions">
    <div class="page-header">
      <h2>异常处理</h2>
    </div>
    
    <el-card>
      <el-form :inline="true" class="filter-form">
        <el-form-item label="处理状态">
          <el-select v-model="filters.handled" placeholder="全部" clearable>
            <el-option label="待处理" :value="false" />
            <el-option label="已处理" :value="true" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="loadData">查询</el-button>
          <el-button @click="resetFilters">重置</el-button>
        </el-form-item>
      </el-form>
      
      <el-table :data="list" v-loading="loading">
        <el-table-column prop="id" label="异常ID" width="160" />
        <el-table-column prop="config_name" label="配置名称" width="150" />
        <el-table-column prop="app_name" label="应用" width="120" />
        <el-table-column prop="error_type" label="错误类型" width="150">
          <template #default="{ row }">
            <el-tag type="danger" size="small">{{ row.error_type }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="error_message" label="错误信息" show-overflow-tooltip min-width="200" />
        <el-table-column prop="handled" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.handled ? 'success' : 'warning'" size="small">
              {{ row.handled ? '已处理' : '待处理' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="发生时间" width="180">
          <template #default="{ row }">{{ formatTime(row.created_at) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="150" fixed="right">
          <template #default="{ row }">
            <el-button size="small" type="primary" link @click="handleException(row)">
              {{ row.handled ? '查看' : '处理' }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
    
    <el-dialog v-model="showHandleDialog" title="处理异常" width="700px">
      <div v-if="currentException">
        <el-descriptions :column="2" size="small" border>
          <el-descriptions-item label="异常ID">{{ currentException.id }}</el-descriptions-item>
          <el-descriptions-item label="错误类型">{{ currentException.error_type }}</el-descriptions-item>
          <el-descriptions-item label="错误信息" :span="2">{{ currentException.error_message }}</el-descriptions-item>
        </el-descriptions>
        
        <el-divider>原始请求</el-divider>
        <pre class="json-preview">{{ currentException.original_request || '{}' }}</pre>
        
        <el-divider>处理信息</el-divider>
        <el-form label-width="100px">
          <el-form-item label="补偿动作">
            <el-input v-model="handleForm.compensation_action" type="textarea" :rows="3" placeholder="记录补偿措施" />
          </el-form-item>
          <el-form-item label="人工备注">
            <el-input v-model="handleForm.manual_remark" type="textarea" :rows="3" placeholder="备注说明" />
          </el-form-item>
        </el-form>
      </div>
      <template #footer>
        <el-button @click="showHandleDialog = false">关闭</el-button>
        <el-button type="primary" @click="submitHandle" :disabled="currentException?.handled">
          标记已处理
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted, reactive } from 'vue'
import { ElMessage } from 'element-plus'
import { audit } from '@/api'

const list = ref([])
const loading = ref(false)
const showHandleDialog = ref(false)
const currentException = ref(null)

const filters = reactive({
  handled: ''
})

const handleForm = reactive({
  compensation_action: '',
  manual_remark: ''
})

const formatTime = (t) => t ? new Date(t).toLocaleString() : '-'

const loadData = async () => {
  loading.value = true
  try {
    const params = {}
    if (filters.handled !== '') {
      params.handled = filters.handled
    }
    const result = await audit.exceptions(params)
    list.value = result.exceptions || []
  } catch (e) {
    ElMessage.error('加载失败')
  } finally {
    loading.value = false
  }
}

const resetFilters = () => {
  filters.handled = ''
  loadData()
}

const handleException = (row) => {
  currentException.value = row
  handleForm.compensation_action = row.compensation_action || ''
  handleForm.manual_remark = row.manual_remark || ''
  showHandleDialog.value = true
}

const submitHandle = async () => {
  try {
    await audit.handleException(currentException.value.id, handleForm)
    ElMessage.success('处理成功')
    showHandleDialog.value = false
    loadData()
  } catch (e) {
    ElMessage.error(e.error || '处理失败')
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.page-header {
  margin-bottom: 20px;
}

.page-header h2 {
  margin: 0;
  font-size: 24px;
}

.filter-form {
  margin-bottom: 20px;
}

.json-preview {
  background: #1e293b;
  color: #e2e8f0;
  padding: 16px;
  border-radius: 8px;
  margin: 0;
  white-space: pre-wrap;
  max-height: 200px;
  overflow: auto;
  font-size: 12px;
}
</style>

// frontend/src/pages/Exceptions.jsx
import React, { useState, useEffect } from 'react';
import { Table, Card, Select, Form, Button, message, Tag, Modal, Descriptions, Input, Row, Col, Statistic } from 'antd';
import { SearchOutlined, EyeOutlined, CheckCircleOutlined, WarningOutlined } from '@ant-design/icons';
import { exceptionsApi } from '../utils/api';
import dayjs from 'dayjs';

const { TextArea } = Input;

function Exceptions() {
  const [data, setData] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [stats, setStats] = useState({ pending: 0, resolved: 0 });
  const [detailModalVisible, setDetailModalVisible] = useState(false);
  const [resolveModalVisible, setResolveModalVisible] = useState(false);
  const [detailData, setDetailData] = useState(null);
  const [filters, setFilters] = useState({
    page: 1,
    pageSize: 20,
    operation: '',
    error_type: '',
    status: ''
  });

  useEffect(() => {
    loadStats();
    loadData();
  }, [filters]);

  const loadStats = async () => {
    try {
      const res = await exceptionsApi.getStats();
      setStats(res.data);
    } catch (error) {
      console.error(error);
    }
  };

  const loadData = async () => {
    setLoading(true);
    try {
      const res = await exceptionsApi.getList(filters);
      setData(res.data.list);
      setTotal(res.data.total);
    } catch (error) {
      message.error('加载数据失败');
    } finally {
      setLoading(false);
    }
  };

  const showDetail = async (id) => {
    try {
      const res = await exceptionsApi.getDetail(id);
      setDetailData(res.data);
      setDetailModalVisible(true);
    } catch (error) {
      message.error('加载详情失败');
    }
  };

  const showResolve = (record) => {
    setDetailData(record);
    setResolveModalVisible(true);
  };

  const handleResolve = async (values) => {
    try {
      await exceptionsApi.resolve(detailData.id, values);
      message.success('处理完成');
      setResolveModalVisible(false);
      loadData();
      loadStats();
    } catch (error) {
      message.error('处理失败');
    }
  };

  const errorTypeOptions = [
    { value: 'pdf_parse_failure', label: 'PDF解析失败' },
    { value: 'version_conflict', label: '版本冲突' },
    { value: 'missing_answers', label: '评分项漏答' },
    { value: 'database', label: '数据库错误' },
    { value: 'upload', label: '上传错误' },
    { value: 'network', label: '网络错误' }
  ];

  const columns = [
    { title: '操作', dataIndex: 'operation', width: 120 },
    { title: '错误类型', dataIndex: 'error_type', width: 150,
      render: (v) => errorTypeOptions.find(o => o.value === v)?.label || v
    },
    { title: '错误信息', dataIndex: 'error_message' },
    { title: '标书', dataIndex: 'project_name', width: 180,
      render: (v, r) => v || r.bid_no || '-'
    },
    { title: '操作人', dataIndex: 'operator_name', width: 100 },
    { title: '状态', dataIndex: 'status', width: 100,
      render: (v) => (
        <Tag color={v === 'resolved' ? 'green' : 'orange'}>{v}</Tag>
      )
    },
    { title: '创建时间', dataIndex: 'created_at', width: 170,
      render: (t) => dayjs(t).format('YYYY-MM-DD HH:mm')
    },
    { title: '操作', width: 150,
      render: (_, record) => (
        <div>
          <Button type="link" size="small" icon={<EyeOutlined />} onClick={() => showDetail(record.id)}>详情</Button>
          {record.status === 'pending' && (
            <Button type="link" size="small" onClick={() => showResolve(record)}>处理</Button>
          )}
        </div>
      )
    }
  ];

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">异常处理</h1>
      </div>

      <Row gutter={16} style={{ marginBottom: 16 }}>
        <Col span={12}>
          <Card size="small">
            <Statistic 
              title="待处理异常" 
              value={stats.pending} 
              valueStyle={{ color: '#faad14' }}
              prefix={<WarningOutlined />}
            />
          </Card>
        </Col>
        <Col span={12}>
          <Card size="small">
            <Statistic 
              title="已处理" 
              value={stats.resolved}
              valueStyle={{ color: '#52c41a' }}
              prefix={<CheckCircleOutlined />}
            />
          </Card>
        </Col>
      </Row>

      <Card style={{ marginBottom: 16 }}>
        <Form layout="inline">
          <Form.Item label="错误类型">
            <Select 
              style={{ width: 150 }} 
              allowClear 
              placeholder="全部"
              onChange={(v) => setFilters({ ...filters, error_type: v, page: 1 })}
            >
              {errorTypeOptions.map(o => (
                <Select.Option key={o.value} value={o.value}>{o.label}</Select.Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item label="状态">
            <Select 
              style={{ width: 120 }} 
              allowClear 
              placeholder="全部"
              onChange={(v) => setFilters({ ...filters, status: v, page: 1 })}
            >
              <Select.Option value="pending">待处理</Select.Option>
              <Select.Option value="resolved">已处理</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item>
            <Button type="primary" icon={<SearchOutlined />} onClick={loadData}>搜索</Button>
          </Form.Item>
        </Form>
      </Card>

      <Card>
        <Table
          loading={loading}
          columns={columns}
          dataSource={data}
          rowKey="id"
          pagination={{
            current: filters.page,
            pageSize: filters.pageSize,
            total,
            onChange: (page, pageSize) => setFilters({ ...filters, page, pageSize })
          }}
        />
      </Card>

      <Modal
        title="异常详情"
        open={detailModalVisible}
        onCancel={() => setDetailModalVisible(false)}
        footer={null}
        width={700}
      >
        {detailData && (
          <div>
            <Descriptions column={2} size="small" bordered>
              <Descriptions.Item label="操作" span={2}>{detailData.operation}</Descriptions.Item>
              <Descriptions.Item label="错误类型">
                {errorTypeOptions.find(o => o.value === detailData.error_type)?.label || detailData.error_type}
              </Descriptions.Item>
              <Descriptions.Item label="状态">
                <Tag color={detailData.status === 'resolved' ? 'green' : 'orange'}>{detailData.status}</Tag>
              </Descriptions.Item>
              <Descriptions.Item label="标书" span={2}>{detailData.project_name || detailData.bid_no || '-'}</Descriptions.Item>
              <Descriptions.Item label="操作人">{detailData.operator_name || '-'}</Descriptions.Item>
              <Descriptions.Item label="创建时间">{dayjs(detailData.created_at).format('YYYY-MM-DD HH:mm:ss')}</Descriptions.Item>
              <Descriptions.Item label="错误信息" span={2}>{detailData.error_message || '-'}</Descriptions.Item>
              <Descriptions.Item label="补偿动作" span={2}>{detailData.compensation_action || '-'}</Descriptions.Item>
              <Descriptions.Item label="人工备注" span={2}>{detailData.manual_remark || '-'}</Descriptions.Item>
            </Descriptions>
            {detailData.request_data && (
              <div style={{ marginTop: 16 }}>
                <h4>原始请求</h4>
                <pre style={{ background: '#f5f5f5', padding: 12, borderRadius: 4, fontSize: 12, maxHeight: 200, overflow: 'auto' }}>
                  {JSON.stringify(detailData.request_data, null, 2)}
                </pre>
              </div>
            )}
          </div>
        )}
      </Modal>

      <Modal
        title="处理异常"
        open={resolveModalVisible}
        onCancel={() => setResolveModalVisible(false)}
        footer={null}
      >
        <Form layout="vertical" onFinish={handleResolve}>
          <Form.Item label="补偿动作" name="compensation_action">
            <TextArea rows={3} placeholder="描述采取的补偿动作" />
          </Form.Item>
          <Form.Item label="人工备注" name="manual_remark">
            <TextArea rows={3} placeholder="记录处理备注" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" block>确认处理</Button>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}

export default Exceptions;
