// frontend/src/views/messages/index.vue
<template>
  <div class="messages-page page-container">
    <van-nav-bar title="消息" />
    
    <div v-if="loading" class="loading-container">
      <van-loading type="spinner" size="32px">加载中...</van-loading>
    </div>
    
    <div v-else-if="conversations.length === 0" class="empty-container">
      <van-empty description="暂无消息" />
    </div>
    
    <div v-else class="conversation-list">
      <div
        v-for="item in conversations"
        :key="item.user_id"
        class="conversation-item card flex"
        @click="goChat(item.user_id)"
      >
        <img :src="item.avatar" class="avatar" />
        <div class="conversation-info flex-1 ml-12">
          <div class="flex-between">
            <span class="nickname">{{ item.nickname }}</span>
            <span class="time text-gray">{{ formatTime(item.last_message_time) }}</span>
          </div>
          <div class="last-message text-gray ellipsis mt-4">{{ item.last_message }}</div>
        </div>
        <van-badge v-if="item.unread_count > 0" :content="item.unread_count" class="badge" />
      </div>
    </div>
    
    <TabBar />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import request from '@/utils/request'
import TabBar from '@/components/TabBar.vue'

const router = useRouter()

const loading = ref(true)
const conversations = ref([])

const fetchConversations = async () => {
  try {
    const res = await request.get('/messages/conversations')
    conversations.value = res.data || []
  } catch (error) {
    console.error('获取会话列表失败:', error)
  } finally {
    loading.value = false
  }
}

const formatTime = (time) => {
  if (!time) return ''
  const date = new Date(time)
  const now = new Date()
  const diff = now - date
  
  if (diff < 60000) return '刚刚'
  if (diff < 3600000) return `${Math.floor(diff / 60000)}分钟前`
  if (diff < 86400000) return `${Math.floor(diff / 3600000)}小时前`
  return `${date.getMonth() + 1}/${date.getDate()}`
}

const goChat = (userId) => {
  router.push(`/messages/${userId}`)
}

onMounted(() => {
  fetchConversations()
})
</script>

<style scoped>
.messages-page {
  padding-bottom: 50px;
}

.loading-container,
.empty-container {
  padding: 60px 20px;
  text-align: center;
}

.conversation-list {
  padding: 8px;
}

.conversation-item {
  margin-bottom: 8px;
  padding: 12px;
  align-items: center;
  position: relative;
}

.avatar {
  width: 48px;
  height: 48px;
  border-radius: 50%;
}

.nickname {
  font-size: 15px;
  font-weight: 500;
}

.time {
  font-size: 12px;
}

.last-message {
  font-size: 13px;
}

.badge {
  position: absolute;
  top: 12px;
  right: 12px;
}

.mt-4 {
  margin-top: 4px;
}

.ml-12 {
  margin-left: 12px;
}
</style>

// frontend/src/pages/Messages.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { MessageCircle } from 'lucide-react';
import api, { handleApiError } from '../services/api';
import Loading from '../components/Loading';
import { showToast } from '../components/Toast';

interface Conversation {
  user_id: number;
  nickname: string;
  avatar: string;
  last_message: string;
  last_message_time: string;
  unread_count: number;
}

const Messages: React.FC = () => {
  const navigate = useNavigate();
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchConversations();
  }, []);

  const fetchConversations = async () => {
    try {
      const res = await api.get('/messages/conversations');
      if (res.data.success) {
        setConversations(res.data.data.conversations || []);
      }
    } catch (error) {
      showToast(handleApiError(error), 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      <div className="bg-white sticky top-0 z-20 shadow-sm">
        <div className="px-4 pt-8 pb-4">
          <h1 className="text-xl font-bold text-gray-800">消息</h1>
        </div>
      </div>

      <div className="p-4">
        {loading ? (
          <Loading />
        ) : conversations.length === 0 ? (
          <div className="text-center py-16 text-gray-500">
            <MessageCircle size={48} className="mx-auto mb-3 opacity-50" />
            <p className="mb-2">暂无消息</p>
            <p className="text-sm">去星球匹配有趣的人吧</p>
          </div>
        ) : (
          <div className="space-y-1">
            {conversations.map((conv) => (
              <button
                key={conv.user_id}
                onClick={() => navigate(`/chat/${conv.user_id}`)}
                className="w-full flex items-center gap-3 p-3 bg-white rounded-xl shadow-sm hover:bg-gray-50"
              >
                <img
                  src={conv.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${conv.user_id}`}
                  alt=""
                  className="w-12 h-12 rounded-full object-cover"
                />
                <div className="flex-1 text-left">
                  <div className="flex items-center justify-between">
                    <span className="font-medium text-gray-800">{conv.nickname}</span>
                    {conv.unread_count > 0 && (
                      <span className="w-5 h-5 bg-pink-500 text-white text-xs rounded-full flex items-center justify-center">
                        {conv.unread_count}
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-gray-500 truncate">{conv.last_message || '暂无消息'}</p>
                </div>
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Messages;
