// frontend/src/views/Projects.vue
<template>
  <div class="page-container">
    <div class="page-header" style="display: flex; justify-content: space-between; align-items: center;">
      <div>
        <h1 class="page-title">项目档案</h1>
        <p class="page-subtitle">管理科研项目基本信息</p>
      </div>
      <el-button type="primary" @click="openDialog">
        <el-icon><Plus /></el-icon>
        新建项目
      </el-button>
    </div>

    <div class="card">
      <el-table :data="projects" border stripe>
        <el-table-column prop="project_no" label="项目编号" width="120" />
        <el-table-column prop="name" label="项目名称" min-width="200" />
        <el-table-column prop="source" label="项目来源" width="140" />
        <el-table-column prop="principal" label="负责人" width="100" />
        <el-table-column prop="department" label="所属部门" width="120" />
        <el-table-column label="周期" width="220">
          <template #default="{ row }">
            {{ row.start_date }} 至 {{ row.end_date }}
          </template>
        </el-table-column>
        <el-table-column prop="total_budget" label="总预算" width="120">
          <template #default="{ row }">
            ¥{{ formatMoney(row.total_budget) }}
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="getStatusType(row.status)">
              {{ getStatusText(row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="150" fixed="right">
          <template #default="{ row }">
            <div class="table-actions">
              <el-button size="small" @click="viewBudget(row)">预算</el-button>
              <el-button size="small" @click="editProject(row)">编辑</el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </div>

    <el-dialog v-model="dialogVisible" :title="isEdit ? '编辑项目' : '新建项目'" width="600px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="项目编号">
          <el-input v-model="form.project_no" />
        </el-form-item>
        <el-form-item label="项目名称">
          <el-input v-model="form.name" />
        </el-form-item>
        <el-form-item label="项目来源">
          <el-input v-model="form.source" />
        </el-form-item>
        <el-form-item label="负责人">
          <el-input v-model="form.principal" />
        </el-form-item>
        <el-form-item label="所属部门">
          <el-input v-model="form.department" />
        </el-form-item>
        <el-form-item label="开始日期">
          <el-date-picker v-model="form.start_date" type="date" style="width: 100%;" />
        </el-form-item>
        <el-form-item label="结束日期">
          <el-date-picker v-model="form.end_date" type="date" style="width: 100%;" />
        </el-form-item>
        <el-form-item label="总预算">
          <el-input-number v-model="form.total_budget" :min="0" style="width: 100%;" />
        </el-form-item>
        <el-form-item label="状态" v-if="isEdit">
          <el-select v-model="form.status" style="width: 100%;">
            <el-option label="进行中" value="active" />
            <el-option label="已完成" value="completed" />
            <el-option label="已暂停" value="suspended" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="saveProject">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { getProjects, createProject, updateProject } from '../api'
import { Plus } from '@element-plus/icons-vue'

const router = useRouter()
const projects = ref([])
const dialogVisible = ref(false)
const isEdit = ref(false)
const form = ref({
  project_no: '',
  name: '',
  source: '',
  principal: '',
  department: '',
  start_date: '',
  end_date: '',
  total_budget: 0,
  status: 'active'
})

const formatMoney = (value) => {
  if (!value) return '0.00'
  return Number(value).toLocaleString('zh-CN', { minimumFractionDigits: 2 })
}

const getStatusType = (status) => {
  const map = { active: 'success', completed: 'info', suspended: 'warning' }
  return map[status] || 'info'
}

const getStatusText = (status) => {
  const map = { active: '进行中', completed: '已完成', suspended: '已暂停' }
  return map[status] || status
}

const loadProjects = async () => {
  try {
    const res = await getProjects()
    projects.value = res.data
  } catch (error) {
    ElMessage.error('加载项目列表失败')
  }
}

const openDialog = () => {
  isEdit.value = false
  form.value = {
    project_no: '',
    name: '',
    source: '',
    principal: '',
    department: '',
    start_date: '',
    end_date: '',
    total_budget: 0,
    status: 'active'
  }
  dialogVisible.value = true
}

const editProject = (row) => {
  isEdit.value = true
  form.value = { ...row }
  dialogVisible.value = true
}

const saveProject = async () => {
  try {
    if (isEdit.value) {
      await updateProject(form.value.id, form.value)
      ElMessage.success('更新成功')
    } else {
      await createProject(form.value)
      ElMessage.success('创建成功')
    }
    dialogVisible.value = false
    loadProjects()
  } catch (error) {
    ElMessage.error(error.response?.data?.error || '保存失败')
  }
}

const viewBudget = (row) => {
  router.push(`/budget?projectId=${row.id}`)
}

onMounted(() => {
  loadProjects()
})
</script>

// frontend/src/pages/Projects.jsx
import React, { useState, useEffect } from 'react';
import { Table, Button, Modal, Form, Input, Select, DatePicker, Space, message, Tag } from 'antd';
import { PlusOutlined, EyeOutlined, EditOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import dayjs from 'dayjs';
import api from '../services/api.js';

const { Option } = Select;
const { TextArea } = Input;

export default function Projects() {
  const [projects, setProjects] = useState([]);
  const [modalVisible, setModalVisible] = useState(false);
  const [editingProject, setEditingProject] = useState(null);
  const [form] = Form.useForm();
  const navigate = useNavigate();

  useEffect(() => {
    loadProjects();
  }, []);

  const loadProjects = async () => {
    try {
      const response = await api.get('/projects');
      setProjects(response.data || []);
    } catch (error) {
      message.error('加载项目列表失败');
    }
  };

  const handleAdd = () => {
    setEditingProject(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleEdit = (record) => {
    setEditingProject(record);
    form.setFieldsValue({
      ...record,
      start_date: record.start_date ? dayjs(record.start_date) : null,
      end_date: record.end_date ? dayjs(record.end_date) : null
    });
    setModalVisible(true);
  };

  const handleSubmit = async (values) => {
    try {
      const data = {
        ...values,
        start_date: values.start_date ? values.start_date.format('YYYY-MM-DD') : null,
        end_date: values.end_date ? values.end_date.format('YYYY-MM-DD') : null
      };

      if (editingProject) {
        await api.put(`/projects/${editingProject.id}`, data);
        message.success('更新成功');
      } else {
        await api.post('/projects', data);
        message.success('创建成功');
      }
      setModalVisible(false);
      loadProjects();
    } catch (error) {
      message.error(error.response?.data?.error || '操作失败');
    }
  };

  const columns = [
    { title: '项目编号', dataIndex: 'project_no', key: 'project_no', width: 120 },
    { title: '项目名称', dataIndex: 'name', key: 'name' },
    { title: '主要研究者', dataIndex: 'principal_investigator', key: 'pi', width: 120 },
    { 
      title: '状态', 
      dataIndex: 'status', 
      key: 'status',
      width: 100,
      render: (status) => {
        const statusMap = {
          draft: { color: 'default', text: '草稿' },
          approved: { color: 'blue', text: '已批准' },
          recruiting: { color: 'green', text: '招募中' },
          ongoing: { color: 'processing', text: '进行中' },
          completed: { color: 'success', text: '已完成' },
          suspended: { color: 'warning', text: '已暂停' }
        };
        const s = statusMap[status] || { color: 'default', text: status };
        return <Tag color={s.color}>{s.text}</Tag>;
      }
    },
    { title: '目标样本量', dataIndex: 'target_sample_size', key: 'target', width: 100 },
    { title: '已入组', dataIndex: 'actual_sample_size', key: 'actual', width: 100 },
    { title: '创建时间', dataIndex: 'created_at', key: 'created_at', width: 180 },
    {
      title: '操作',
      key: 'action',
      width: 180,
      render: (_, record) => (
        <Space>
          <Button type="link" icon={<EyeOutlined />} onClick={() => navigate(`/projects/${record.id}`)}>
            详情
          </Button>
          <Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(record)}>
            编辑
          </Button>
        </Space>
      )
    }
  ];

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
        <h2>研究项目管理</h2>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
          新建项目
        </Button>
      </div>

      <Table
        dataSource={projects}
        columns={columns}
        rowKey="id"
        pagination={{ pageSize: 10 }}
      />

      <Modal
        title={editingProject ? '编辑项目' : '新建项目'}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
        width={600}
      >
        <Form form={form} layout="vertical" onFinish={handleSubmit}>
          <Form.Item name="project_no" label="项目编号" rules={[{ required: true }]}>
            <Input placeholder="请输入项目编号" />
          </Form.Item>
          <Form.Item name="name" label="项目名称" rules={[{ required: true }]}>
            <Input placeholder="请输入项目名称" />
          </Form.Item>
          <Form.Item name="principal_investigator" label="主要研究者">
            <Input placeholder="请输入主要研究者姓名" />
          </Form.Item>
          <Form.Item name="description" label="项目描述">
            <TextArea rows={3} placeholder="请输入项目描述" />
          </Form.Item>
          <Form.Item name="status" label="状态" initialValue="draft">
            <Select>
              <Option value="draft">草稿</Option>
              <Option value="approved">已批准</Option>
              <Option value="recruiting">招募中</Option>
              <Option value="ongoing">进行中</Option>
              <Option value="completed">已完成</Option>
              <Option value="suspended">已暂停</Option>
            </Select>
          </Form.Item>
          <Form.Item name="target_sample_size" label="目标样本量">
            <Input type="number" placeholder="请输入目标样本量" />
          </Form.Item>
          <Form.Item name="start_date" label="开始日期">
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item name="end_date" label="结束日期">
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit">
                提交
              </Button>
              <Button onClick={() => setModalVisible(false)}>取消</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
