// frontend/src/views/Register.vue
<template>
  <div class="login">
    <el-card class="login-card">
      <h2>会员注册</h2>
      <el-form :model="form" label-width="80px" @submit.prevent="submit">
        <el-form-item label="手机号">
          <el-input v-model="form.phone" placeholder="请输入手机号" />
        </el-form-item>
        <el-form-item label="姓名">
          <el-input v-model="form.name" placeholder="请输入姓名（选填）" />
        </el-form-item>
        <el-form-item label="密码">
          <el-input v-model="form.password" type="password" placeholder="请输入密码" show-password />
        </el-form-item>
        <el-form-item label="确认密码">
          <el-input v-model="form.confirmPassword" type="password" placeholder="请确认密码" show-password />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" native-type="submit" style="width:100%">注册</el-button>
        </el-form-item>
      </el-form>
      <p>已有账号？<el-button type="primary" link @click="$router.push('/login?type=member')">立即登录</el-button></p>
    </el-card>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { auth } from '../api'
import { useUserStore } from '../utils/userStore'

const router = useRouter()
const { updateUser } = useUserStore()
const form = ref({ phone: '', name: '', password: '', confirmPassword: '' })

const submit = async () => {
  if (!form.value.phone) return ElMessage.warning('请输入手机号')
  if (!/^1[3-9]\d{9}$/.test(form.value.phone)) return ElMessage.warning('手机号格式不正确')
  if (!form.value.password) return ElMessage.warning('请输入密码')
  if (form.value.password !== form.value.confirmPassword) return ElMessage.warning('两次密码不一致')
  try {
    const res = await auth.memberRegister(form.value)
    localStorage.setItem('token', res.token)
    localStorage.setItem('userType', 'member')
    updateUser(res.member)
    ElMessage.success('注册成功，已自动登录')
    router.push('/member/dashboard')
  } catch (e) {
    ElMessage.error(e.error || e.message || '注册失败')
  }
}
</script>

<style scoped>
.login { min-height: 100vh; display: flex; align-items: center; justify-content: center; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
.login-card { width: 420px; }
.login-card h2 { text-align: center; margin-bottom: 20px; }
</style>

// frontend-user/src/pages/Register.tsx
import { useState } from 'react';
import { useNavigate, useSearchParams, Link } from 'react-router-dom';
import { authApi } from '../api/modules';
import { useToast, useUser } from '../App';

export default function Register() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const toast = useToast();
  const { setUser } = useUser();
  const [form, setForm] = useState({
    phone: '',
    password: '',
    confirmPassword: '',
    nickname: '',
    referrerCode: params.get('ref') || ''
  });
  const [loading, setLoading] = useState(false);

  const submit = async () => {
    if (!form.phone || !form.password) return toast.show('请填写手机号和密码', 'error');
    if (form.password !== form.confirmPassword) return toast.show('两次密码不一致', 'error');
    if (!/^1\d{10}$/.test(form.phone)) return toast.show('手机号格式错误', 'error');
    if (form.password.length < 6) return toast.show('密码长度至少6位', 'error');

    setLoading(true);
    try {
      const res: any = await authApi.register({
        phone: form.phone,
        password: form.password,
        nickname: form.nickname,
        referrerCode: form.referrerCode
      });
      if (res.success) {
        localStorage.setItem('user_token', res.data.token);
        localStorage.setItem('user_info', JSON.stringify(res.data.user));
        setUser(res.data.user);
        toast.show('注册成功', 'success');
        setTimeout(() => navigate('/'), 500);
      }
    } catch (e: any) {
      toast.show(e.message || '注册失败', 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' }}>
      <div style={{ padding: '80px 24px 24px' }}>
        <div style={{ color: 'white', marginBottom: 40 }}>
          <div style={{ fontSize: 32, fontWeight: 700, marginBottom: 8 }}>创建账号 🎉</div>
          <div style={{ opacity: 0.85 }}>立即加入，享受首单优惠和分享赚钱</div>
        </div>

        <div className="card" style={{ margin: 0 }}>
          <div className="form-group">
            <label className="form-label">手机号</label>
            <input className="form-input" placeholder="请输入手机号"
              value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} />
          </div>
          <div className="form-group">
            <label className="form-label">昵称（选填）</label>
            <input className="form-input" placeholder="给您起个好听的名字吧"
              value={form.nickname} onChange={e => setForm({ ...form, nickname: e.target.value })} />
          </div>
          <div className="form-group">
            <label className="form-label">密码</label>
            <input className="form-input" type="password" placeholder="至少6位"
              value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} />
          </div>
          <div className="form-group">
            <label className="form-label">确认密码</label>
            <input className="form-input" type="password" placeholder="再次输入密码"
              value={form.confirmPassword} onChange={e => setForm({ ...form, confirmPassword: e.target.value })} />
          </div>
          <div className="form-group">
            <label className="form-label">邀请码（选填）</label>
            <input className="form-input" placeholder="填写可获得额外奖励"
              value={form.referrerCode} onChange={e => setForm({ ...form, referrerCode: e.target.value })} />
          </div>

          <button className="btn-danger btn-block mt-16" onClick={submit} disabled={loading}>
            {loading ? '注册中...' : '立即注册'}
          </button>

          <div style={{ marginTop: 16, textAlign: 'center', color: '#666', fontSize: 13 }}>
            已有账号？<Link to="/login" style={{ color: '#ee5a6f', fontWeight: 600 }}>立即登录</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
