// frontend/src/views/user/Notifications.vue
<template>
  <div class="notifications">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>通知中心</span>
          <el-button type="primary" size="small" @click="markAllRead" v-if="unreadCount > 0">
            全部已读
          </el-button>
        </div>
      </template>

      <el-empty v-if="notifications.length === 0" description="暂无通知" />

      <el-timeline v-else>
        <el-timeline-item
          v-for="item in notifications"
          :key="item.id"
          :timestamp="formatDateTime(item.created_at)"
          placement="top"
          :type="item.is_read ? 'info' : 'primary'"
        >
          <el-card :class="{ 'unread-card': !item.is_read }">
            <div class="notification-header">
              <span class="notification-title" :class="{ 'unread-title': !item.is_read }">
                {{ item.title }}
              </span>
              <el-tag v-if="!item.is_read" type="danger" size="small">新</el-tag>
            </div>
            <div class="notification-message">
              {{ item.message }}
            </div>
            <div class="notification-actions">
              <el-button type="text" size="small" @click="markAsRead(item)" v-if="!item.is_read">
                标记已读
              </el-button>
            </div>
          </el-card>
        </el-timeline-item>
      </el-timeline>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { apiClient } from '@/api'
import type { NotificationResponse } from '@/types'
import dayjs from 'dayjs'

const notifications = ref<NotificationResponse[]>([])

const unreadCount = computed(() => {
  return notifications.value.filter((n) => !n.is_read).length
})

const formatDateTime = (dateStr: string) => {
  return dayjs(dateStr).format('YYYY-MM-DD HH:mm')
}

const fetchNotifications = async () => {
  try {
    const response = await apiClient.get<NotificationResponse[]>('/users/me/notifications')
    notifications.value = response.data
  } catch (error) {
    console.error('Failed to fetch notifications:', error)
  }
}

const markAsRead = async (item: NotificationResponse) => {
  try {
    await apiClient.post(`/notifications/${item.id}/read`)
    item.is_read = true
    ElMessage.success('已标记为已读')
  } catch (error) {
    console.error('Failed to mark as read:', error)
  }
}

const markAllRead = async () => {
  try {
    const unreadItems = notifications.value.filter((n) => !n.is_read)
    for (const item of unreadItems) {
      await apiClient.post(`/notifications/${item.id}/read`)
      item.is_read = true
    }
    ElMessage.success('已全部标记为已读')
  } catch (error) {
    console.error('Failed to mark all as read:', error)
  }
}

onMounted(() => {
  fetchNotifications()
})
</script>

<style scoped>
.notifications {
  padding: 0;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.unread-card {
  border-left: 4px solid #409EFF;
}

.notification-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.notification-title {
  font-weight: bold;
  font-size: 14px;
  color: #303133;
}

.unread-title {
  color: #409EFF;
}

.notification-message {
  font-size: 14px;
  color: #606266;
  margin-bottom: 8px;
}

.notification-actions {
  display: flex;
  justify-content: flex-end;
}
</style>

// web/src/pages/Notifications.jsx
import React, { useState, useEffect } from 'react';
import { Card, List, Tabs, Button, Badge, Spin, Tag, Empty, message } from 'antd';
import { BellOutlined, CheckOutlined, FileTextOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { notifications as notifApi } from '../api';
import dayjs from 'dayjs';

const typeIconMap = {
  case: <FileTextOutlined style={{ color: '#1890ff' }} />,
  certificate: <SafetyCertificateOutlined style={{ color: '#722ed1' }} />,
  system: <BellOutlined style={{ color: '#fa8c16' }} />,
};

const typeRouteMap = {
  case: '/cases',
  certificate: '/certificates',
};

export default function Notifications() {
  const [activeTab, setActiveTab] = useState('unread');
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [unreadCount, setUnreadCount] = useState(0);
  const navigate = useNavigate();

  useEffect(() => {
    fetchData();
  }, [activeTab]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const params = {};
      if (activeTab === 'unread') params.is_read = false;
      const res = await notifApi.getNotifications(params);
      const d = res.data?.data || res.data || {};
      const items = d.items || d.list || [];
      setData(items);
      if (activeTab === 'unread') {
        setUnreadCount(items.length);
      }
    } catch {
      message.error('获取通知列表失败');
    } finally {
      setLoading(false);
    }
  };

  const handleMarkRead = async (id) => {
    try {
      await notifApi.markRead(id);
      fetchData();
    } catch {
      message.error('操作失败');
    }
  };

  const handleMarkAllRead = async () => {
    try {
      await notifApi.markAllRead();
      message.success('全部已读');
      fetchData();
    } catch {
      message.error('操作失败');
    }
  };

  const handleClick = (item) => {
    if (!item.is_read) {
      notifApi.markRead(item.id).catch(() => {});
    }
    const route = typeRouteMap[item.type];
    if (route) navigate(route);
  };

  return (
    <Card
      title="消息通知"
      extra={
        <Button onClick={handleMarkAllRead} icon={<CheckOutlined />}>
          全部已读
        </Button>
      }
    >
      <Tabs
        activeKey={activeTab}
        onChange={setActiveTab}
        items={[
          {
            key: 'unread',
            label: (
              <span>
                未读 <Badge count={unreadCount} size="small" />
              </span>
            ),
          },
          { key: 'all', label: '全部' },
        ]}
      />

      <Spin spinning={loading}>
        {data.length === 0 ? (
          <Empty description="暂无通知" />
        ) : (
          <List
            itemLayout="horizontal"
            dataSource={data}
            renderItem={(item) => (
              <List.Item
                style={{
                  cursor: 'pointer',
                  background: item.is_read ? 'transparent' : '#f0f5ff',
                  padding: '12px 16px',
                  borderRadius: 4,
                  marginBottom: 8,
                }}
                onClick={() => handleClick(item)}
                actions={[
                  !item.is_read && (
                    <Button type="link" size="small" key="read" onClick={(e) => { e.stopPropagation(); handleMarkRead(item.id); }}>
                      标记已读
                    </Button>
                  ),
                ].filter(Boolean)}
              >
                <List.Item.Meta
                  avatar={
                    <div style={{ width: 40, height: 40, borderRadius: '50%', background: '#f0f2f5', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      {typeIconMap[item.type] || <BellOutlined style={{ color: '#999' }} />}
                    </div>
                  }
                  title={
                    <span style={{ fontWeight: item.is_read ? 'normal' : 'bold' }}>
                      {item.title}
                    </span>
                  }
                  description={
                    <div>
                      <div style={{ color: '#666', marginBottom: 4 }}>{item.content}</div>
                      <div style={{ color: '#999', fontSize: 12 }}>
                        {item.created_at ? dayjs(item.created_at).format('YYYY-MM-DD HH:mm') : ''}
                      </div>
                    </div>
                  }
                />
              </List.Item>
            )}
          />
        )}
      </Spin>
    </Card>
  );
}
