// client/src/components/ProductCard.vue
<template>
  <div class="product-card card" @click="$emit('click')">
    <div class="product-image">
      <img :src="product.cover_image" :alt="product.title" />
      <span v-if="product.sales > 100" class="sales-tag">已售{{ formatSales(product.sales) }}</span>
    </div>
    <div class="product-info">
      <div class="product-title text-ellipsis-2">{{ product.title }}</div>
      <div class="product-price">
        <span class="price">¥{{ product.price }}</span>
        <span v-if="product.original_price" class="price-old">¥{{ product.original_price }}</span>
      </div>
      <div class="product-meta">
        <span class="shop">{{ product.shop_name }}</span>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  product: {
    type: Object,
    required: true
  }
});

defineEmits(['click']);

const formatSales = (sales) => {
  if (sales >= 10000) {
    return (sales / 10000).toFixed(1) + '万';
  }
  return sales;
};
</script>

<style scoped>
.product-card {
  overflow: hidden;
  background: #fff;
  border-radius: 12px;
}

.product-image {
  position: relative;
  width: 100%;
  aspect-ratio: 1;
  overflow: hidden;
}

.product-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.sales-tag {
  position: absolute;
  top: 8px;
  left: 8px;
  background: rgba(255, 80, 0, 0.9);
  color: #fff;
  font-size: 10px;
  padding: 2px 6px;
  border-radius: 4px;
}

.product-info {
  padding: 10px;
}

.product-title {
  font-size: 13px;
  color: #333;
  line-height: 1.4;
  min-height: 36px;
  margin-bottom: 6px;
}

.product-price {
  display: flex;
  align-items: baseline;
  gap: 6px;
}

.price {
  color: #ff4d4f;
  font-size: 16px;
  font-weight: bold;
}

.price-old {
  color: #999;
  font-size: 11px;
  text-decoration: line-through;
}

.product-meta {
  margin-top: 6px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.shop {
  font-size: 11px;
  color: #999;
}
</style>

// apps/web/src/components/shop/product-card.tsx
'use client';

import { memo } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ShoppingCart, Star } from 'lucide-react';
import { cn, formatPrice, formatCount } from '@/lib/utils';
import type { ProductSPU } from '@pet/shared/types';

interface ProductCardProps {
  product: ProductSPU;
  className?: string;
}

export const ProductCard = memo(function ProductCard({ product, className }: ProductCardProps) {
  const minPrice = product.skus?.length
    ? Math.min(...product.skus.map((s) => s.price))
    : 0;
  const maxOriginalPrice = product.skus?.length
    ? Math.max(...product.skus.map((s) => s.originalPrice))
    : 0;

  return (
    <Link href={`/shop/product/${product.id}`} className={cn('group', className)}>
      <div className="overflow-hidden rounded-lg border bg-card shadow-sm transition-shadow hover:shadow-md">
        <div className="relative aspect-square overflow-hidden">
          <Image
            src={product.mainImage}
            alt={product.name}
            fill
            className="object-cover transition-transform duration-300 group-hover:scale-105"
            sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw"
          />
          {product.skus?.some((s) => s.originalPrice > s.price) && (
            <span className="absolute left-2 top-2 rounded-md bg-pet-orange px-1.5 py-0.5 text-xs font-medium text-white">
              折扣
            </span>
          )}
        </div>
        <div className="p-3">
          <h3 className="line-clamp-2 text-sm font-medium text-foreground">
            {product.name}
          </h3>
          {product.subtitle && (
            <p className="mt-1 line-clamp-1 text-xs text-muted-foreground">
              {product.subtitle}
            </p>
          )}
          <div className="mt-2 flex items-center gap-1">
            {product.rating > 0 && (
              <div className="flex items-center gap-0.5">
                <Star className="h-3 w-3 fill-pet-gold text-pet-gold" />
                <span className="text-xs text-muted-foreground">
                  {product.rating.toFixed(1)}
                </span>
              </div>
            )}
            <span className="text-xs text-muted-foreground">
              {formatCount(product.salesCount)}已售
            </span>
          </div>
          <div className="mt-2 flex items-center justify-between">
            <div className="flex items-baseline gap-1">
              <span className="text-base font-bold text-pet-orange">
                {formatPrice(minPrice)}
              </span>
              {maxOriginalPrice > minPrice && (
                <span className="text-xs text-muted-foreground line-through">
                  {formatPrice(maxOriginalPrice)}
                </span>
              )}
            </div>
            <button
              className="rounded-full p-1.5 text-muted-foreground transition-colors hover:bg-pet-orange hover:text-white"
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
              }}
            >
              <ShoppingCart className="h-4 w-4" />
            </button>
          </div>
        </div>
      </div>
    </Link>
  );
});
