// frontend/src/views/Users.vue
<template>
  <div class="users-page">
    <div class="toolbar">
      <div class="title">用户管理</div>
      <div class="filters">
        <input v-model="keyword" @keyup.enter="loadUsers" placeholder="搜索用户名/昵称..." />
        <select v-model="roleFilter" @change="loadUsers">
          <option value="all">全部角色</option>
          <option value="user">普通用户</option>
          <option value="cs">客服</option>
          <option value="moderator">审核员</option>
          <option value="admin">管理员</option>
        </select>
      </div>
    </div>

    <div class="user-table">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>昵称</th>
            <th>角色</th>
            <th>状态</th>
            <th>注册时间</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="u in users" :key="u.id">
            <td>{{ u.id }}</td>
            <td>{{ u.username }}</td>
            <td>{{ u.nickname || '-' }}</td>
            <td><span class="role-badge" :class="'role-' + u.role">{{ roleText(u.role) }}</span></td>
            <td><span class="status-badge" :class="'status-' + u.status">{{ statusText(u.status) }}</span></td>
            <td>{{ formatTime(u.created_at) }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { userApi } from '../api'

const users = ref([])
const keyword = ref('')
const roleFilter = ref('all')

const loadUsers = async () => {
  try {
    const res = await userApi.list({ keyword: keyword.value, role: roleFilter.value, page_size: 100 })
    users.value = res.data.list
  } catch (e) {
    console.error(e)
  }
}

const roleText = (r) => {
  const map = { admin: '管理员', moderator: '审核员', cs: '客服', user: '普通用户' }
  return map[r] || r
}

const statusText = (s) => {
  const map = { active: '正常', banned: '已封禁', muted: '已禁言' }
  return map[s] || s
}

const formatTime = (t) => {
  if (!t) return '-'
  return new Date(t).toLocaleDateString('zh-CN')
}

onMounted(loadUsers)
</script>

<style scoped>
.users-page { height: 100%; }
.toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}
.title { font-size: 18px; font-weight: 600; color: #1e293b; }
.filters { display: flex; gap: 8px; }
.filters input, .filters select {
  padding: 8px 12px;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  font-size: 14px;
}
.user-table {
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}
table { width: 100%; border-collapse: collapse; }
th, td {
  padding: 12px 16px;
  text-align: left;
  border-bottom: 1px solid #f1f5f9;
  font-size: 14px;
}
th {
  background: #f8fafc;
  font-weight: 600;
  color: #475569;
}
.role-badge {
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}
.role-admin { background: #fef3c7; color: #92400e; }
.role-moderator { background: #dbeafe; color: #1e40af; }
.role-cs { background: #dcfce7; color: #166534; }
.role-user { background: #f1f5f9; color: #475569; }
.status-badge {
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}
.status-active { background: #dcfce7; color: #166534; }
.status-banned { background: #fee2e2; color: #991b1b; }
.status-muted { background: #fef3c7; color: #92400e; }
</style>

// frontend/src/pages/admin/Users.jsx
import React, { useState, useEffect } from 'react'
import api from '../../api'

export default function AdminUsers() {
  const [users, setUsers] = useState([])
  const [filter, setFilter] = useState('')

  useEffect(() => {
    loadUsers()
  }, [filter])

  const loadUsers = () => {
    const params = {}
    if (filter) params.role = filter
    api.get('/admin/users', { params }).then(res => setUsers(res.data))
  }

  const handleVerify = async (id) => {
    try {
      await api.put(`/admin/users/${id}/verify`)
      loadUsers()
    } catch (err) {
      alert('操作失败')
    }
  }

  return (
    <div className="container" style={{ padding: '40px 20px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <h1 style={{ fontSize: '32px', margin: 0 }}>用户管理</h1>
        <select
          className="form-input"
          style={{ width: '200px' }}
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
        >
          <option value="">全部用户</option>
          <option value="client">需求方</option>
          <option value="provider">服务者</option>
          <option value="admin">管理员</option>
        </select>
      </div>

      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <table className="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>用户名</th>
              <th>邮箱</th>
              <th>角色</th>
              <th>认证状态</th>
              <th>评分</th>
              <th>信用分</th>
              <th>注册时间</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            {users.map(user => (
              <tr key={user.id}>
                <td>{user.id}</td>
                <td>{user.username}</td>
                <td>{user.email}</td>
                <td>
                  <span style={{
                    padding: '2px 8px',
                    borderRadius: '4px',
                    fontSize: '12px',
                    background: user.role === 'admin' ? '#fef3c7' : user.role === 'provider' ? '#dbeafe' : '#dcfce7',
                    color: user.role === 'admin' ? '#d97706' : user.role === 'provider' ? '#1d4ed8' : '#15803d'
                  }}>
                    {user.role === 'admin' ? '管理员' : user.role === 'provider' ? '服务者' : '需求方'}
                  </span>
                </td>
                <td>
                  <span style={{
                    padding: '2px 8px',
                    borderRadius: '4px',
                    fontSize: '12px',
                    background: user.is_verified ? '#dcfce7' : '#fef3c7',
                    color: user.is_verified ? '#15803d' : '#d97706'
                  }}>
                    {user.is_verified ? '已认证' : '未认证'}
                  </span>
                </td>
                <td>{user.rating?.toFixed(1) || '5.0'}</td>
                <td>{user.credit_score || 100}</td>
                <td>{new Date(user.created_at).toLocaleDateString()}</td>
                <td>
                  {!user.is_verified && user.role !== 'admin' && (
                    <button
                      className="btn btn-primary"
                      style={{ padding: '4px 12px', fontSize: '12px' }}
                      onClick={() => handleVerify(user.id)}
                    >
                      认证
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
