// src/components/layout/AdminLayout.vue
<template>
  <div class="min-h-screen flex bg-gray-50">
    <aside class="w-64 bg-white border-r border-gray-100 flex flex-col">
      <div class="h-16 flex items-center gap-3 px-5 border-b border-gray-100">
        <div class="w-9 h-9 rounded-lg bg-brand-500 flex items-center justify-center">
          <span class="text-white font-bold">德</span>
        </div>
        <div>
          <div class="text-sm font-bold text-gray-900">大件运营平台</div>
          <div class="text-xs text-gray-500">Deppon Admin</div>
        </div>
      </div>

      <nav class="flex-1 py-4 px-3 space-y-1">
        <router-link
          v-for="item in menuItems"
          :key="item.path"
          :to="item.path"
          class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all duration-200"
          :class="isActive(item.path) ? 'bg-brand-50 text-brand-600' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'"
        >
          <component :is="item.icon" class="w-5 h-5" />
          <span>{{ item.label }}</span>
          <span v-if="item.badge" class="ml-auto px-2 py-0.5 rounded-full text-xs bg-alert-500 text-white">
            {{ item.badge }}
          </span>
        </router-link>
      </nav>

      <div class="p-4 border-t border-gray-100">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-full bg-brand-100 flex items-center justify-center text-brand-600 font-semibold">
            管
          </div>
          <div class="flex-1 min-w-0">
            <div class="text-sm font-medium text-gray-900 truncate">管理员</div>
            <div class="text-xs text-gray-500">运营调度组</div>
          </div>
          <router-link to="/" class="text-gray-400 hover:text-gray-600">
            <component :is="icons.LogOut" class="w-4 h-4" />
          </router-link>
        </div>
      </div>
    </aside>

    <div class="flex-1 flex flex-col min-w-0">
      <header class="h-16 bg-white border-b border-gray-100 flex items-center justify-between px-6">
        <div>
          <h1 class="text-lg font-semibold text-gray-900">{{ pageTitle }}</h1>
          <p class="text-xs text-gray-500">{{ pageSubtitle }}</p>
        </div>
        <div class="flex items-center gap-3">
          <button class="relative p-2 rounded-lg hover:bg-gray-100 text-gray-600">
            <component :is="icons.Bell" class="w-5 h-5" />
            <span class="absolute top-1 right-1 w-2 h-2 rounded-full bg-alert-500"></span>
          </button>
          <button class="p-2 rounded-lg hover:bg-gray-100 text-gray-600">
            <component :is="icons.Settings" class="w-5 h-5" />
          </button>
        </div>
      </header>

      <main class="flex-1 p-6 overflow-auto animate-fade-in">
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import {
  LayoutDashboard, Route, Video, FileText, Truck, Bell, Settings, LogOut
} from 'lucide-vue-next'

const icons = { Bell, Settings, LogOut }
const route = useRoute()

const menuItems = [
  { path: '/admin/dashboard', label: '数据概览', icon: LayoutDashboard },
  { path: '/admin/routing', label: '路由规划引擎', icon: Route },
  { path: '/admin/video-review', label: '装卸视频审核', icon: Video, badge: '3' },
  { path: '/admin/claims', label: '理赔中心', icon: FileText, badge: '1' },
  { path: '/admin/vehicles', label: '车辆监控对接', icon: Truck }
]

const titleMap: Record<string, { title: string; subtitle: string }> = {
  '/admin/dashboard': { title: '数据概览', subtitle: '大件物流运营核心指标实时监控' },
  '/admin/routing': { title: '大件路由规划引擎', subtitle: '智能规避限高限重路段，多方案对比选优' },
  '/admin/video-review': { title: '装卸作业视频审核', subtitle: 'AI智能抽检 + 人工复核' },
  '/admin/claims': { title: '理赔中心', subtitle: 'OCR智能识别 · 结构化录入 · 快速理算' },
  '/admin/vehicles': { title: '车辆监控对接', subtitle: '交通运输部货运车辆动态监控平台' }
}

const pageInfo = computed(() => titleMap[route.path] || { title: '', subtitle: '' })
const pageTitle = computed(() => pageInfo.value.title)
const pageSubtitle = computed(() => pageInfo.value.subtitle)

function isActive(path: string) {
  return route.path === path
}
</script>

// src/layouts/AdminLayout.tsx
import React, { useState } from 'react';
import { Outlet, useLocation, useNavigate } from 'react-router-dom';
import {
  LayoutDashboard,
  FileClock,
  Fingerprint,
  FileText,
  ChevronLeft,
  ChevronRight,
  Shield,
  Bell,
  User,
  LogOut,
} from 'lucide-react';
import { useUserStore } from '@/store/useUserStore';

const AdminLayout: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { user, logout } = useUserStore();
  const [collapsed, setCollapsed] = useState(false);
  const [showUserMenu, setShowUserMenu] = useState(false);

  const menuItems = [
    { icon: LayoutDashboard, label: '督办仪表盘', path: '/admin/dashboard' },
    { icon: FileClock, label: '业务督办', path: '/admin/supervision' },
    { icon: Fingerprint, label: '认证中心', path: '/admin/auth-center' },
    { icon: FileText, label: '政策管理', path: '/admin/policy' },
  ];

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <div className="min-h-screen flex bg-neutral-50">
      <aside
        className={`fixed left-0 top-0 h-screen bg-neutral-700 text-white transition-all duration-300 z-50 ${
          collapsed ? 'w-16' : 'w-60'
        }`}
      >
        <div className="h-16 flex items-center justify-center border-b border-neutral-600">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center flex-shrink-0">
              <Shield className="w-5 h-5 text-white" />
            </div>
            {!collapsed && (
              <div>
                <h1 className="text-sm font-bold">管理后台</h1>
                <p className="text-[10px] text-neutral-400">Admin Console</p>
              </div>
            )}
          </div>
        </div>

        <nav className="py-4">
          {menuItems.map((item) => {
            const isActive = location.pathname === item.path;
            return (
              <button
                key={item.path}
                onClick={() => navigate(item.path)}
                className={`w-full flex items-center gap-3 px-4 py-3 text-sm transition-all duration-200 ${
                  isActive
                    ? 'text-white bg-primary-500/20 border-r-2 border-primary-400'
                    : 'text-neutral-300 hover:text-white hover:bg-neutral-600/50'
                }`}
              >
                <item.icon className="w-5 h-5 flex-shrink-0" />
                {!collapsed && <span>{item.label}</span>}
              </button>
            );
          })}
        </nav>

        <button
          onClick={() => setCollapsed(!collapsed)}
          className="absolute bottom-4 left-1/2 -translate-x-1/2 p-2 text-neutral-400 hover:text-white hover:bg-neutral-600 rounded-lg transition-colors"
        >
          {collapsed ? <ChevronRight className="w-4 h-4" /> : <ChevronLeft className="w-4 h-4" />}
        </button>
      </aside>

      <div className={`flex-1 flex flex-col transition-all duration-300 ${collapsed ? 'ml-16' : 'ml-60'}`}>
        <header className="h-16 bg-white border-b border-neutral-100 flex items-center justify-between px-6 sticky top-0 z-40">
          <div>
            <h2 className="text-lg font-semibold text-neutral-600">
              {menuItems.find((m) => location.pathname.startsWith(m.path))?.label || '管理后台'}
            </h2>
          </div>

          <div className="flex items-center gap-3">
            <button className="relative p-2 text-neutral-400 hover:text-primary-500 hover:bg-primary-50 rounded-lg transition-colors">
              <Bell className="w-5 h-5" />
              <span className="absolute top-1 right-1 w-2 h-2 bg-danger-500 rounded-full"></span>
            </button>

            <div className="relative">
              <button
                onClick={() => setShowUserMenu(!showUserMenu)}
                className="flex items-center gap-2 p-1.5 pr-3 hover:bg-neutral-50 rounded-full transition-colors"
              >
                <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center text-white text-sm font-medium">
                  {user?.name?.charAt(0) || 'A'}
                </div>
                <span className="text-sm font-medium text-neutral-600">{user?.name || '管理员'}</span>
              </button>

              {showUserMenu && (
                <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-xl shadow-dropdown border border-neutral-100 py-2 animate-fade-in">
                  <button
                    onClick={() => {}}
                    className="w-full flex items-center gap-3 px-4 py-2 text-sm text-neutral-600 hover:bg-primary-50 hover:text-primary-500 transition-colors"
                  >
                    <User className="w-4 h-4" />
                    个人信息
                  </button>
                  <button
                    onClick={handleLogout}
                    className="w-full flex items-center gap-3 px-4 py-2 text-sm text-danger-500 hover:bg-danger-50 transition-colors"
                  >
                    <LogOut className="w-4 h-4" />
                    退出登录
                  </button>
                </div>
              )}
            </div>
          </div>
        </header>

        <main className="flex-1 p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
};

export default AdminLayout;
