// apps/admin-client/src/pages/AuditLogs.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Search } from 'lucide-vue-next';
import { adminApi } from '@/api/admin';
import { formatDateTime } from '@shared/utils';
import {
  AuditModuleMap,
} from '@shared/types/admin';
import type {
  AuditLogItem,
  AuditLogQuery,
  AuditLogModule,
  AuditLogResult,
} from '@shared/types/admin';

const modules: AuditLogModule[] = ['AUTH', 'SOCIAL', 'CERTIFY', 'TASK', 'SYSTEM'];
const results: { label: string; value: AuditLogResult }[] = [
  { label: '成功', value: 'SUCCESS' },
  { label: '失败', value: 'FAIL' },
];

const query = ref<AuditLogQuery>({
  module: undefined,
  result: undefined,
  startDate: '',
  endDate: '',
  page: 1,
  size: 20,
});

const logs = ref<AuditLogItem[]>([]);
const total = ref(0);
const loading = ref(false);

async function fetchLogs() {
  loading.value = true;
  try {
    const params: AuditLogQuery = { ...query.value };
    if (!params.module) delete params.module;
    if (!params.result) delete params.result;
    if (!params.startDate) delete params.startDate;
    if (!params.endDate) delete params.endDate;
    const res = await adminApi.getAuditLogs(params);
    logs.value = res.list;
    total.value = res.total;
  } catch {
    // silent
  } finally {
    loading.value = false;
  }
}

function handleSearch() {
  query.value.page = 1;
  fetchLogs();
}

function handleReset() {
  query.value = {
    module: undefined,
    result: undefined,
    startDate: '',
    endDate: '',
    page: 1,
    size: 20,
  };
  fetchLogs();
}

onMounted(fetchLogs);
</script>

<template>
  <div class="space-y-5">
    <div class="bg-white rounded-lg shadow-sm p-5">
      <div class="flex items-center gap-2 mb-4">
        <Search class="w-4 h-4 text-gray-500" />
        <h3 class="text-base font-semibold text-gray-800">筛选条件</h3>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div>
          <label class="block text-sm text-gray-600 mb-1.5">模块</label>
          <select
            v-model="query.module"
            class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary"
          >
            <option :value="undefined">全部</option>
            <option v-for="m in modules" :key="m" :value="m">{{ AuditModuleMap[m] }}</option>
          </select>
        </div>

        <div>
          <label class="block text-sm text-gray-600 mb-1.5">操作类型</label>
          <input
            v-model="query.operation"
            type="text"
            placeholder="输入操作关键词"
            class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary"
          />
        </div>

        <div>
          <label class="block text-sm text-gray-600 mb-1.5">时间范围</label>
          <div class="flex items-center gap-2">
            <input
              v-model="query.startDate"
              type="date"
              class="flex-1 px-2 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary"
            />
            <span class="text-gray-400 text-xs">至</span>
            <input
              v-model="query.endDate"
              type="date"
              class="flex-1 px-2 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary"
            />
          </div>
        </div>

        <div>
          <label class="block text-sm text-gray-600 mb-1.5">结果</label>
          <select
            v-model="query.result"
            class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary"
          >
            <option :value="undefined">全部</option>
            <option v-for="r in results" :key="r.value" :value="r.value">{{ r.label }}</option>
          </select>
        </div>
      </div>

      <div class="flex gap-3 mt-4">
        <button
          class="px-5 py-2 bg-primary text-white rounded-lg text-sm hover:bg-blue-700 transition-colors"
          @click="handleSearch"
        >
          查询
        </button>
        <button
          class="px-5 py-2 border border-gray-200 text-gray-600 rounded-lg text-sm hover:bg-gray-50 transition-colors"
          @click="handleReset"
        >
          重置
        </button>
      </div>
    </div>

    <div class="bg-white rounded-lg shadow-sm p-5">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-base font-semibold text-gray-800">
          审计日志（共 {{ total }} 条）
        </h3>
      </div>

      <div class="overflow-x-auto">
        <table class="w-full text-sm table-striped">
          <thead>
            <tr class="border-b border-gray-200">
              <th class="text-left py-3 px-3 text-gray-500 font-medium">时间</th>
              <th class="text-left py-3 px-3 text-gray-500 font-medium">用户</th>
              <th class="text-left py-3 px-3 text-gray-500 font-medium">操作</th>
              <th class="text-left py-3 px-3 text-gray-500 font-medium">模块</th>
              <th class="text-left py-3 px-3 text-gray-500 font-medium">IP</th>
              <th class="text-left py-3 px-3 text-gray-500 font-medium">设备</th>
              <th class="text-center py-3 px-3 text-gray-500 font-medium">结果</th>
              <th class="text-left py-3 px-3 text-gray-500 font-medium">详情</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="loading">
              <td colspan="8" class="py-8 text-center text-gray-400">加载中...</td>
            </tr>
            <tr v-else-if="!logs.length">
              <td colspan="8" class="py-8 text-center text-gray-400">暂无数据</td>
            </tr>
            <tr
              v-for="log in logs"
              :key="log.id"
              class="border-b border-gray-100"
            >
              <td class="py-3 px-3 text-gray-500 whitespace-nowrap">{{ formatDateTime(log.timestamp) }}</td>
              <td class="py-3 px-3">{{ log.userNameMasked }}</td>
              <td class="py-3 px-3">{{ log.operation }}</td>
              <td class="py-3 px-3">
                <span class="status-tag status-tag-info">{{ AuditModuleMap[log.module] }}</span>
              </td>
              <td class="py-3 px-3 tabular-nums text-gray-500">{{ log.ip }}</td>
              <td class="py-3 px-3 text-gray-500 max-w-[200px] truncate">{{ log.deviceInfo }}</td>
              <td class="py-3 px-3 text-center">
                <span
                  class="status-tag"
                  :class="log.result === 'SUCCESS' ? 'status-tag-success' : 'status-tag-danger'"
                >
                  {{ log.result === 'SUCCESS' ? '成功' : '失败' }}
                </span>
              </td>
              <td class="py-3 px-3 text-gray-500 max-w-[200px] truncate" :title="log.detail">
                {{ log.detail }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

// src/pages/admin/AuditLogs.tsx
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Search, Filter } from 'lucide-react';

interface AuditLog {
  id: number;
  timestamp: string;
  user_name: string;
  action: string;
  resource: string;
  details: string;
}

export default function AuditLogs() {
  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionFilter, setActionFilter] = useState('');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');

  const fetchLogs = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (actionFilter) params.set('action', actionFilter);
      if (dateFrom) params.set('from', dateFrom);
      if (dateTo) params.set('to', dateTo);
      const data = await api<AuditLog[]>(`/admin/audit?${params.toString()}`);
      setLogs(data);
    } catch {} finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchLogs(); }, []);

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold text-[#1E293B]">审计日志</h1>

      <div className="bg-white rounded-lg shadow-sm p-4">
        <div className="flex items-end gap-4">
          <div className="flex-1">
            <label className="block text-xs font-medium text-gray-500 mb-1">操作类型</label>
            <div className="relative">
              <Filter className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <select
                value={actionFilter}
                onChange={(e) => setActionFilter(e.target.value)}
                className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0F6CBD]"
              >
                <option value="">全部</option>
                <option value="login">登录</option>
                <option value="create">创建</option>
                <option value="update">更新</option>
                <option value="delete">删除</option>
                <option value="dispatch">派单</option>
              </select>
            </div>
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">开始日期</label>
            <input
              type="date"
              value={dateFrom}
              onChange={(e) => setDateFrom(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0F6CBD]"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">结束日期</label>
            <input
              type="date"
              value={dateTo}
              onChange={(e) => setDateTo(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0F6CBD]"
            />
          </div>
          <button onClick={fetchLogs} className="flex items-center gap-2 bg-[#0F6CBD] text-white px-4 py-2 rounded-lg text-sm hover:bg-[#0D5DA8]">
            <Search className="w-4 h-4" /> 查询
          </button>
        </div>
      </div>

      {loading ? (
        <div className="bg-white rounded-lg shadow-sm p-6 animate-pulse space-y-3">
          {[1, 2, 3].map((i) => (<div key={i} className="h-10 bg-gray-200 rounded" />))}
        </div>
      ) : (
        <div className="bg-white rounded-lg shadow-sm overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="text-left py-3 px-4 font-medium text-gray-600">时间</th>
                <th className="text-left py-3 px-4 font-medium text-gray-600">用户</th>
                <th className="text-left py-3 px-4 font-medium text-gray-600">操作</th>
                <th className="text-left py-3 px-4 font-medium text-gray-600">资源</th>
                <th className="text-left py-3 px-4 font-medium text-gray-600">详情</th>
              </tr>
            </thead>
            <tbody>
              {logs.length === 0 ? (
                <tr><td colSpan={5} className="py-8 text-center text-gray-400">暂无日志</td></tr>
              ) : (
                logs.map((log) => (
                  <tr key={log.id} className="border-b border-gray-50 hover:bg-gray-50">
                    <td className="py-3 px-4 text-gray-500 whitespace-nowrap">{new Date(log.timestamp).toLocaleString()}</td>
                    <td className="py-3 px-4">{log.user_name}</td>
                    <td className="py-3 px-4"><span className="text-xs px-2 py-0.5 rounded-full bg-blue-50 text-blue-700">{log.action}</span></td>
                    <td className="py-3 px-4">{log.resource}</td>
                    <td className="py-3 px-4 text-gray-500 max-w-xs truncate">{log.details}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
