// frontend/src/pages/Chat.jsx
import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import request, { showToast } from '../utils/request';
import useAuthStore from '../store/authStore';

function Chat() {
  const { chatId } = useParams();
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [chatInfo, setChatInfo] = useState({});
  const messagesEndRef = useRef(null);

  const fetchMessages = async () => {
    try {
      const res = await request.get(`/chats/${chatId}/messages`);
      if (res?.success) {
        setMessages(res.data || []);
      }
    } catch (e) {
      showToast('获取消息失败');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMessages();
  }, [chatId]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const sendMessage = async () => {
    if (!input.trim() || sending) return;

    setSending(true);
    try {
      const res = await request.post(`/chats/${chatId}/messages`, {
        type: 0,
        content: input.trim()
      });
      if (res?.success) {
        setMessages(prev => [...prev, res.data]);
        setInput('');
      }
    } catch (e) {
      showToast('发送失败');
    } finally {
      setSending(false);
    }
  };

  const sendHeart = async () => {
    if (sending) return;
    setSending(true);
    try {
      const res = await request.post(`/chats/${chatId}/messages`, {
        type: 2,
        content: '❤️'
      });
      if (res?.success) {
        setMessages(prev => [...prev, res.data]);
      }
    } catch (e) {
      showToast('发送失败');
    } finally {
      setSending(false);
    }
  };

  const formatTime = (time) => {
    if (!time) return '';
    return new Date(time).toLocaleTimeString('zh-CN', { 
      hour: '2-digit', 
      minute: '2-digit' 
    });
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
      <div className="header">
        <div className="header-back" onClick={() => navigate(-1)}>←</div>
        <div className="header-title">{chatInfo.name || '聊天'}</div>
        <div style={{ cursor: 'pointer', fontSize: 18 }} onClick={() => setShowSettings(!showSettings)}>
          ⋮
        </div>
      </div>

      {showSettings && (
        <div style={{ 
          background: '#fff', 
          padding: 16, 
          borderBottom: '1px solid var(--border)' 
        }}>
          <div style={{ display: 'flex', gap: 24, marginBottom: 16 }}>
            <div style={{ textAlign: 'center', cursor: 'pointer' }}>
              <div style={{ fontSize: 20 }}>🔕</div>
              <div style={{ fontSize: 12, marginTop: 4 }}>免打扰</div>
            </div>
            <div style={{ textAlign: 'center', cursor: 'pointer' }}>
              <div style={{ fontSize: 20 }}>📌</div>
              <div style={{ fontSize: 12, marginTop: 4 }}>置顶</div>
            </div>
            <div style={{ textAlign: 'center', cursor: 'pointer', color: '#f5222d' }}>
              <div style={{ fontSize: 20 }}>🗑️</div>
              <div style={{ fontSize: 12, marginTop: 4 }}>删除</div>
            </div>
            <div style={{ textAlign: 'center', cursor: 'pointer', color: '#f5222d' }}>
              <div style={{ fontSize: 20 }}>⚠️</div>
              <div style={{ fontSize: 12, marginTop: 4 }}>投诉</div>
            </div>
          </div>
        </div>
      )}

      <div style={{ flex: 1, overflowY: 'auto', padding: 16, background: '#f5f5f5' }}>
        {loading ? (
          <div className="loading">
            <div className="spinner" />
          </div>
        ) : (
          messages.map((msg, index) => {
            const isMe = msg.sender_id === user?.id;
            const showTime = index === 0 || 
              new Date(msg.created_at) - new Date(messages[index - 1].created_at) > 300000;

            return (
              <div key={msg.id}>
                {showTime && (
                  <div style={{ 
                    textAlign: 'center', 
                    fontSize: 12, 
                    color: '#999', 
                    margin: '12px 0' 
                  }}>
                    {formatTime(msg.created_at)}
                  </div>
                )}
                <div style={{
                  display: 'flex',
                  justifyContent: isMe ? 'flex-end' : 'flex-start',
                  marginBottom: 16
                }}>
                  {!isMe && (
                    <img
                      src={msg.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${msg.sender_id}`}
                      alt="avatar"
                      className="avatar-sm"
                      style={{ marginRight: 8 }}
                    />
                  )}
                  <div style={{
                    maxWidth: '70%',
                    padding: '10px 14px',
                    borderRadius: isMe ? '18px 4px 18px 18px' : '4px 18px 18px 18px',
                    background: isMe ? 'var(--primary)' : '#fff',
                    color: isMe ? '#fff' : 'var(--text)',
                    wordBreak: 'break-word'
                  }}>
                    {msg.content === '❤️' ? (
                      <span style={{ fontSize: 48 }}>❤️</span>
                    ) : (
                      msg.content
                    )}
                  </div>
                  {isMe && (
                    <img
                      src={user?.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${user?.id}`}
                      alt="avatar"
                      className="avatar-sm"
                      style={{ marginLeft: 8 }}
                    />
                  )}
                </div>
              </div>
            );
          })
        )}
        <div ref={messagesEndRef} />
      </div>

      <div style={{ 
        padding: '12px 16px', 
        background: '#fff', 
        borderTop: '1px solid var(--border)',
        paddingBottom: 24
      }}>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <span style={{ fontSize: 24, cursor: 'pointer' }}>📷</span>
          <span style={{ fontSize: 24, cursor: 'pointer' }}>😊</span>
          <input
            type="text"
            className="input"
            placeholder="输入消息..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
            style={{ flex: 1 }}
          />
          <span 
            style={{ fontSize: 24, cursor: 'pointer' }} 
            onClick={sendHeart}
          >
            ❤️
          </span>
          <button
            className="btn btn-primary"
            onClick={sendMessage}
            disabled={!input.trim() || sending}
            style={{ padding: '8px 16px' }}
          >
            发送
          </button>
        </div>
      </div>
    </div>
  );
}

export default Chat;

// frontend/src/views/Chat.vue
<template>
  <div class="chat-page">
    <van-nav-bar :title="chatUser?.nickname || chatUser?.username || '聊天'" left-arrow @click-left="goBack" fixed />

    <div class="messages-container" ref="messagesContainer">
      <van-loading v-if="loading" class="loading" />
      <div v-else class="message-list">
        <div v-if="messages.length === 0" class="empty-state">
          <van-empty description="暂无消息，开始聊天吧" />
        </div>
        <div v-for="message in messages" :key="message.id" class="message-item" :class="{ 'is-mine': message.senderId === currentUserId }">
          <van-image
            :src="message.senderId === currentUserId ? (userStore.user?.avatar || 'https://picsum.photos/100/100') : (chatUser?.avatar || 'https://picsum.photos/100/100')"
            round
            class="message-avatar"
          />
          <div class="message-content">
            <div class="message-text">{{ message.content }}</div>
            <div class="message-time">{{ formatTime(message.createdAt) }}</div>
          </div>
        </div>
      </div>
    </div>

    <div class="input-area">
      <van-field
        v-model="inputMessage"
        placeholder="输入消息..."
        :border="false"
        @keyup.enter="sendMessage"
      />
      <van-button type="primary" size="small" @click="sendMessage" :loading="sending">发送</van-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, nextTick, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { showToast } from 'vant'
import dayjs from 'dayjs'
import request from '@/utils/request'
import { useUserStore } from '@/stores/user'

interface Message {
  id: number
  content: string
  senderId: number
  receiverId: number
  isRead: boolean
  createdAt: string
}

interface User {
  id: number
  username: string
  nickname?: string
  avatar?: string
}

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()

const messages = ref<Message[]>([])
const loading = ref(true)
const sending = ref(false)
const inputMessage = ref('')
const chatUser = ref<User | null>(null)
const messagesContainer = ref<HTMLElement | null>(null)

const currentUserId = computed(() => userStore.user?.id || 0)

const formatTime = (time: string) => {
  return dayjs(time).format('HH:mm')
}

const fetchMessages = async () => {
  try {
    const res = await request.get(`/messages/${route.params.userId}`)
    messages.value = res.data
    scrollToBottom()
  } catch {
    showToast('加载失败')
  } finally {
    loading.value = false
  }
}

const fetchChatUser = async () => {
  const userId = Number(route.params.userId)
  chatUser.value = {
    id: userId,
    username: `用户${userId}`,
    nickname: `用户${userId}`
  }
}

const sendMessage = async () => {
  if (!inputMessage.value.trim() || sending.value) return
  sending.value = true
  try {
    await request.post(`/messages/${route.params.userId}`, {
      content: inputMessage.value
    })
    inputMessage.value = ''
    await fetchMessages()
  } catch {
    showToast('发送失败')
  } finally {
    sending.value = false
  }
}

const scrollToBottom = () => {
  nextTick(() => {
    if (messagesContainer.value) {
      messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
    }
  })
}

const goBack = () => {
  router.back()
}

onMounted(() => {
  fetchChatUser()
  fetchMessages()
})
</script>

<style scoped>
.chat-page {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: #f5f5f5;
}

.messages-container {
  flex: 1;
  overflow-y: auto;
  padding: 56px 10px 70px;
}

.loading {
  padding: 50px 0;
  text-align: center;
}

.message-list {
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.message-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
}

.message-item.is-mine {
  flex-direction: row-reverse;
}

.message-avatar {
  width: 40px;
  height: 40px;
  flex-shrink: 0;
}

.message-content {
  max-width: 70%;
}

.message-text {
  background: #fff;
  padding: 10px 15px;
  border-radius: 12px;
  font-size: 14px;
  line-height: 1.5;
  word-break: break-word;
}

.is-mine .message-text {
  background: #1989fa;
  color: #fff;
}

.message-time {
  font-size: 11px;
  color: #999;
  margin-top: 4px;
}

.is-mine .message-time {
  text-align: right;
}

.input-area {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  max-width: 480px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  padding: 10px;
  background: #fff;
  border-top: 1px solid #eee;
}

.input-area .van-field {
  flex: 1;
  margin-right: 10px;
}

.empty-state {
  padding: 50px 0;
}
</style>
