// frontend/src/pages/PostDetail.jsx
import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import api from '../api/client'
import { useAuthStore } from '../store/authStore'

export default function PostDetail() {
  const { id } = useParams()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [post, setPost] = useState(null)
  const [comment, setComment] = useState('')
  const { isAuthenticated } = useAuthStore()

  useEffect(() => {
    loadPost()
  }, [id])

  const loadPost = async () => {
    try {
      setLoading(true)
      setError(null)
      const res = await api.get(`/posts/${id}`)
      setPost(res.data.data)
    } catch (err) {
      setError('加载失败，请重试')
    } finally {
      setLoading(false)
    }
  }

  const handleLike = async () => {
    if (!isAuthenticated) {
      alert('请先登录')
      return
    }
    try {
      await api.post(`/posts/${id}/like`)
      loadPost()
    } catch (err) {
      alert('点赞失败')
    }
  }

  const handleComment = async (e) => {
    e.preventDefault()
    if (!isAuthenticated) {
      alert('请先登录')
      return
    }
    if (!comment.trim()) return
    
    try {
      await api.post(`/posts/${id}/comment`, { content: comment })
      setComment('')
      loadPost()
    } catch (err) {
      alert('评论失败')
    }
  }

  if (loading) return <div className="loading">加载中...</div>
  if (error) return <div className="error">{error}</div>
  if (!post) return <div className="empty">帖子不存在</div>

  return (
    <div className="container" style={{ maxWidth: '800px' }}>
      <div className="card">
        <h1 style={{ fontSize: '24px', marginBottom: '15px' }}>{post.title}</h1>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '20px', paddingBottom: '20px', borderBottom: '1px solid #e5e7eb' }}>
          <div style={{ 
            width: '40px', height: '40px', borderRadius: '50%', background: '#ff6b6b20', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px' }}>
            👤
          </div>
          <div>
            <div style={{ fontWeight: '500' }}>{post.nickname || '匿名用户'}</div>
            <div style={{ fontSize: '12px', color: '#9ca3af' }}>
              {new Date(post.created_at).toLocaleString()}
            </div>
          </div>
          <div style={{ marginLeft: 'auto', display: 'flex', gap: '20px', fontSize: '14px', color: '#6b7280' }}>
            <span>👁️ {post.views || 0}</span>
            <span>❤️ {post.likes || 0}</span>
            <span>💬 {post.comments || 0}</span>
          </div>
        </div>

        <div style={{ fontSize: '16px', lineHeight: '1.8', color: '#374151', marginBottom: '30px', whiteSpace: 'pre-wrap' }}>
          {post.content}
        </div>

        <button 
          onClick={handleLike}
          className="btn btn-primary"
          style={{ marginBottom: '30px' }}
        >
          ❤️ 点赞
        </button>

        <div>
          <h3 style={{ fontSize: '18px', marginBottom: '20px' }}>评论 ({post.comments?.length || 0})</h3>
          
          <form onSubmit={handleComment} style={{ marginBottom: '25px' }}>
            <textarea
              value={comment}
              onChange={(e) => setComment(e.target.value)}
              placeholder="写下你的评论..."
              style={{
                width: '100%',
                padding: '12px',
                border: '1px solid #e5e7eb',
                borderRadius: '8px',
                minHeight: '80px',
                marginBottom: '10px',
                fontSize: '14px'
              }}
            />
            <button type="submit" className="btn btn-primary" style={{ fontSize: '14px' }}>
              发表评论
            </button>
          </form>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
            {(!post.comments || post.comments.length === 0) ? (
              <p style={{ textAlign: 'center', color: '#9ca3af', padding: '20px' }}>暂无评论</p>
            ) : (
              post.comments.map(c => (
                <div key={c.id} style={{ padding: '15px', background: '#f9fafb', borderRadius: '8px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
                    <div style={{ 
                      width: '30px', height: '30px', borderRadius: '50%', background: '#4ecdc420', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '16px' }}>
                      👤
                    </div>
                    <span style={{ fontWeight: '500', fontSize: '14px' }}>{c.nickname || '匿名用户'}</span>
                    <span style={{ fontSize: '12px', color: '#9ca3af' }}>
                      {new Date(c.created_at).toLocaleString()}
                    </span>
                  </div>
                  <p style={{ fontSize: '14px', color: '#374151', marginLeft: '40px' }}>{c.content}</p>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/PostDetail.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useUserStore } from '../store/user'
import request from '../utils/request'
import { ElMessage } from 'element-plus'

const route = useRoute()
const userStore = useUserStore()

const loading = ref(true)
const error = ref('')
const post = ref(null)
const commentContent = ref('')
const submitting = ref(false)

const fetchPost = async () => {
  try {
    loading.value = true
    error.value = ''
    const res = await request.get(`/community/posts/${route.params.id}`)
    post.value = res.data
  } catch (err) {
    console.error('Fetch post error:', err)
    error.value = '加载失败，请点击重试'
  } finally {
    loading.value = false
  }
}

const handleLike = async () => {
  if (!userStore.isLoggedIn) {
    ElMessage.warning('请先登录')
    return
  }
  try {
    await request.post(`/community/posts/${route.params.id}/like`)
    post.value.is_liked = !post.value.is_liked
    post.value.likes_count += post.value.is_liked ? 1 : -1
    ElMessage.success(post.value.is_liked ? '点赞成功' : '取消点赞')
  } catch (err) {
    console.error('Like error:', err)
    ElMessage.error('操作失败')
  }
}

const handleComment = async () => {
  if (!userStore.isLoggedIn) {
    ElMessage.warning('请先登录')
    return
  }
  if (!commentContent.value.trim()) {
    ElMessage.warning('请输入评论内容')
    return
  }
  try {
    submitting.value = true
    await request.post(`/community/posts/${route.params.id}/comments`, {
      content: commentContent.value
    })
    ElMessage.success('评论成功')
    commentContent.value = ''
    fetchPost()
  } catch (err) {
    console.error('Comment error:', err)
    ElMessage.error('评论失败')
  } finally {
    submitting.value = false
  }
}

onMounted(() => {
  fetchPost()
})
</script>

<template>
  <Layout>
    <div class="post-detail-page">
      <div class="container">
        <el-skeleton v-if="loading" :rows="10" animated />
        
        <div v-else-if="error" class="error-state">
          <el-empty description="加载失败">
            <el-button type="primary" @click="fetchPost">点击重试</el-button>
          </el-empty>
        </div>

        <template v-else-if="post">
          <div class="post-header">
            <div class="author-info">
              <el-avatar :size="48" :src="post.avatar">
                {{ post.nickname?.charAt(0) || '用' }}
              </el-avatar>
              <div class="author-detail">
                <span class="author-name">{{ post.nickname }}</span>
                <el-tag size="small" type="info">{{ post.category }}</el-tag>
              </div>
            </div>
          </div>

          <h1 class="post-title">{{ post.title }}</h1>
          
          <div class="post-content">
            <p>{{ post.content }}</p>
          </div>

          <div class="post-actions">
            <el-button :type="post.is_liked ? 'primary' : 'default'" @click="handleLike">
              <el-icon><Star :filled="post.is_liked" /></el-icon>
              {{ post.likes_count || 0 }} 点赞
            </el-button>
            <el-button>
              <el-icon><ChatDotRound /></el-icon>
              {{ post.comments_count || 0 }} 评论
            </el-button>
            <el-button>
              <el-icon><View /></el-icon>
              {{ post.views_count || 0 }} 浏览
            </el-button>
          </div>

          <div class="comment-section">
            <h3>发表评论</h3>
            <div class="comment-input">
              <el-input
                v-model="commentContent"
                type="textarea"
                :rows="3"
                placeholder="写下你的评论..."
              />
              <el-button 
                type="primary" 
                :loading="submitting"
                @click="handleComment"
                class="submit-btn"
              >
                发表评论
              </el-button>
            </div>

            <div class="comments-list">
              <h3>全部评论 ({{ post.comments?.length || 0 }})</h3>
              <div v-if="!post.comments?.length" class="empty-comments">
                <el-empty description="暂无评论，快来抢沙发" :image-size="80" />
              </div>
              <div v-for="comment in post.comments" :key="comment.id" class="comment-item">
                <el-avatar :size="36" :src="comment.avatar">
                  {{ comment.nickname?.charAt(0) || '用' }}
                </el-avatar>
                <div class="comment-content">
                  <div class="comment-header">
                    <span class="comment-author">{{ comment.nickname }}</span>
                  </div>
                  <p class="comment-text">{{ comment.content }}</p>
                </div>
              </div>
            </div>
          </div>
        </template>
      </div>
    </div>
  </Layout>
</template>

<style scoped>
.post-detail-page {
  min-height: 80vh;
}

.post-header {
  margin-bottom: 24px;
}

.author-info {
  display: flex;
  align-items: center;
  gap: 16px;
}

.author-detail {
  display: flex;
  align-items: center;
  gap: 12px;
}

.author-name {
  font-size: 16px;
  font-weight: 500;
  color: #303133;
}

.post-title {
  font-size: 28px;
  font-weight: 600;
  color: #303133;
  margin: 0 0 24px;
  line-height: 1.4;
}

.post-content {
  background: white;
  border-radius: 12px;
  padding: 30px;
  margin-bottom: 24px;
}

.post-content p {
  color: #303133;
  font-size: 16px;
  line-height: 1.8;
  margin: 0;
}

.post-actions {
  display: flex;
  gap: 12px;
  margin-bottom: 30px;
}

.comment-section {
  background: white;
  border-radius: 12px;
  padding: 30px;
}

.comment-section h3 {
  font-size: 18px;
  font-weight: 600;
  color: #303133;
  margin: 0 0 16px;
}

.comment-input {
  margin-bottom: 30px;
}

.submit-btn {
  margin-top: 12px;
}

.comments-list {
  border-top: 1px solid #e4e7ed;
  padding-top: 24px;
}

.empty-comments {
  padding: 30px 0;
}

.comment-item {
  display: flex;
  gap: 12px;
  padding: 16px 0;
  border-bottom: 1px solid #f0f0f0;
}

.comment-item:last-child {
  border-bottom: none;
}

.comment-content {
  flex: 1;
}

.comment-header {
  margin-bottom: 8px;
}

.comment-author {
  font-size: 14px;
  font-weight: 500;
  color: #303133;
}

.comment-text {
  color: #606266;
  font-size: 14px;
  line-height: 1.6;
  margin: 0;
}

.error-state {
  padding: 60px 0;
  text-align: center;
}
</style>
